//! Board plot as SVG (File ▸ Plot with format SVG): every visible layer in KiCad's
//! default colours, back to front, in millimetre units.
use crate::footprints::PadShape;
use crate::geom::{mm, Pt};
use crate::pcb::{Board, DrawShape, Layer};

pub fn color(layer: Layer) -> (u8, u8, u8) {
    match layer {
        Layer::FCu => (200, 52, 52),
        Layer::BCu => (77, 127, 196),
        Layer::FPaste => (180, 160, 154),
        Layer::BPaste => (0, 194, 194),
        Layer::FSilkS => (242, 237, 161),
        Layer::BSilkS => (232, 178, 167),
        Layer::FMask => (216, 100, 255),
        Layer::BMask => (2, 255, 238),
        Layer::EdgeCuts => (208, 210, 205),
        Layer::FCrtYd => (255, 38, 226),
        Layer::BCrtYd => (38, 233, 255),
        Layer::FFab => (175, 175, 175),
        Layer::BFab => (88, 93, 132),
    }
}
fn n(v: i64) -> String {
    mm(v, 1_000_000)
}
fn hex((r, g, b): (u8, u8, u8)) -> String {
    format!("#{r:02X}{g:02X}{b:02X}")
}

/// Plot `layers` (drawn in the order given) into one SVG document.
pub fn plot(board: &Board, layers: &[Layer], title: &str) -> String {
    let bounds = board.outline_bounds().unwrap_or_else(|| {
        let mut r = crate::geom::Rect::new(Pt::new(0, 0), Pt::new(50_000_000, 40_000_000));
        for f in &board.footprints {
            r = r.union(&f.bounds());
        }
        r
    });
    let pad = 2_000_000;
    let (x0, y0) = (bounds.min.x - pad, bounds.min.y - pad);
    let (w, h) = (bounds.width() + 2 * pad, bounds.height() + 2 * pad);
    let mut out = vec![
        "<?xml version=\"1.0\" standalone=\"no\"?>".to_owned(),
        "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">".into(),
        format!(
            "<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" width=\"{}mm\" height=\"{}mm\" viewBox=\"{} {} {} {}\">",
            n(w), n(h), n(x0), n(y0), n(w), n(h)
        ),
        format!("<title>SVG Image created as {title} date by KiCad 8.0.4</title>"),
        "<desc>Image generated by PCBNEW</desc>".into(),
    ];
    for &layer in layers {
        let c = hex(color(layer));
        out.push(format!("<g id=\"{}\" style=\"fill:{c}; stroke:{c}; stroke-linecap:round; stroke-linejoin:round\">", layer.name()));
        let line = |a: Pt, b: Pt, width: i64, out: &mut Vec<String>| {
            out.push(format!(
                "<path style=\"fill:none; stroke-width:{}\" d=\"M {} {} L {} {}\"/>",
                n(width),
                n(a.x),
                n(a.y),
                n(b.x),
                n(b.y)
            ));
        };
        if layer.is_copper() {
            for z in board.zones.iter().filter(|z| z.layer == layer) {
                for r in &z.fill {
                    out.push(format!(
                        "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" style=\"stroke:none\"/>",
                        n(r.min.x),
                        n(r.min.y),
                        n(r.width()),
                        n(r.height())
                    ));
                }
            }
            for t in board.tracks.iter().filter(|t| t.layer == layer) {
                line(t.a, t.b, t.width, &mut out);
            }
        }
        for f in &board.footprints {
            for l in f.lines.iter().filter(|l| f.layer(l.layer) == layer) {
                line(f.to_board(l.a), f.to_board(l.b), l.width, &mut out);
            }
            if f.layer(Layer::FSilkS) == layer {
                let b = f.bounds();
                let h = 1_000_000;
                let tw = crate::font::width(&f.reference, h);
                let origin = if f.back {
                    (b.center().x + tw / 2, b.min.y - h - 400_000)
                } else {
                    (b.center().x - tw / 2, b.min.y - h - 400_000)
                };
                for stroke in crate::font::strokes(&f.reference, origin, h, f.back) {
                    for pair in stroke.windows(2) {
                        line(
                            Pt::new(pair[0].0, pair[0].1),
                            Pt::new(pair[1].0, pair[1].1),
                            150_000,
                            &mut out,
                        );
                    }
                }
            }
            if !layer.is_copper() && !matches!(layer, Layer::FMask | Layer::BMask) {
                continue;
            }
            for p in &f.pads {
                let on_layer = f.pad_layers(p).contains(&layer)
                    || (matches!(layer, Layer::FMask | Layer::BMask)
                        && f.pad_layers(p).contains(&if layer == Layer::FMask {
                            Layer::FCu
                        } else {
                            Layer::BCu
                        }));
                if !on_layer {
                    continue;
                }
                let c = f.pad_pos(p);
                let (w, h) = f.pad_size(p);
                if !f.orthogonal() && p.shape != PadShape::Circle {
                    // A pad turned to an arbitrary angle: its true outline.
                    match f.pad_shape(p) {
                        crate::pcb::Shape::Seg { a, b, r } => out.push(format!(
                            "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" style=\"stroke-width:{}; stroke-linecap:round\"/>",
                            n(a.x), n(a.y), n(b.x), n(b.y), n(2 * r)
                        )),
                        shape => {
                            let pts: Vec<String> = shape
                                .corners()
                                .unwrap_or([c; 4])
                                .iter()
                                .map(|q| format!("{},{}", n(q.x), n(q.y)))
                                .collect();
                            out.push(format!(
                                "<polygon points=\"{}\" style=\"stroke:none\"/>",
                                pts.join(" ")
                            ));
                        }
                    }
                    if p.drill > 0 && layer.is_copper() {
                        out.push(format!("<circle cx=\"{}\" cy=\"{}\" r=\"{}\" style=\"fill:#000000; stroke:none\"/>", n(c.x), n(c.y), n(p.drill / 2)));
                    }
                    continue;
                }
                match p.shape {
                    PadShape::Circle => out.push(format!(
                        "<circle cx=\"{}\" cy=\"{}\" r=\"{}\" style=\"stroke:none\"/>",
                        n(c.x),
                        n(c.y),
                        n(w / 2)
                    )),
                    PadShape::Oval => {
                        let r = w.min(h) / 2;
                        out.push(format!(
                            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" rx=\"{}\" style=\"stroke:none\"/>",
                            n(c.x - w / 2), n(c.y - h / 2), n(w), n(h), n(r)
                        ));
                    }
                    PadShape::Rect | PadShape::RoundRect => {
                        let r = if p.shape == PadShape::RoundRect {
                            w.min(h) / 4
                        } else {
                            0
                        };
                        out.push(format!(
                            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" rx=\"{}\" style=\"stroke:none\"/>",
                            n(c.x - w / 2), n(c.y - h / 2), n(w), n(h), n(r)
                        ));
                    }
                }
                if p.drill > 0 && layer.is_copper() {
                    out.push(format!("<circle cx=\"{}\" cy=\"{}\" r=\"{}\" style=\"fill:#000000; stroke:none\"/>", n(c.x), n(c.y), n(p.drill / 2)));
                }
            }
        }
        if layer.is_copper() {
            for v in &board.vias {
                out.push(format!(
                    "<circle cx=\"{}\" cy=\"{}\" r=\"{}\" style=\"stroke:none\"/>",
                    n(v.pos.x),
                    n(v.pos.y),
                    n(v.diameter / 2)
                ));
                out.push(format!(
                    "<circle cx=\"{}\" cy=\"{}\" r=\"{}\" style=\"fill:#000000; stroke:none\"/>",
                    n(v.pos.x),
                    n(v.pos.y),
                    n(v.drill / 2)
                ));
            }
        }
        for d in board.drawings.iter().filter(|d| d.layer == layer) {
            match d.shape {
                DrawShape::Line { a, b } => line(a, b, d.width, &mut out),
                DrawShape::Rect { a, b } => {
                    let c = [a, Pt::new(b.x, a.y), b, Pt::new(a.x, b.y)];
                    for i in 0..4 {
                        line(c[i], c[(i + 1) % 4], d.width, &mut out);
                    }
                }
            }
        }
        out.push("</g>".into());
    }
    out.push("</svg>".into());
    out.join("\n") + "\n"
}
