#!/usr/bin/env python3
"""Regenerates src/uprops.rs: code point ranges for the Unicode property escapes
(`\\p{...}`) the regex engine has no tables for, from the Unicode Character
Database of the version Node v24 ships (17.0.0).

    python3 crates/languages/jsvm/tools/generate_uprops.py [UnicodeData.txt emoji-data.txt]

Without arguments the two files are downloaded from unicode.org.
"""
import os
import sys
import urllib.request

VERSION = "17.0.0"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "uprops.rs")

# General categories, and the groups JavaScript names by their long and short names.
GROUPS = {
    "L": ["Lu", "Ll", "Lt", "Lm", "Lo"],
    "LC": ["Lu", "Ll", "Lt"],
    "M": ["Mn", "Mc", "Me"],
    "N": ["Nd", "Nl", "No"],
    "P": ["Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po"],
    "S": ["Sm", "Sc", "Sk", "So"],
    "Z": ["Zs", "Zl", "Zp"],
    "C": ["Cc", "Cf", "Cs", "Co", "Cn"],
}
LONG = {
    "Letter": "L", "Cased_Letter": "LC", "Uppercase_Letter": "Lu", "Lowercase_Letter": "Ll",
    "Titlecase_Letter": "Lt", "Modifier_Letter": "Lm", "Other_Letter": "Lo",
    "Mark": "M", "Combining_Mark": "M", "Nonspacing_Mark": "Mn", "Spacing_Mark": "Mc",
    "Enclosing_Mark": "Me", "Number": "N", "Decimal_Number": "Nd", "Letter_Number": "Nl",
    "Other_Number": "No", "Punctuation": "P", "punct": "P", "Connector_Punctuation": "Pc",
    "Dash_Punctuation": "Pd", "Open_Punctuation": "Ps", "Close_Punctuation": "Pe",
    "Initial_Punctuation": "Pi", "Final_Punctuation": "Pf", "Other_Punctuation": "Po",
    "Symbol": "S", "Math_Symbol": "Sm", "Currency_Symbol": "Sc", "Modifier_Symbol": "Sk",
    "Other_Symbol": "So", "Separator": "Z", "Space_Separator": "Zs", "Line_Separator": "Zl",
    "Paragraph_Separator": "Zp", "Format": "Cf", "Private_Use": "Co", "Surrogate": "Cs",
}
EMOJI = ["Emoji", "Emoji_Presentation", "Emoji_Modifier", "Emoji_Modifier_Base",
         "Emoji_Component", "Extended_Pictographic"]


def fetch(name, url):
    path = os.path.join(HERE, name)
    if not os.path.exists(path):
        urllib.request.urlretrieve(url, path)
    return path


def categories(path):
    cat = {}
    first = None
    for line in open(path, encoding="utf-8"):
        f = line.split(";")
        cp, name, gc = int(f[0], 16), f[1], f[2]
        if name.endswith(", First>"):
            first = cp
            continue
        if name.endswith(", Last>"):
            for c in range(first, cp + 1):
                cat[c] = gc
            continue
        cat[cp] = gc
    return cat


def ranges(cps):
    out = []
    for c in sorted(cps):
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def main():
    if len(sys.argv) == 3:
        ucd, emoji = sys.argv[1], sys.argv[2]
    else:
        base = f"https://www.unicode.org/Public/{VERSION}/ucd"
        ucd = fetch("UnicodeData.txt", f"{base}/UnicodeData.txt")
        emoji = fetch("emoji-data.txt", f"{base}/emoji/emoji-data.txt")
    cat = categories(ucd)
    sets = {}
    for gc in sorted(set(cat.values())):
        sets[gc] = {c for c, g in cat.items() if g == gc}
    # Unassigned code points (Cn) are everything else below 0x110000.
    sets["Cn"] = set(range(0x110000)) - set(cat)
    for group, members in GROUPS.items():
        sets[group] = set().union(*(sets.get(m, set()) for m in members))
    for prop in EMOJI:
        sets[prop] = set()
    for line in open(emoji, encoding="utf-8"):
        line = line.split("#")[0].strip()
        if not line:
            continue
        cps, prop = [x.strip() for x in line.split(";")]
        lo, _, hi = cps.partition("..")
        sets[prop].update(range(int(lo, 16), int(hi or lo, 16) + 1))
    # The engine's own tables already answer these (from Rust's char classes), and
    # C and Cn would be most of the file.
    skip = {"Cs", "C", "Cn", "Cc", "L", "Lu", "Ll", "N", "Nd"}
    names = sorted(k for k in sets if k not in skip)
    with open(OUT, "w") as f:
        f.write(f"""//! Code point ranges for Unicode property escapes the regex engine has no
//! tables for (General_Category values and groups, and the emoji properties),
//! from the Unicode Character Database {VERSION}, the version Node v24 ships.
//! Generated by tools/generate_uprops.py; do not edit.

/// The ranges of `name` (`P`, `Punctuation`, `Emoji`, ...), inclusive.
pub fn ranges(name: &str) -> Option<&'static [(u32, u32)]> {{
    let short = match name {{
""")
        for long, short in sorted(LONG.items()):
            if short in skip:
                continue
            f.write(f"        {long!r:s} => {short!r:s},\n".replace("'", '"'))
        f.write("        other => other,\n    };\n    Some(match short {\n")
        for n in names:
            f.write(f"        \"{n}\" => {n.upper()},\n")
        f.write("        _ => return None,\n    })\n}\n")
        for n in names:
            rs = ranges(sets[n] - set(range(0xD800, 0xE000)))
            body = ", ".join(f"(0x{a:X}, 0x{b:X})" for a, b in rs)
            f.write(f"\nstatic {n.upper()}: &[(u32, u32)] = &[{body}];\n")
    # House style is rustfmt's.
    import subprocess
    subprocess.run(["rustfmt", "--edition", "2021", OUT], check=True)
    print(f"wrote {OUT}: {len(names)} properties")


if __name__ == "__main__":
    main()
