// Generated by assets/generate-symbols.py; do not edit.
pub const SYMBOLS: &[(&str, &[u8])] = &[
    (
        "symbol/accessibility",
        include_bytes!("../assets/symbols/accessibility.png"),
    ),
    (
        "symbol/airplane",
        include_bytes!("../assets/symbols/airplane.png"),
    ),
    ("symbol/apps", include_bytes!("../assets/symbols/apps.png")),
    (
        "symbol/archive",
        include_bytes!("../assets/symbols/archive.png"),
    ),
    (
        "symbol/arrow-left",
        include_bytes!("../assets/symbols/arrow-left.png"),
    ),
    (
        "symbol/arrow-right",
        include_bytes!("../assets/symbols/arrow-right.png"),
    ),
    (
        "symbol/arrow-up",
        include_bytes!("../assets/symbols/arrow-up.png"),
    ),
    (
        "symbol/backspace",
        include_bytes!("../assets/symbols/backspace.png"),
    ),
    (
        "symbol/battery",
        include_bytes!("../assets/symbols/battery.png"),
    ),
    (
        "symbol/battery-vertical",
        include_bytes!("../assets/symbols/battery-vertical.png"),
    ),
    ("symbol/bell", include_bytes!("../assets/symbols/bell.png")),
    (
        "symbol/bluetooth",
        include_bytes!("../assets/symbols/bluetooth.png"),
    ),
    ("symbol/book", include_bytes!("../assets/symbols/book.png")),
    (
        "symbol/calendar",
        include_bytes!("../assets/symbols/calendar.png"),
    ),
    (
        "symbol/camera",
        include_bytes!("../assets/symbols/camera.png"),
    ),
    ("symbol/cast", include_bytes!("../assets/symbols/cast.png")),
    (
        "symbol/cellular",
        include_bytes!("../assets/symbols/cellular.png"),
    ),
    ("symbol/chat", include_bytes!("../assets/symbols/chat.png")),
    (
        "symbol/check",
        include_bytes!("../assets/symbols/check.png"),
    ),
    (
        "symbol/chevron-down",
        include_bytes!("../assets/symbols/chevron-down.png"),
    ),
    (
        "symbol/chevron-left",
        include_bytes!("../assets/symbols/chevron-left.png"),
    ),
    (
        "symbol/chevron-right",
        include_bytes!("../assets/symbols/chevron-right.png"),
    ),
    (
        "symbol/chevron-up",
        include_bytes!("../assets/symbols/chevron-up.png"),
    ),
    (
        "symbol/clock",
        include_bytes!("../assets/symbols/clock.png"),
    ),
    (
        "symbol/close",
        include_bytes!("../assets/symbols/close.png"),
    ),
    (
        "symbol/cloud",
        include_bytes!("../assets/symbols/cloud.png"),
    ),
    (
        "symbol/compose",
        include_bytes!("../assets/symbols/compose.png"),
    ),
    (
        "symbol/control-center",
        include_bytes!("../assets/symbols/control-center.png"),
    ),
    ("symbol/copy", include_bytes!("../assets/symbols/copy.png")),
    (
        "symbol/desktop",
        include_bytes!("../assets/symbols/desktop.png"),
    ),
    (
        "symbol/display",
        include_bytes!("../assets/symbols/display.png"),
    ),
    ("symbol/dnd", include_bytes!("../assets/symbols/dnd.png")),
    (
        "symbol/document",
        include_bytes!("../assets/symbols/document.png"),
    ),
    (
        "symbol/download",
        include_bytes!("../assets/symbols/download.png"),
    ),
    (
        "symbol/drive",
        include_bytes!("../assets/symbols/drive.png"),
    ),
    ("symbol/edit", include_bytes!("../assets/symbols/edit.png")),
    (
        "symbol/eject",
        include_bytes!("../assets/symbols/eject.png"),
    ),
    ("symbol/flag", include_bytes!("../assets/symbols/flag.png")),
    (
        "symbol/flashlight",
        include_bytes!("../assets/symbols/flashlight.png"),
    ),
    (
        "symbol/folder",
        include_bytes!("../assets/symbols/folder.png"),
    ),
    (
        "symbol/fruit",
        include_bytes!("../assets/symbols/fruit.png"),
    ),
    ("symbol/gear", include_bytes!("../assets/symbols/gear.png")),
    (
        "symbol/globe",
        include_bytes!("../assets/symbols/globe.png"),
    ),
    ("symbol/grid", include_bytes!("../assets/symbols/grid.png")),
    (
        "symbol/grid-view",
        include_bytes!("../assets/symbols/grid-view.png"),
    ),
    (
        "symbol/headphones",
        include_bytes!("../assets/symbols/headphones.png"),
    ),
    ("symbol/home", include_bytes!("../assets/symbols/home.png")),
    (
        "symbol/hotspot",
        include_bytes!("../assets/symbols/hotspot.png"),
    ),
    (
        "symbol/image",
        include_bytes!("../assets/symbols/image.png"),
    ),
    (
        "symbol/inbox",
        include_bytes!("../assets/symbols/inbox.png"),
    ),
    ("symbol/info", include_bytes!("../assets/symbols/info.png")),
    (
        "symbol/keyboard",
        include_bytes!("../assets/symbols/keyboard.png"),
    ),
    ("symbol/leaf", include_bytes!("../assets/symbols/leaf.png")),
    ("symbol/link", include_bytes!("../assets/symbols/link.png")),
    (
        "symbol/list-view",
        include_bytes!("../assets/symbols/list-view.png"),
    ),
    (
        "symbol/location",
        include_bytes!("../assets/symbols/location.png"),
    ),
    ("symbol/lock", include_bytes!("../assets/symbols/lock.png")),
    ("symbol/menu", include_bytes!("../assets/symbols/menu.png")),
    ("symbol/mic", include_bytes!("../assets/symbols/mic.png")),
    ("symbol/moon", include_bytes!("../assets/symbols/moon.png")),
    ("symbol/more", include_bytes!("../assets/symbols/more.png")),
    (
        "symbol/more-vertical",
        include_bytes!("../assets/symbols/more-vertical.png"),
    ),
    (
        "symbol/music",
        include_bytes!("../assets/symbols/music.png"),
    ),
    (
        "symbol/new-tab",
        include_bytes!("../assets/symbols/new-tab.png"),
    ),
    (
        "symbol/night-light",
        include_bytes!("../assets/symbols/night-light.png"),
    ),
    (
        "symbol/paperclip",
        include_bytes!("../assets/symbols/paperclip.png"),
    ),
    (
        "symbol/paste",
        include_bytes!("../assets/symbols/paste.png"),
    ),
    (
        "symbol/person",
        include_bytes!("../assets/symbols/person.png"),
    ),
    ("symbol/pin", include_bytes!("../assets/symbols/pin.png")),
    ("symbol/plus", include_bytes!("../assets/symbols/plus.png")),
    (
        "symbol/power",
        include_bytes!("../assets/symbols/power.png"),
    ),
    (
        "symbol/reload",
        include_bytes!("../assets/symbols/reload.png"),
    ),
    (
        "symbol/rename",
        include_bytes!("../assets/symbols/rename.png"),
    ),
    (
        "symbol/reply",
        include_bytes!("../assets/symbols/reply.png"),
    ),
    (
        "symbol/rotate-lock",
        include_bytes!("../assets/symbols/rotate-lock.png"),
    ),
    (
        "symbol/scissors",
        include_bytes!("../assets/symbols/scissors.png"),
    ),
    (
        "symbol/screenshot",
        include_bytes!("../assets/symbols/screenshot.png"),
    ),
    (
        "symbol/search",
        include_bytes!("../assets/symbols/search.png"),
    ),
    ("symbol/send", include_bytes!("../assets/symbols/send.png")),
    (
        "symbol/share",
        include_bytes!("../assets/symbols/share.png"),
    ),
    (
        "symbol/shield",
        include_bytes!("../assets/symbols/shield.png"),
    ),
    (
        "symbol/sidebar",
        include_bytes!("../assets/symbols/sidebar.png"),
    ),
    (
        "symbol/signal",
        include_bytes!("../assets/symbols/signal.png"),
    ),
    ("symbol/sort", include_bytes!("../assets/symbols/sort.png")),
    (
        "symbol/split",
        include_bytes!("../assets/symbols/split.png"),
    ),
    ("symbol/star", include_bytes!("../assets/symbols/star.png")),
    (
        "symbol/star-outline",
        include_bytes!("../assets/symbols/star-outline.png"),
    ),
    ("symbol/sun", include_bytes!("../assets/symbols/sun.png")),
    ("symbol/tabs", include_bytes!("../assets/symbols/tabs.png")),
    ("symbol/tag", include_bytes!("../assets/symbols/tag.png")),
    (
        "symbol/terminal",
        include_bytes!("../assets/symbols/terminal.png"),
    ),
    (
        "symbol/trash",
        include_bytes!("../assets/symbols/trash.png"),
    ),
    (
        "symbol/volume",
        include_bytes!("../assets/symbols/volume.png"),
    ),
    (
        "symbol/volume-mute",
        include_bytes!("../assets/symbols/volume-mute.png"),
    ),
    (
        "symbol/wallet",
        include_bytes!("../assets/symbols/wallet.png"),
    ),
    ("symbol/wifi", include_bytes!("../assets/symbols/wifi.png")),
    (
        "symbol/wifi-fill",
        include_bytes!("../assets/symbols/wifi-fill.png"),
    ),
    (
        "symbol/windows",
        include_bytes!("../assets/symbols/windows.png"),
    ),
];
