use crate::check;

check!(node_types, "<div id=d><!--c-->t</div>", "const d=document.getElementById('d'); console.log(d.nodeType, d.firstChild.nodeType, d.lastChild.nodeType, document.nodeType, document.doctype.nodeType, document.createDocumentFragment().nodeType);", "1 8 3 9 10 11");
check!(node_names, "<div id=d>t</div>", "const d=document.getElementById('d'); console.log(d.nodeName, d.tagName, d.localName, d.firstChild.nodeName, document.nodeName, document.doctype.name, document.createComment('x').nodeName);", "DIV DIV div #text #document html #comment");
check!(node_values, "<div id=d>t</div>", "const d=document.getElementById('d'); console.log(d.nodeValue, d.firstChild.nodeValue, d.textContent, document.textContent); d.firstChild.nodeValue='u'; console.log(d.textContent);", "null t t null\nu");
check!(parent_links, "<div id=a><p id=b>x</p><p id=c>y</p></div>", "const b=document.getElementById('b'), c=document.getElementById('c'); console.log(b.parentNode.id, b.parentElement.id, b.nextSibling.id, c.previousSibling.id, b.previousSibling, c.nextSibling, document.documentElement.parentNode===document, document.parentNode);", "a a c b null null true null");
check!(child_links, "<div id=a> <p>x</p><p>y</p> </div>", "const a=document.getElementById('a'); console.log(a.firstChild.nodeType, a.lastChild.nodeType, a.firstElementChild.textContent, a.lastElementChild.textContent, a.childNodes.length, a.children.length, a.childElementCount, a.hasChildNodes(), document.createElement('i').hasChildNodes());", "3 3 x y 4 2 2 true false");
check!(element_siblings, "<ul id=u><li>1</li> <li>2</li><li>3</li></ul>", "const u=document.getElementById('u'); const l=u.children; console.log(l[0].nextElementSibling.textContent, l[2].previousElementSibling.textContent, l[0].previousElementSibling, l[2].nextElementSibling);", "2 2 null null");
check!(append_and_insert, "<div id=a></div>", "const a=document.getElementById('a'); const p=document.createElement('p'); const q=document.createElement('q'); a.appendChild(p); a.insertBefore(q,p); a.appendChild(document.createTextNode('t')); console.log(a.innerHTML, a.childNodes.length);", "<q></q><p></p>t 3");
check!(remove_and_replace, "<div id=a><b>1</b><i>2</i></div>", "const a=document.getElementById('a'); const b=a.querySelector('b'); const s=document.createElement('s'); a.replaceChild(s, b); console.log(a.innerHTML, b.parentNode); a.removeChild(a.lastChild); a.querySelector('s').remove(); console.log(a.innerHTML);", "<s></s><i>2</i> null\n");
check!(append_moves_node, "<div id=a><b>1</b></div><div id=c></div>", "const b=document.querySelector('b'); document.getElementById('c').appendChild(b); console.log(document.getElementById('a').innerHTML, document.getElementById('c').innerHTML);", " <b>1</b>");
check!(fragment_insert, "<div id=a></div>", "const f=document.createDocumentFragment(); f.appendChild(document.createElement('x')); f.appendChild(document.createElement('y')); const a=document.getElementById('a'); a.appendChild(f); console.log(a.innerHTML, f.childNodes.length, f.hasChildNodes());", "<x></x><y></y> 0 false");
check!(hierarchy_errors, "<div id=a><p id=b></p></div>", "const a=document.getElementById('a'), b=document.getElementById('b'); try { b.appendChild(a); } catch(e) { console.log(e.name); } try { a.removeChild(document.body); } catch(e) { console.log(e.name, e instanceof DOMException); } try { a.insertBefore(document.createElement('i'), document.body); } catch(e) { console.log(e.name); }", "HierarchyRequestError\nNotFoundError true\nNotFoundError");
check!(text_content_set, "<div id=a><b>1</b></div>", "const a=document.getElementById('a'); a.textContent='<x>'; console.log(a.innerHTML, a.childNodes.length); a.textContent=''; console.log(a.childNodes.length);", "&lt;x&gt; 1\n0");
check!(clone_node, "<div id=a class=c><b>1</b></div>", "const a=document.getElementById('a'); const s=a.cloneNode(false), d=a.cloneNode(true); console.log(s.outerHTML, d.outerHTML, d!==a, d.firstChild!==a.firstChild, s.parentNode);", "<div id=\"a\" class=\"c\"></div> <div id=\"a\" class=\"c\"><b>1</b></div> true true null");
check!(contains_and_connected, "<div id=a><b id=b></b></div>", "const a=document.getElementById('a'), b=document.getElementById('b'); console.log(a.contains(b), b.contains(a), a.contains(a), a.isConnected, document.createElement('i').isConnected, document.contains(a)); b.remove(); console.log(b.isConnected, a.contains(b));", "true false true true false true\nfalse false");
check!(compare_document_position, "<div id=a><b id=b></b><i id=c></i></div>", "const a=document.getElementById('a'), b=document.getElementById('b'), c=document.getElementById('c'); console.log(a.compareDocumentPosition(b), b.compareDocumentPosition(a), b.compareDocumentPosition(c), c.compareDocumentPosition(b), a.compareDocumentPosition(a), Node.DOCUMENT_POSITION_FOLLOWING);", "20 10 4 2 0 4");
check!(is_equal_node, "<div id=a><b>x</b></div><div id=c><b>x</b></div><div id=d><b>y</b></div>", "const [a,c,d]=['a','c','d'].map(i=>document.getElementById(i)); console.log(a.isEqualNode(c), a.isEqualNode(d), a.isSameNode(a), a.isSameNode(c), a.firstChild.isEqualNode(c.firstChild));", "false false true false true");
check!(normalize_merges_text, "<div id=a></div>", "const a=document.getElementById('a'); a.appendChild(document.createTextNode('x')); a.appendChild(document.createTextNode('')); a.appendChild(document.createTextNode('y')); a.normalize(); console.log(a.childNodes.length, a.firstChild.data);", "1 xy");
check!(get_root_node, "<div id=a></div>", "const a=document.getElementById('a'); console.log(a.getRootNode()===document, document.createElement('i').getRootNode().nodeType, a.baseURI);", "true 1 https://example.test/page.html");
check!(owner_document, "<div id=a></div>", "console.log(document.getElementById('a').ownerDocument===document, document.ownerDocument, document.createElement('i').ownerDocument===document);", "true null true");

check!(attributes_basic, "<div id=a data-x=1 title=t></div>", "const a=document.getElementById('a'); console.log(a.getAttribute('data-x'), a.getAttribute('DATA-X'), a.getAttribute('nope'), a.hasAttribute('title'), a.hasAttributes(), a.getAttributeNames().join());", "1 1 null true true id,data-x,title");
check!(set_remove_toggle_attribute, "<div id=a></div>", "const a=document.getElementById('a'); a.setAttribute('X','1'); a.setAttribute('x', 2); console.log(a.outerHTML); a.removeAttribute('x'); console.log(a.toggleAttribute('hidden'), a.toggleAttribute('hidden'), a.toggleAttribute('z', true), a.outerHTML);", "<div id=\"a\" x=\"2\"></div>\ntrue false true <div id=\"a\" z=\"\"></div>");
check!(invalid_attribute_name, "", "try { document.body.setAttribute('a b', 1); } catch(e) { console.log(e.name); } try { document.createElement('a b'); } catch(e) { console.log(e.name); }", "InvalidCharacterError\nInvalidCharacterError");
check!(id_and_class_name, "<div id=a class='x y'></div>", "const a=document.getElementById('a'); console.log(a.id, a.className); a.id='b'; a.className='z'; console.log(document.getElementById('b')===a, document.getElementById('a'), a.getAttribute('class'));", "a x y\ntrue null z");
check!(attributes_map, "<div id=a b=2></div>", "const a=document.getElementById('a'); const m=a.attributes; console.log(m.length, m[0].name, m[1].value, m.getNamedItem('b').value, m.item(5), m.b.name, a.getAttributeNode('b').ownerElement===a); m[1].value='3'; console.log(a.getAttribute('b'), [...m].map(x=>x.name).join()); m.removeNamedItem('b'); console.log(a.hasAttribute('b'), m.length);", "2 id 2 2 null b true\n3 id,b\nfalse 1");
check!(attr_node_create, "<div id=a></div>", "const at=document.createAttribute('data-q'); at.value='v'; const a=document.getElementById('a'); a.setAttributeNode(at); console.log(a.getAttribute('data-q'), at.ownerElement===a, at.nodeType, at instanceof Node);", "v true 2 true");
check!(class_list, "<div id=a class='x y x'></div>", "const c=document.getElementById('a').classList; console.log(c.length, c[0], c.item(1), c.contains('x'), c.contains('z')); c.add('z','w'); c.remove('y'); console.log(c.value, c.toggle('x'), c.toggle('x'), c.toggle('q', false), c.replace('z','r'), String(c), [...c].join('|')); try { c.add(''); } catch(e) { console.log(e.name); } try { c.add('a b'); } catch(e) { console.log(e.name); }", "2 x y true false\nx z w false true false true r w x r|w|x\nSyntaxError\nInvalidCharacterError");
check!(class_list_foreach, "<div id=a class='p q'></div>", "const out=[]; document.getElementById('a').classList.forEach((t,i)=>out.push(i+t)); console.log(out.join());", "0p,1q");
check!(dataset_map, "<div id=a data-foo-bar=1 data-x=2></div>", "const d=document.getElementById('a').dataset; console.log(d.fooBar, d.x, d.nope, Object.keys(d).join(), 'x' in d); d.newKey='v'; delete d.x; console.log(document.getElementById('a').outerHTML);", "1 2 undefined fooBar,x true\n<div id=\"a\" data-foo-bar=\"1\" data-new-key=\"v\"></div>");
check!(namespaces, "<svg id=s><circle id=c/></svg><div id=d></div>", "const s=document.getElementById('s'); console.log(s.namespaceURI, s.tagName, document.getElementById('d').namespaceURI, document.createElementNS('http://www.w3.org/2000/svg','path').namespaceURI, s.querySelector('circle').localName);", "http://www.w3.org/2000/svg svg http://www.w3.org/1999/xhtml http://www.w3.org/2000/svg circle");

check!(inner_html_get_set, "<div id=a><b>1</b></div>", "const a=document.getElementById('a'); console.log(a.innerHTML); a.innerHTML='<p>x<p>y'; console.log(a.innerHTML, a.children.length); a.innerHTML=''; console.log(a.childNodes.length);", "<b>1</b>\n<p>x</p><p>y</p> 2\n0");
check!(inner_html_table_context, "<table id=t></table>", "const t=document.getElementById('t'); t.innerHTML='<tr><td>1</td></tr>'; console.log(t.innerHTML, t.rows.length);", "<tbody><tr><td>1</td></tr></tbody> 1");
check!(outer_html, "<div id=a><b id=b>1</b></div>", "const b=document.getElementById('b'); console.log(b.outerHTML); b.outerHTML='<i>2</i><u>3</u>'; console.log(document.getElementById('a').innerHTML, b.parentNode);", "<b id=\"b\">1</b>\n<i>2</i><u>3</u> null");
check!(insert_adjacent, "<div id=a><b>1</b></div>", "const b=document.querySelector('b'); b.insertAdjacentHTML('beforebegin','<i>0</i>'); b.insertAdjacentHTML('afterbegin','<u>a</u>'); b.insertAdjacentHTML('beforeend','<u>z</u>'); b.insertAdjacentHTML('afterend','<i>2</i>'); b.insertAdjacentText('afterend','T'); b.insertAdjacentElement('beforebegin', document.createElement('s')); console.log(document.getElementById('a').innerHTML); try { b.insertAdjacentHTML('x','') } catch(e) { console.log(e.name) }", "<i>0</i><s></s><b><u>a</u>1<u>z</u></b>T<i>2</i>\nSyntaxError");
check!(inner_text_blocks, "<div id=a>Hello <b>bold</b><p>para</p><span style='display:none'>hidden</span>line<br>next   spaces</div>", "console.log(JSON.stringify(document.getElementById('a').innerText));", "\"Hello bold\\n\\npara\\n\\nline\\nnext spaces\"");
check!(
    inner_text_set,
    "<div id=a></div>",
    "const a=document.getElementById('a'); a.innerText='a\\nb'; console.log(a.innerHTML);",
    "a<br>b"
);
check!(text_node_ops, "<div id=a>hello world</div>", "const t=document.getElementById('a').firstChild; console.log(t.length, t.substringData(0,5), t.wholeText); t.appendData('!'); t.insertData(0,'>'); t.deleteData(1,6); t.replaceData(0,1,'<'); console.log(t.data); const s=t.splitText(3); console.log(t.data, s.data, s.previousSibling===t, t.wholeText); try { t.substringData(99,1) } catch(e) { console.log(e.name) }", "11 hello hello world\n<world!\n<wo rld! true <world!\nIndexSizeError");
check!(text_and_comment_ctors, "<div id=a></div>", "const t=new Text('x'), c=new Comment('y'); document.getElementById('a').append(t,c); console.log(document.getElementById('a').innerHTML, t instanceof Text, t instanceof CharacterData, t instanceof Node, c instanceof Comment, Object.prototype.toString.call(t), t.constructor.name);", "x<!--y--> true true true true [object Text] Text");
check!(append_prepend_before_after, "<div id=a><b>1</b></div>", "const a=document.getElementById('a'), b=a.firstChild; a.append('x', document.createElement('i')); a.prepend('p'); b.before('B'); b.after(document.createElement('u'), 'A'); b.replaceWith('R'); console.log(a.innerHTML); a.replaceChildren('only'); console.log(a.innerHTML);", "pBR<u></u>Ax<i></i>\nonly");

check!(query_selector_basic, "<div id=a><p class=x>1</p><p class='x y'>2</p><span data-k='v'>3</span></div>", "const a=document.getElementById('a'); console.log(a.querySelector('.x').textContent, a.querySelectorAll('.x').length, a.querySelectorAll('p.y')[0].textContent, document.querySelector('[data-k=v]').textContent, document.querySelector('#a > span').textContent, document.querySelector('nope'), a.querySelectorAll('p:nth-child(2)')[0].textContent);", "1 2 2 3 3 null 2");
check!(query_selector_all_static, "<ul id=u><li>1</li><li>2</li></ul>", "const l=document.querySelectorAll('li'); document.getElementById('u').appendChild(document.createElement('li')); console.log(l.length, document.querySelectorAll('li').length, l instanceof NodeList, Array.from(l).length, [...l].map(x=>x.textContent).join(), l.item(0).textContent, l.item(9)); let n=0; l.forEach((x,i,list)=>{ n+=i; if(list!==l) n=99;}); console.log(n, Object.prototype.toString.call(l));", "2 3 true 2 1,2 1 null\n1 [object NodeList]");
check!(query_selector_scope, "<div id=a><p id=p><b>x</b></p></div>", "const p=document.getElementById('p'); console.log(p.querySelector(':scope > b').textContent, p.querySelectorAll('#a b').length, document.querySelector('div p b').textContent);", "x 1 x");
check!(query_selector_invalid, "", "try { document.querySelector('[') } catch(e) { console.log(e.name, e instanceof DOMException) }", "SyntaxError true");
check!(matches_closest, "<div id=a class=c><p id=p><b id=b></b></p></div>", "const b=document.getElementById('b'); console.log(b.matches('b'), b.matches('#a b'), b.matches('p'), b.closest('p').id, b.closest('.c').id, b.closest('b').id, b.closest('nope'), b.webkitMatchesSelector('b'));", "true true false p a b null true");
check!(get_element_by_id, "<div id=a></div><div id=a class=second></div>", "console.log(document.getElementById('a').className, document.getElementById('zz')); const f=document.createDocumentFragment(); const e=document.createElement('div'); e.id='q'; f.appendChild(e); console.log(f.getElementById('q')===e, document.getElementById('q'));", " null\ntrue null");
check!(get_elements_by_live, "<div id=a><p>1</p></div>", "const a=document.getElementById('a'); const ps=a.getElementsByTagName('p'), all=document.getElementsByTagName('*'); const n=all.length; a.appendChild(document.createElement('p')); console.log(ps.length, all.length-n, ps[1].tagName, ps.item(0).textContent, ps.namedItem('x'), ps instanceof HTMLCollection);", "2 1 P 1 null true");
check!(get_elements_by_class_name, "<div class='a b'></div><div class=a></div><div class=b id=z></div>", "console.log(document.getElementsByClassName('a').length, document.getElementsByClassName('a b').length, document.getElementsByClassName('b')[1].id, document.getElementsByClassName('').length);", "2 1 z 0");
check!(get_elements_by_name, "<input name=n><input name=n><meta name=n>", "console.log(document.getElementsByName('n').length, document.getElementsByName('n') instanceof NodeList);", "3 true");
check!(collection_named_access, "<form id=f><input name=q id=w></form><div id=c><p id=x></p><p name=y></p></div>", "const c=document.getElementById('c').children; console.log(c.x.id, c.y.getAttribute('name'), c.namedItem('x').id, c.zz, c.length, Object.keys(c).join());", "x y x undefined 2 0,1");
check!(children_live, "<div id=a><p></p></div>", "const a=document.getElementById('a'); const c=a.children, n=a.childNodes; a.appendChild(document.createTextNode('t')); a.appendChild(document.createElement('b')); console.log(c.length, n.length, c[1].tagName, n[1].nodeType, [...c].length, Array.prototype.map.call(n, x=>x.nodeType).join());", "2 3 B 3 2 1,3,1");
check!(document_collections, "<form></form><img><a href=x></a><a name=n></a><script></script>", "console.log(document.forms.length, document.images.length, document.links.length, document.anchors.length, document.scripts.length-1, document.all.length>5, document.body instanceof HTMLBodyElement, document.head.tagName, document.documentElement.tagName);", "1 1 1 1 1 true true HEAD HTML");

check!(tree_walker, "<div id=a><b>1</b><!--c--><i>2<u>3</u></i></div>", "const w=document.createTreeWalker(document.getElementById('a'), NodeFilter.SHOW_ELEMENT); const out=[]; while(w.nextNode()) out.push(w.currentNode.tagName); w.currentNode=document.getElementById('a'); console.log(out.join(), w.firstChild().tagName, w.nextSibling().tagName, w.previousSibling().tagName, w.parentNode().id); const w2=document.createTreeWalker(document.getElementById('a'), NodeFilter.SHOW_ALL, n=>n.nodeType===8?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT); const o2=[]; while(w2.nextNode()) o2.push(w2.currentNode.nodeName); console.log(o2.join());", "B,I,U B I B a\nB,#text,I,#text,U,#text");
check!(node_iterator, "<div id=a><b>1</b><i>2</i></div>", "const it=document.createNodeIterator(document.getElementById('a'), NodeFilter.SHOW_TEXT); const out=[]; let n; while((n=it.nextNode())) out.push(n.data); console.log(out.join(), it.previousNode().data);", "1,2 2");
check!(range_basics, "<p id=p>hello world</p>", "const t=document.getElementById('p').firstChild; const r=document.createRange(); r.setStart(t,0); r.setEnd(t,5); console.log(r.toString(), r.collapsed, r.startOffset, r.endOffset, r.commonAncestorContainer===t); r.deleteContents(); console.log(t.data, r.collapsed); const r2=new Range(); r2.selectNodeContents(document.getElementById('p')); console.log(r2.toString(), r2.startContainer.id, r2.endOffset); r2.selectNode(document.getElementById('p')); console.log(r2.startContainer===document.body, r2.cloneContents().firstChild.tagName, typeof r2.getBoundingClientRect().width);", "hello false 0 5 true\n world true\n world p 1\ntrue P number");
check!(range_across_nodes, "<div id=d><b>ab</b><i>cd</i></div>", "const d=document.getElementById('d'); const r=document.createRange(); r.setStart(d.firstChild.firstChild,1); r.setEnd(d.lastChild.firstChild,1); console.log(r.toString(), r.commonAncestorContainer.id); const f=r.extractContents(); console.log(d.innerHTML, f.childNodes.length);", "bc d\n<b>a</b><i>d</i> 2");
check!(selection_minimal, "<p id=p>x</p>", "const s=window.getSelection(); console.log(s.rangeCount, s.type, s.toString()); const r=document.createRange(); r.selectNodeContents(document.getElementById('p')); s.addRange(r); console.log(s.rangeCount, s.toString(), s.anchorNode.id, s.isCollapsed, document.getSelection()===s); s.removeAllRanges(); console.log(s.rangeCount);", "0 None \n1 x p false true\n0");

check!(dom_parser, "", "const d=new DOMParser().parseFromString('<p id=q>hi<b>x</b></p>','text/html'); console.log(d.body.innerHTML, d.getElementById('q').textContent, d.querySelector('b').tagName, d.documentElement.tagName, d.title, d.nodeType); d.title='T'; console.log(d.title, d.head.innerHTML);", "<p id=\"q\">hi<b>x</b></p> hix B HTML  9\nT <title>T</title>");
check!(create_html_document, "", "const d=document.implementation.createHTMLDocument('t'); console.log(d.title, d.body.tagName, d.body.childNodes.length); const p=d.createElement('p'); p.textContent='x'; d.body.appendChild(p); console.log(d.body.innerHTML); document.body.appendChild(document.adoptNode(p)); console.log(document.body.lastElementChild.textContent);", "t BODY 0\n<p>x</p>\nx");
check!(import_node, "<div id=a><b>1</b></div>", "const c=document.importNode(document.getElementById('a'), true); console.log(c.outerHTML, c.parentNode);", "<div id=\"a\"><b>1</b></div> null");
check!(template_content, "<template id=t><p>x</p></template>", "const t=document.getElementById('t'); console.log(t.content.nodeType, t.content.childNodes.length, t.childNodes.length, t.innerHTML); const c=t.content.cloneNode(true); document.body.appendChild(c); console.log(document.body.querySelector('p').textContent, t.content.firstChild.parentNode===t.content, t.content.parentNode);", "11 1 0 <p>x</p>\nx true null");
check!(shadow_root_approximation, "<div id=h></div>", "const h=document.getElementById('h'); const r=h.attachShadow({mode:'open'}); r.innerHTML='<b>s</b>'; console.log(h.shadowRoot===r, r.host===h, r.mode, r instanceof ShadowRoot, r instanceof DocumentFragment, r.querySelector('b').textContent, h.innerHTML, r.getRootNode()===r, h.firstChild.getRootNode()===document); try { h.attachShadow({mode:'open'}) } catch(e) { console.log(e.name) }", "true true open true true s <b>s</b> true true\nNotSupportedError");
check!(instanceof_hierarchy, "<div id=d></div><svg id=s></svg><input id=i>", "const d=document.getElementById('d'); console.log(d instanceof HTMLDivElement, d instanceof HTMLElement, d instanceof Element, d instanceof Node, d instanceof EventTarget, d.constructor.name, document.getElementById('s') instanceof SVGElement, document.getElementById('s') instanceof HTMLElement, document.getElementById('i').constructor.name, document instanceof Document, document instanceof HTMLDocument, document.constructor.name, Object.prototype.toString.call(d), Object.prototype.toString.call(document));", "true true true true true HTMLDivElement true false HTMLInputElement true true HTMLDocument [object HTMLDivElement] [object HTMLDocument]");
check!(unknown_and_custom_tags, "<foo id=f></foo><my-el id=m></my-el>", "console.log(document.getElementById('f').constructor.name, document.getElementById('m').constructor.name, document.createElement('blink').constructor.name);", "HTMLUnknownElement HTMLElement HTMLUnknownElement");
check!(node_constants_and_illegal_ctor, "", "console.log(Node.ELEMENT_NODE, document.body.TEXT_NODE); try { new Node() } catch(e) { console.log(e.constructor.name) } try { new HTMLDivElement() } catch(e) { console.log(e.name) }", "1 3\nTypeError\nTypeError");
check!(document_props, "", "console.log(document.URL, document.documentURI, document.location.href, document.readyState, document.compatMode, document.characterSet, document.charset, document.contentType, document.referrer, document.hidden, document.visibilityState, document.defaultView===window, document.title, document.doctype.name, document.scrollingElement===document.documentElement, document.hasFocus(), document.execCommand('bold'), document.currentScript.tagName);", "https://example.test/page.html https://example.test/page.html https://example.test/page.html loading CSS1Compat UTF-8 UTF-8 text/html  false visible true t html true true false SCRIPT");
check!(document_title_set, "", "document.title='New'; console.log(document.title, document.head.querySelector('title').textContent); document.querySelector('title').remove(); console.log(document.title); document.title='Z'; console.log(document.title);", "New New\n\nZ");
check!(
    quirks_mode,
    "",
    "console.log(document.compatMode);",
    "CSS1Compat"
);
check!(base_uri, "", "const b=document.createElement('base'); b.href='https://other.test/dir/'; document.head.appendChild(b); console.log(document.baseURI, document.body.baseURI); const a=document.createElement('a'); a.setAttribute('href','x'); console.log(a.href);", "https://other.test/dir/ https://other.test/dir/\nhttps://other.test/dir/x");
check!(create_event_legacy, "", "const e=document.createEvent('MouseEvents'); e.initMouseEvent('click', true, true, window, 1, 0,0,0,0,false,false,false,false,0,null); console.log(e.type, e.bubbles, e instanceof MouseEvent); const c=document.createEvent('CustomEvent'); c.initCustomEvent('x', false, false, 5); console.log(c.detail); try { document.createEvent('Nope') } catch(err) { console.log(err.name) }", "click true true\n5\nNotSupportedError");
check!(document_fragment_ctor, "", "const f=new DocumentFragment(); f.append('a', document.createElement('b')); console.log(f.childNodes.length, f.querySelector('b').tagName, f.children.length, f instanceof DocumentFragment);", "2 B 1 true");
check!(
    xml_serializer,
    "<div id=a><b>x</b></div>",
    "console.log(new XMLSerializer().serializeToString(document.getElementById('a')));",
    "<div id=\"a\"><b>x</b></div>"
);
check!(dom_rect, "", "const r=new DOMRect(1,2,3,4); console.log(r.x, r.right, r.bottom, JSON.stringify(r.toJSON()), r instanceof DOMRectReadOnly, DOMRect.fromRect({x:1,width:2}).width, new DOMPoint(1,2).y);", "1 4 6 {\"x\":1,\"y\":2,\"width\":3,\"height\":4,\"top\":2,\"right\":4,\"bottom\":6,\"left\":1} true 2 2");
check!(dom_exception, "", "const e=new DOMException('m','NotFoundError'); console.log(e.name, e.code, e.message, e instanceof Error, DOMException.name);", "NotFoundError 8 m true DOMException");
check!(element_children_of_document, "", "console.log(document.children.length, document.firstElementChild.tagName, document.childElementCount);", "1 HTML 1");
check!(document_write_after_load, "<p>old</p>", "window.addEventListener('load', () => { document.write('<h1>new</h1>'); document.write('<p>more</p>'); console.log(document.body.innerHTML); });", "<h1>new</h1><p>more</p>");
// A mutation made just before `createElement('template')` still restyles: creating
// the template drops only its content fragment's insertion from the mutation log.
check!(creating_a_template_keeps_earlier_mutations, "<style>.x { color: rgb(255, 0, 0) } .x span { width: 7px }</style><div id=d><span id=s style='display: inline-block'></span></div>", "const d=document.getElementById('d'), s=document.getElementById('s'); d.getBoundingClientRect(); d.className='x'; document.createElement('template'); console.log(getComputedStyle(d).color, s.getBoundingClientRect().width); s.textContent='t'; document.createElement('template'); console.log(s.firstChild.data, s.getBoundingClientRect().width > 0);", "rgb(255, 0, 0) 7\nt true");
