//! An independent determinism regression corpus: recorded goldens for long runs.
//!
//! A run of this engine is meant to be a pure function of (engine, world, seed,
//! action sequence, viewport). This file pins that claim down with data captured
//! from a known-good commit, so that any change to observable behaviour — a
//! different per-step hash, a renumbered event, a reordered event log, a snapshot
//! that exports different bytes, a `validate_snapshot` that stopped refusing
//! something — fails here with the step it happened at and both values.
//!
//! What is covered
//! ---------------
//! * Five scenarios over two worlds (`worlds/company-2026/world.json` and
//!   `worlds/agent-desktop/world.json`), five seeds and four machines — one of
//!   them a Windows box, so a second shell dialect is in the mix — 300 to 360
//!   steps each, 1 to 3 actions a step, over all seven built-in action families.
//! * `state_hash()` after **every** step, not only at the end, so a divergence is
//!   localised to the step that caused it.
//! * A digest of every `StepResult` — observation channels, per-action outcome,
//!   error code and refusal reason, tick and pending count.
//! * The complete event log: `sequence`, `tick`, `kind`, `machine`, `actor` in
//!   clear and a digest of `data`, plus a chained hash over the whole log so
//!   ordering and numbering cannot change unnoticed.
//! * A digest of `scene(1280, 800)` at every sampled step and of
//!   `scene(390, 844)` at the end, because `Environment::scene` is in the code
//!   being rewritten and the scene is observable output too.
//! * The action journal's head hash, which chains every recorded step.
//! * Snapshot / fork / restore: a mid-run snapshot, the exact byte length and
//!   SHA-256 of `export_snapshot()`, and two forks driven apart with different
//!   actions, each checked against its own golden.
//! * `Environment::replay` over the recorded journal, which must reproduce the
//!   same hashes (with step verification on, so the engine itself refuses a
//!   divergent replay).
//! * A snapshot exported at the baseline commit and committed as a fixture, which
//!   must still import and still hash the same.
//! * The negative half: `validate_snapshot` must still refuse a snapshot from a
//!   different world, an incompatible kernel version or engine string, mismatched
//!   application or interface module versions, a machine grant that is not in the
//!   world, a tampered journal, and a checkpoint with unresolved live host
//!   effects — each with the same error code *and* the same message.
//!
//! Diagnosing a divergence
//! -----------------------
//! If the step-result digests move but the state hashes do not, the difference is
//! inside `StepResult` rather than in world state. `dump_step_results` (ignored,
//! `CW_CORPUS_DUMP_DIR=<dir>`) writes every `StepResult` out in full; run it in a
//! worktree at the last good commit and in the tree under test and diff the two
//! directories, and the diff names the field.
//!
//! Regenerating the goldens
//! ------------------------
//! The goldens are not something you refresh to make a red test green. A change
//! here means the engine's observable output changed; that is either a bug or a
//! decision someone has to take deliberately. When it really is intended:
//!
//! ```text
//! CW_BLESS_DETERMINISM_CORPUS=yes-i-intend-to-change-observable-behaviour \
//!   cargo test -p computerworld --test determinism_corpus -- --ignored --exact \
//!   regenerate_determinism_goldens --nocapture
//! ```
//!
//! Both the `--ignored` filter and the exact pass-phrase are required; the test
//! refuses and prints why if either is missing. Commit the regenerated fixtures
//! in their own commit, with the reason for the behaviour change in the message,
//! so a reviewer sees the diff of what the engine now does.
//!
//! Note that `worlds/company-2026/world.json` is generated by
//! `scripts/build-content.sh`. If that file is regenerated the corpus will report
//! `the world definition itself changed` before any hash mismatch, so a content
//! change is never mistaken for an engine regression.

use computerworld::{
    ActionEnvelope, EnvironmentConfig, HttpRequest, SimError, World, WorldDefinition,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

const CORPUS_VERSION: u32 = 1;
const BLESS_VAR: &str = "CW_BLESS_DETERMINISM_CORPUS";
const BLESS_PHRASE: &str = "yes-i-intend-to-change-observable-behaviour";

const COMPANY: &str = include_str!("../../../worlds/company-2026/world.json");
const AGENT_DESKTOP: &str = include_str!("../../../worlds/agent-desktop/world.json");

const ALL_FAMILIES: &[&str] = &[
    "terminal.v1",
    "filesystem.v1",
    "application.v1",
    "browser.v1",
    "keyboard.v1",
    "pointer.v1",
    "http.v1",
];

// ---------------------------------------------------------------------------
// Scenarios
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq)]
enum WorldKind {
    Company,
    AgentDesktop,
}
impl WorldKind {
    fn json(self) -> &'static str {
        match self {
            WorldKind::Company => COMPANY,
            WorldKind::AgentDesktop => AGENT_DESKTOP,
        }
    }
    fn name(self) -> &'static str {
        match self {
            WorldKind::Company => "worlds/company-2026/world.json",
            WorldKind::AgentDesktop => "worlds/agent-desktop/world.json",
        }
    }
    /// Addresses the scripts navigate to. Small static sites on purpose: the engine
    /// paths under test — the omnibox, DNS, the simulated network, history, tabs and
    /// the page projection — are the same whichever site answers, but laying out one
    /// of the world's large public sites costs seconds per navigation in a debug
    /// build and would put this suite out of reach. `file:` is refused rather than
    /// searched for, and an address that does not resolve becomes a search: both are
    /// observable behaviour and must not drift either.
    fn urls(self) -> &'static [&'static str] {
        match self {
            WorldKind::Company => &[
                "http://intranet.internal/",
                "http://intranet.internal/handbook",
                "https://northstar.example",
                "https://status.northstar.example",
                "https://guide.example",
                "file:///etc/passwd",
            ],
            WorldKind::AgentDesktop => &[
                "http://wiki.internal/",
                "http://wiki.internal/wiki/Main_Page",
                "http://wiki.internal/missing",
                "file:///etc/passwd",
            ],
        }
    }
}

struct Scenario {
    name: &'static str,
    world: WorldKind,
    seed: u64,
    actor: &'static str,
    machines: &'static [&'static str],
    families: &'static [&'static str],
    observations: &'static [&'static str],
    /// Steps in the main run, before the mid-run checkpoint is taken.
    steps: usize,
    /// Step index the checkpoint is taken at; the two forks start here.
    fork_at: usize,
    /// Steps driven down each fork, with different actions on each side.
    branch_steps: usize,
    /// `state_hash()` is recorded every `hash_stride` steps (and always on the
    /// last step and at the checkpoint). It is 1 — every step — wherever that is
    /// affordable. On `company-2026` one `state_hash()` canonicalises a 3.7 MB
    /// world definition and costs ~0.7 s in a debug build, so per-step hashing
    /// there would make this suite take three quarters of an hour. Divergence is
    /// still localised to the exact step by the per-step `StepResult` digests and
    /// by the event log, which are recorded for every step of every scenario; the
    /// strided state hash is the backstop for state those two do not expose.
    hash_stride: usize,
    /// Ask the engine to hash after every step and refuse a divergent replay
    /// itself. Same cost consideration as `hash_stride`.
    verify_steps: bool,
}

const SCENARIOS: &[Scenario] = &[
    Scenario {
        name: "company-alice-seed1",
        world: WorldKind::Company,
        seed: 1,
        actor: "alice",
        machines: &["alice-mac"],
        families: ALL_FAMILIES,
        observations: &["terminal.v1", "semantic.v1"],
        steps: 320,
        fork_at: 160,
        branch_steps: 40,
        hash_stride: 20,
        verify_steps: false,
    },
    Scenario {
        name: "company-alice-seed90210",
        world: WorldKind::Company,
        seed: 90210,
        actor: "alice",
        machines: &["alice-mac"],
        families: ALL_FAMILIES,
        observations: &["terminal.v1", "semantic.v1"],
        steps: 320,
        fork_at: 160,
        branch_steps: 40,
        hash_stride: 20,
        verify_steps: false,
    },
    Scenario {
        name: "company-three-machines-seed4242",
        world: WorldKind::Company,
        seed: 4242,
        actor: "carol",
        machines: &["alice-mac", "bob-windows", "carol-ubuntu"],
        families: ALL_FAMILIES,
        observations: &["terminal.v1", "semantic.v1"],
        steps: 360,
        fork_at: 200,
        branch_steps: 40,
        hash_stride: 20,
        verify_steps: false,
    },
    Scenario {
        name: "agent-desktop-seed7",
        world: WorldKind::AgentDesktop,
        seed: 7,
        actor: "ada",
        machines: &["workstation"],
        families: ALL_FAMILIES,
        observations: &["terminal.v1", "semantic.v1"],
        steps: 300,
        fork_at: 150,
        branch_steps: 40,
        hash_stride: 1,
        verify_steps: true,
    },
    Scenario {
        name: "agent-desktop-seed31337",
        world: WorldKind::AgentDesktop,
        seed: 31337,
        actor: "ada",
        machines: &["workstation"],
        families: &[
            "terminal.v1",
            "filesystem.v1",
            "application.v1",
            "keyboard.v1",
        ],
        observations: &["terminal.v1", "semantic.v1"],
        steps: 300,
        fork_at: 150,
        branch_steps: 40,
        hash_stride: 1,
        verify_steps: true,
    },
];

/// The scenario whose exported snapshot is committed as a fixture, so a snapshot
/// taken before an engine change can be proved to still import after it. The
/// small world keeps the fixture small.
const PORTABLE_SNAPSHOT_SCENARIO: usize = 4;

// ---------------------------------------------------------------------------
// The golden shape
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize)]
struct Golden {
    corpus_version: u32,
    scenario: String,
    world: String,
    /// SHA-256 of the world definition file, so a regenerated world is reported
    /// as such instead of looking like an engine regression.
    world_definition_sha256: String,
    seed: u64,
    actor: String,
    machines: Vec<String>,
    families: Vec<String>,
    steps: usize,
    actions: usize,
    /// SHA-256 of the generated action script. If this moves, the generator was
    /// edited and every hash below is measuring a different program.
    script_sha256: String,
    /// How often `state_hash()` was sampled; see `Scenario::hash_stride`.
    state_hash_stride: usize,
    /// `state_hash()` at each sampled step of the main run.
    step_state_hashes: Vec<StepHash>,
    /// Digest of the whole `StepResult` after each step of the main run.
    step_result_digests: Vec<String>,
    journal_entries: usize,
    journal_head: String,
    events: Events,
    checkpoint: Checkpoint,
}

#[derive(Serialize, Deserialize)]
struct Events {
    count: usize,
    /// Rolling hash over every event in order: `h(i, h(i-1), event)`.
    chain_sha256: String,
    /// `sequence|tick|kind|machine|actor|sha256(data)[..16]`, one per event.
    records: Vec<String>,
}

/// One sample, carrying the step it was taken at so a failure can say "step 417"
/// rather than "element 20". `scene` is a digest of `scene(1280, 800)`, which is
/// built by `Environment::scene` — one of the files being rewritten — and is
/// observable behaviour in its own right.
#[derive(Serialize, Deserialize, PartialEq)]
struct StepHash {
    step: usize,
    hash: String,
    scene: String,
}

#[derive(Serialize, Deserialize)]
struct Checkpoint {
    at_step: usize,
    state_hash: String,
    export_sha256: String,
    export_bytes: usize,
    /// The original world, driven on after the checkpoint.
    branch_a: Vec<StepHash>,
    /// A fork of the checkpoint, driven with different actions.
    branch_b: Vec<StepHash>,
    /// Digest of every event the replayed world produced, which must equal the
    /// main run's `events.chain_sha256`.
    replayed_event_chain_sha256: String,
    replayed_state_hash: String,
    /// A second viewport at the end of branch A, so a scene change that only
    /// shows at another size is caught too.
    final_scene_390x844: String,
}

// ---------------------------------------------------------------------------
// Deterministic action scripts
// ---------------------------------------------------------------------------

/// splitmix64. The scripts must be a pure function of the scenario and nothing
/// the engine says, or a behaviour change would silently change the program the
/// corpus is measuring.
struct Rng(u64);
impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed)
    }
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        &items[self.below(items.len())]
    }
}

fn name_seed(name: &str) -> u64 {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in name.as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x1000_0000_01b3);
    }
    h
}

/// The simulated Windows shell speaks a different dialect; terminal work in the
/// scripts stays on the POSIX machines and the Windows box is driven through the
/// other families.
fn posix(machine: &str) -> bool {
    !machine.contains("windows")
}

const SCRATCH: &str = "/tmp/cw-corpus";

fn terminal_action(rng: &mut Rng, machine: &str, i: usize) -> ActionEnvelope {
    let command = match rng.below(16) {
        0 => format!("echo \"line {i}\" >> {SCRATCH}/log.txt"),
        1 => format!("mkdir -p {SCRATCH}/d{}", i % 7),
        2 => format!("ls -la {SCRATCH}"),
        3 => format!("cat {SCRATCH}/log.txt"),
        4 => format!("wc -l {SCRATCH}/log.txt"),
        5 => "pwd".to_string(),
        6 => "whoami".to_string(),
        7 => format!("printf 'a%sb\\n' {i}"),
        8 => format!("sha256sum {SCRATCH}/log.txt"),
        9 => format!("sort {SCRATCH}/log.txt | head -3"),
        10 => format!("touch {SCRATCH}/t{}.txt", i % 5),
        11 => format!("sed -n '1,2p' {SCRATCH}/log.txt"),
        12 => format!("rm -f {SCRATCH}/t{}.txt", i % 5),
        13 => format!("seq 1 {}", i % 9 + 1),
        14 => format!("stat {SCRATCH}/log.txt"),
        _ => format!("grep -c line {SCRATCH}/log.txt"),
    };
    ActionEnvelope::new(
        "terminal.v1",
        "execute",
        machine,
        json!({"command": command}),
    )
}

fn filesystem_action(rng: &mut Rng, machine: &str, i: usize) -> ActionEnvelope {
    let path = format!("{SCRATCH}/f{}.txt", i % 11);
    match rng.below(4) {
        0 => ActionEnvelope::new(
            "filesystem.v1",
            "write",
            machine,
            json!({"path": path, "content": format!("payload {i}\n")}),
        ),
        1 => ActionEnvelope::new("filesystem.v1", "read", machine, json!({"path": path})),
        2 => ActionEnvelope::new("filesystem.v1", "list", machine, json!({"path": SCRATCH})),
        _ => ActionEnvelope::new("filesystem.v1", "stat", machine, json!({"path": path})),
    }
}

fn application_action(rng: &mut Rng, machine: &str, i: usize) -> ActionEnvelope {
    const KINDS: &[&str] = &["terminal", "browser", "editor", "files", "code", "notes"];
    const PANELS: &[&str] = &[
        "shell:launcher",
        "shell:home",
        "shell:panel:file",
        "shell:panel:view",
        "shell:panel:settings",
        "shell:search",
        "shell:notifications",
    ];
    match rng.below(10) {
        0 => ActionEnvelope::new("application.v1", "list", machine, json!({})),
        1 | 2 => ActionEnvelope::new(
            "application.v1",
            "launch",
            machine,
            json!({"kind": rng.pick(KINDS)}),
        ),
        3 => ActionEnvelope::new(
            "application.v1",
            "focus",
            machine,
            json!({"window": (i % 5 + 1) as u64}),
        ),
        4 => ActionEnvelope::new(
            "application.v1",
            "close",
            machine,
            json!({"window": (i % 7 + 1) as u64}),
        ),
        5 => ActionEnvelope::new("application.v1", "minimize", machine, json!({})),
        6 => ActionEnvelope::new("application.v1", "maximize", machine, json!({})),
        7 => ActionEnvelope::new("application.v1", "switcher", machine, json!({})),
        8 => ActionEnvelope::new("application.v1", "launcher", machine, json!({})),
        _ => ActionEnvelope::new(
            "application.v1",
            "shell",
            machine,
            json!({"target": rng.pick(PANELS)}),
        ),
    }
}

fn browser_action(rng: &mut Rng, machine: &str, urls: &[&str], i: usize) -> ActionEnvelope {
    match rng.below(12) {
        0..=3 => ActionEnvelope::new(
            "browser.v1",
            "navigate",
            machine,
            json!({"url": rng.pick(urls)}),
        ),
        4 => ActionEnvelope::new("browser.v1", "back", machine, json!({})),
        5 => ActionEnvelope::new("browser.v1", "forward", machine, json!({})),
        6 => ActionEnvelope::new("browser.v1", "reload", machine, json!({})),
        7 => ActionEnvelope::new("browser.v1", "new_tab", machine, json!({})),
        8 => ActionEnvelope::new(
            "browser.v1",
            "switch_tab",
            machine,
            json!({"tab": (i % 3) as u64}),
        ),
        9 => ActionEnvelope::new(
            "browser.v1",
            "scroll",
            machine,
            json!({"y": (i as i64 * 37) % 900}),
        ),
        10 => ActionEnvelope::new(
            "browser.v1",
            "close_tab",
            machine,
            json!({"tab": (i % 2) as u64}),
        ),
        _ => ActionEnvelope::new(
            "browser.v1",
            "key",
            machine,
            json!({"key": rng.pick(&["Tab", "Enter", "ArrowDown"])}),
        ),
    }
}

fn keyboard_action(rng: &mut Rng, machine: &str, i: usize) -> ActionEnvelope {
    const KEYS: &[&str] = &[
        "Enter",
        "Tab",
        "Backspace",
        "ArrowDown",
        "ArrowUp",
        "ArrowLeft",
        "ArrowRight",
        "Escape",
        "Alt+Tab",
    ];
    if rng.below(3) == 0 {
        ActionEnvelope::new(
            "keyboard.v1",
            "type",
            machine,
            json!({"text": format!("note {i} ")}),
        )
    } else {
        ActionEnvelope::new(
            "keyboard.v1",
            "key",
            machine,
            json!({"key": rng.pick(KEYS)}),
        )
    }
}

fn pointer_action(rng: &mut Rng, machine: &str) -> ActionEnvelope {
    let x = rng.below(1280) as i64;
    let y = rng.below(800) as i64;
    match rng.below(8) {
        0..=2 => ActionEnvelope::new(
            "pointer.v1",
            "move",
            machine,
            json!({"x": x, "y": y, "width": 1280, "height": 800}),
        ),
        3..=5 => ActionEnvelope::new(
            "pointer.v1",
            "click",
            machine,
            json!({"x": x, "y": y, "width": 1280, "height": 800}),
        ),
        6 => ActionEnvelope::new(
            "pointer.v1",
            "double_click",
            machine,
            json!({"x": x, "y": y, "width": 1280, "height": 800}),
        ),
        _ => ActionEnvelope::new(
            "pointer.v1",
            "wheel",
            machine,
            json!({"x": x, "y": y, "width": 1280, "height": 800, "delta_y": 120}),
        ),
    }
}

fn http_action(rng: &mut Rng, machine: &str, urls: &[&str]) -> ActionEnvelope {
    let url = *rng.pick(urls);
    let request = HttpRequest::json("GET", url, &json!({})).expect("request is representable");
    ActionEnvelope::new(
        "http.v1",
        "request",
        machine,
        serde_json::to_value(request).expect("request serializes"),
    )
}

fn one_action(rng: &mut Rng, scenario: &Scenario, i: usize) -> ActionEnvelope {
    let machine = *rng.pick(scenario.machines);
    let mut family = *rng.pick(scenario.families);
    if family == "terminal.v1" && !posix(machine) {
        family = "filesystem.v1";
    }
    match family {
        "terminal.v1" => terminal_action(rng, machine, i),
        "filesystem.v1" => filesystem_action(rng, machine, i),
        "application.v1" => application_action(rng, machine, i),
        "browser.v1" => browser_action(rng, machine, scenario.world.urls(), i),
        "keyboard.v1" => keyboard_action(rng, machine, i),
        "pointer.v1" => pointer_action(rng, machine),
        "http.v1" => http_action(rng, machine, scenario.world.urls()),
        other => unreachable!("unhandled family {other}"),
    }
}

/// The whole program for a scenario: the main run, then branch A, then branch B.
/// `salt` separates the two branches so the forks are driven apart.
fn steps_for(
    scenario: &Scenario,
    salt: u64,
    count: usize,
    start: usize,
) -> Vec<Vec<ActionEnvelope>> {
    let mut rng = Rng::new(
        name_seed(scenario.name) ^ scenario.seed.rotate_left(17) ^ salt.wrapping_mul(0x2545_f491),
    );
    // A scratch directory to accumulate state in, on every POSIX machine.
    let mut program: Vec<Vec<ActionEnvelope>> = Vec::with_capacity(count + 1);
    if salt == 0 {
        let prologue: Vec<ActionEnvelope> = scenario
            .machines
            .iter()
            .filter(|m| posix(m) && scenario.families.contains(&"terminal.v1"))
            .map(|m| {
                ActionEnvelope::new(
                    "terminal.v1",
                    "execute",
                    *m,
                    json!({"command": format!("mkdir -p {SCRATCH}")}),
                )
            })
            .collect();
        if !prologue.is_empty() {
            program.push(prologue);
        }
    }
    while program.len() < count {
        let i = start + program.len();
        let batch = 1 + rng.below(3);
        program.push(
            (0..batch)
                .map(|_| one_action(&mut rng, scenario, i))
                .collect(),
        );
    }
    program
}

fn main_script(scenario: &Scenario) -> Vec<Vec<ActionEnvelope>> {
    steps_for(scenario, 0, scenario.steps, 0)
}

// ---------------------------------------------------------------------------
// Running a scenario
// ---------------------------------------------------------------------------

fn digest(value: &impl Serialize) -> String {
    format!(
        "{:x}",
        Sha256::digest(serde_json::to_vec(value).expect("value serializes"))
    )
}

fn short(value: &impl Serialize) -> String {
    digest(value)[..16].to_string()
}

fn build(scenario: &Scenario) -> (World, String) {
    let definition =
        WorldDefinition::from_json(scenario.world.json()).expect("packaged world parses");
    let mut world = World::new(definition, scenario.seed).expect("world builds");
    let session = world
        .environment(EnvironmentConfig {
            actor: scenario.actor.into(),
            machines: scenario.machines.iter().map(|m| (*m).into()).collect(),
            actions: scenario.families.iter().map(|f| (*f).into()).collect(),
            observations: scenario.observations.iter().map(|o| (*o).into()).collect(),
            action_budget: 1024,
        })
        .expect("session grants are valid");
    world
        .interfaces_mut()
        .enable_replay_verification(scenario.verify_steps);
    (world, session)
}

/// Whether `state_hash()` is sampled at this step: on the stride, on the last
/// step, and at the checkpoint.
fn sampled(index: usize, len: usize, stride: usize) -> bool {
    index + 1 == len || (index + 1).is_multiple_of(stride)
}

/// The semantic scene the actor would see at the desktop viewport.
fn scene_digest(world: &World, session: &str) -> String {
    short(
        &world
            .scene(session, 1280, 800)
            .expect("the session may see the scene"),
    )
}

/// Drive `program`, sampling a state hash on the stride. `offset` is the step
/// number the first entry of `program` has in the scenario as a whole, so a
/// failure names the step a reader can find in the script.
fn drive(
    world: &mut World,
    session: &str,
    program: &[Vec<ActionEnvelope>],
    stride: usize,
    offset: usize,
) -> Vec<StepHash> {
    let mut hashes = Vec::new();
    for (index, actions) in program.iter().enumerate() {
        world
            .step(session, actions.clone())
            .expect("a granted step is dispatched, whatever its per-action outcomes");
        if sampled(index, program.len(), stride) {
            hashes.push(StepHash {
                step: offset + index,
                hash: world.state_hash().expect("state hashes"),
                scene: scene_digest(world, session),
            });
        }
    }
    hashes
}

/// The event log, as a chained hash plus one readable line per event.
fn event_log(world: &World) -> (usize, String, Vec<String>) {
    let events = world.trajectory();
    let mut chain = String::new();
    let mut records = Vec::with_capacity(events.len());
    for (index, event) in events.iter().enumerate() {
        chain = digest(&(index as u64, &chain, event));
        records.push(format!(
            "{}|{}|{}|{}|{}|{}",
            event.sequence,
            event.tick,
            event.kind,
            event.machine.as_deref().unwrap_or(""),
            event.actor.as_deref().unwrap_or(""),
            short(&event.data),
        ));
    }
    (events.len(), chain, records)
}

struct Observed {
    golden: Golden,
    /// The snapshot exported at `fork_at`, kept so the bless run can commit it.
    export: String,
}

/// `CW_CORPUS_TRACE=1` prints where the time goes, for anyone tuning the step
/// counts or chasing a slow phase.
fn trace(scenario: &Scenario, phase: &str, at: &std::time::Instant) {
    if std::env::var("CW_CORPUS_TRACE").is_ok() {
        println!("[{}] {phase}: {:?}", scenario.name, at.elapsed());
    }
}

fn observe(scenario: &Scenario) -> Observed {
    let clock = std::time::Instant::now();
    let program = main_script(scenario);
    let (mut world, session) = build(scenario);
    let initial = world.snapshot();

    let mut state_hashes: Vec<StepHash> = Vec::new();
    let mut result_digests = Vec::with_capacity(program.len());
    let mut checkpoint: Option<(String, String, usize)> = None;
    let mut forked: Option<World> = None;

    for (index, actions) in program.iter().enumerate() {
        let result = world
            .step(&session, actions.clone())
            .expect("a granted step is dispatched, whatever its per-action outcomes");
        result_digests.push(short(&result));
        if index % 20 == 19 {
            trace(scenario, &format!("step {}", index + 1), &clock);
        }
        let at_checkpoint = index + 1 == scenario.fork_at;
        if at_checkpoint || sampled(index, program.len(), scenario.hash_stride) {
            let hash = world.state_hash().expect("state hashes");
            if sampled(index, program.len(), scenario.hash_stride) {
                state_hashes.push(StepHash {
                    step: index,
                    hash: hash.clone(),
                    scene: scene_digest(&world, &session),
                });
            }
            if at_checkpoint {
                let snapshot = world.snapshot();
                let export = world.export_snapshot().expect("snapshot exports");
                forked = Some(world.fork(&snapshot).expect("a mid-run fork is allowed"));
                checkpoint = Some((hash, export.clone(), export.len()));
            }
        }
    }

    trace(scenario, "main run", &clock);
    let (event_count, event_chain, event_records) = event_log(&world);
    trace(scenario, "event log", &clock);

    let journal = world.interfaces().action_journal().clone();
    assert!(
        journal.verify().expect("journal is serializable"),
        "{}: the recorded action journal does not verify against its own hash chain",
        scenario.name
    );
    let journal_head = journal
        .entries
        .last()
        .map(|e| e.hash.clone())
        .unwrap_or_default();
    let journal_entries = journal.entries.len();

    // Replay: the same initial checkpoint plus the same journal must reproduce
    // the same state and the same event log, event for event. Where step
    // verification is on the engine refuses a divergent replay itself, with
    // `replay_diverged`; where it is off these two comparisons are the check.
    let mut replayed = World::new(
        WorldDefinition::from_json(scenario.world.json()).expect("packaged world parses"),
        scenario.seed,
    )
    .expect("world builds");
    replayed
        .interfaces_mut()
        .replay(&initial, &journal)
        .unwrap_or_else(|e| {
            panic!(
                "{}: replaying the recorded journal diverged: [{}] {}",
                scenario.name, e.code, e.message
            )
        });
    trace(scenario, "replay", &clock);
    let replayed_state_hash = replayed.state_hash().expect("state hashes");

    // And the same journal, stepped entry by entry into a second fresh world, must
    // produce the same `StepResult` for every step — the same observation, the same
    // outcome values and the same `ActionEffect`, digest field included.
    //
    // This is not a golden comparison; it is the contract `ActionEffect::state`
    // states for itself: "equal digests mean equal observable state, in this
    // process or after a snapshot restore". A reconstructed world computes every
    // digest from scratch, so a digest that is cached anywhere and not invalidated
    // when the thing it stands for changes reports the stale value in the live run
    // and the true one here, and this fails — which is the failure mode a golden
    // captured from the same build could never see.
    let mut reconstructed = World::new(
        WorldDefinition::from_json(scenario.world.json()).expect("packaged world parses"),
        scenario.seed,
    )
    .expect("world builds");
    reconstructed
        .restore(&initial)
        .expect("the initial checkpoint restores");
    for (index, entry) in journal.entries.iter().enumerate() {
        let result = reconstructed
            .step(&entry.value.session, entry.value.actions.clone())
            .expect("a recorded step dispatches again");
        let digest = short(&result);
        assert_eq!(
            digest, result_digests[index],
            "{}: step {index} produced a different StepResult when the journal was \
             stepped into a freshly restored world. The world state itself agrees, so \
             the difference is in what the step *reported*, not in what it did — the \
             likeliest cause is a value cached across steps that survived a change it \
             should have been invalidated by. Dump both streams with \
             CW_CORPUS_DUMP_DIR to see which field.",
            scenario.name
        );
    }
    let (_, replayed_event_chain, _) = event_log(&replayed);
    assert_eq!(
        replayed_state_hash,
        state_hashes.last().expect("the run has steps").hash,
        "{}: replay reproduced a different final state",
        scenario.name
    );
    assert_eq!(
        replayed_event_chain, event_chain,
        "{}: replay reproduced a different event log",
        scenario.name
    );

    // The two forks are driven apart and must stay independent.
    let (checkpoint_hash, export, export_bytes) = checkpoint.expect("fork_at is within the run");
    let mut fork = forked.expect("fork_at is within the run");
    fork.interfaces()
        .session(&session)
        .expect("the fork carries the session");
    let branch_a_program = steps_for(scenario, 1, scenario.branch_steps, scenario.steps);
    let branch_b_program = steps_for(scenario, 2, scenario.branch_steps, scenario.steps);
    let branch_a = drive(
        &mut world,
        &session,
        &branch_a_program,
        scenario.hash_stride,
        scenario.steps,
    );
    let branch_b = drive(
        &mut fork,
        &session,
        &branch_b_program,
        scenario.hash_stride,
        scenario.steps,
    );
    trace(scenario, "branches", &clock);
    let final_scene_390x844 = short(
        &world
            .scene(&session, 390, 844)
            .expect("the session may see the scene"),
    );
    assert_ne!(
        branch_a.last().map(|h| &h.hash),
        branch_b.last().map(|h| &h.hash),
        "{}: the two forks were driven with different actions and must not end in the same state",
        scenario.name
    );

    Observed {
        golden: Golden {
            corpus_version: CORPUS_VERSION,
            scenario: scenario.name.into(),
            world: scenario.world.name().into(),
            world_definition_sha256: format!("{:x}", Sha256::digest(scenario.world.json())),
            seed: scenario.seed,
            actor: scenario.actor.into(),
            machines: scenario.machines.iter().map(|m| (*m).into()).collect(),
            families: scenario.families.iter().map(|f| (*f).into()).collect(),
            steps: program.len(),
            actions: program.iter().map(Vec::len).sum(),
            script_sha256: digest(&program),
            state_hash_stride: scenario.hash_stride,
            step_state_hashes: state_hashes,
            step_result_digests: result_digests,
            journal_entries,
            journal_head,
            events: Events {
                count: event_count,
                chain_sha256: event_chain,
                records: event_records,
            },
            checkpoint: Checkpoint {
                at_step: scenario.fork_at,
                state_hash: checkpoint_hash,
                export_sha256: format!("{:x}", Sha256::digest(&export)),
                export_bytes,
                branch_a,
                branch_b,
                replayed_event_chain_sha256: replayed_event_chain,
                replayed_state_hash,
                final_scene_390x844,
            },
        },
        export,
    }
}

// ---------------------------------------------------------------------------
// Golden files
// ---------------------------------------------------------------------------

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/goldens/determinism")
}

fn golden_path(name: &str) -> PathBuf {
    golden_dir().join(format!("{name}.json"))
}

fn snapshot_fixture_path() -> PathBuf {
    golden_dir().join("portable-snapshot.json")
}

fn missing(path: &Path) -> String {
    format!(
        "no golden at {}.\nCapture one deliberately:\n  {BLESS_VAR}={BLESS_PHRASE} \\\n    cargo test -p computerworld --test determinism_corpus -- --ignored --exact regenerate_determinism_goldens --nocapture",
        path.display()
    )
}

fn load(name: &str) -> Golden {
    let path = golden_path(name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|_| panic!("{}", missing(&path)));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("golden {} is not readable: {e}", path.display()))
}

// ---------------------------------------------------------------------------
// Comparison, with a failure message worth reading
// ---------------------------------------------------------------------------

struct Report {
    scenario: String,
    problems: Vec<String>,
}
impl Report {
    fn new(scenario: &str) -> Self {
        Self {
            scenario: scenario.into(),
            problems: Vec::new(),
        }
    }
    fn field(
        &mut self,
        what: &str,
        observed: impl std::fmt::Display,
        golden: impl std::fmt::Display,
    ) {
        let (observed, golden) = (observed.to_string(), golden.to_string());
        if observed != golden {
            self.problems
                .push(format!("{what}: {observed} — expected {golden}"));
        }
    }
    /// Sampled state hashes, reported by the step they were taken at.
    fn hashes(&mut self, what: &str, observed: &[StepHash], golden: &[StepHash]) {
        if observed.len() != golden.len() {
            self.problems.push(format!(
                "{what}: {} samples — expected {}",
                observed.len(),
                golden.len()
            ));
        }
        let mut shown = 0;
        let mut total = 0;
        for (o, g) in observed.iter().zip(golden) {
            if o != g {
                total += 1;
                if shown < 5 {
                    shown += 1;
                    self.problems.push(if o.step != g.step {
                        format!(
                            "{what}: sample at step {} — expected a sample at step {}",
                            o.step, g.step
                        )
                    } else if o.hash != g.hash {
                        format!(
                            "{what} {}: state hash {} — expected {}",
                            o.step, o.hash, g.hash
                        )
                    } else {
                        format!(
                            "{what} {}: scene(1280x800) digest {} — expected {}",
                            o.step, o.scene, g.scene
                        )
                    });
                }
            }
        }
        if total > shown {
            self.problems
                .push(format!("{what}: and {} more differences", total - shown));
        }
    }
    /// Per-element comparison that names the index and stops after a few, so the
    /// message points at the first divergence rather than dumping the run.
    fn series(&mut self, what: &str, observed: &[String], golden: &[String]) {
        if observed.len() != golden.len() {
            self.problems.push(format!(
                "{what}: {} entries — expected {}",
                observed.len(),
                golden.len()
            ));
        }
        let mut shown = 0;
        let mut total = 0;
        for index in 0..observed.len().min(golden.len()) {
            if observed[index] != golden[index] {
                total += 1;
                if shown < 5 {
                    shown += 1;
                    self.problems.push(format!(
                        "{what} {index}: {} — expected {}",
                        observed[index], golden[index]
                    ));
                }
            }
        }
        if total > shown {
            self.problems
                .push(format!("{what}: and {} more differences", total - shown));
        }
    }
    fn finish(self) {
        if self.problems.is_empty() {
            return;
        }
        panic!(
            "determinism corpus `{}` diverged from its golden:\n  {}\n\n\
             This engine's contract is that a run is a pure function of (engine, world, seed,\n\
             action sequence, viewport). A difference above means observable behaviour changed.\n\
             Diagnose it before touching this fixture. If the change really is intended, see the\n\
             regeneration instructions at the top of tests/determinism_corpus.rs — it takes the\n\
             {BLESS_VAR} pass-phrase and belongs in its own commit.",
            self.scenario,
            self.problems.join("\n  ")
        );
    }
}

fn check(scenario: &Scenario) {
    let golden = load(scenario.name);
    // Checked first and on their own: if the fixture or the world file moved, say so
    // before running 300 steps and blaming the engine for it.
    let mut preflight = Report::new(scenario.name);
    preflight.field("corpus version", CORPUS_VERSION, golden.corpus_version);
    preflight.field(
        "the world definition file itself changed (a content change, not an engine regression) sha256",
        format!("{:x}", Sha256::digest(scenario.world.json())),
        &golden.world_definition_sha256,
    );
    preflight.finish();

    let mut report = Report::new(scenario.name);
    let observed = observe(scenario).golden;
    report.field("steps", observed.steps, golden.steps);
    report.field("actions", observed.actions, golden.actions);
    report.field(
        "action script sha256 (the generator in this file was edited)",
        &observed.script_sha256,
        &golden.script_sha256,
    );
    report.field(
        "state hash stride",
        observed.state_hash_stride,
        golden.state_hash_stride,
    );
    report.hashes(
        "step",
        &observed.step_state_hashes,
        &golden.step_state_hashes,
    );
    report.series(
        "step result digest at step",
        &observed.step_result_digests,
        &golden.step_result_digests,
    );
    report.field(
        "journal entries",
        observed.journal_entries,
        golden.journal_entries,
    );
    report.field(
        "journal head hash",
        &observed.journal_head,
        &golden.journal_head,
    );
    report.field("event count", observed.events.count, golden.events.count);
    report.field(
        "event log chain hash",
        &observed.events.chain_sha256,
        &golden.events.chain_sha256,
    );
    report.series("event", &observed.events.records, &golden.events.records);
    report.field(
        "checkpoint state hash",
        &observed.checkpoint.state_hash,
        &golden.checkpoint.state_hash,
    );
    report.field(
        "exported snapshot bytes",
        observed.checkpoint.export_bytes,
        golden.checkpoint.export_bytes,
    );
    report.field(
        "exported snapshot sha256",
        &observed.checkpoint.export_sha256,
        &golden.checkpoint.export_sha256,
    );
    report.hashes(
        "fork branch A, step",
        &observed.checkpoint.branch_a,
        &golden.checkpoint.branch_a,
    );
    report.hashes(
        "fork branch B, step",
        &observed.checkpoint.branch_b,
        &golden.checkpoint.branch_b,
    );
    report.field(
        "state hash after replaying the journal",
        &observed.checkpoint.replayed_state_hash,
        &golden.checkpoint.replayed_state_hash,
    );
    report.field(
        "event log chain hash after replaying the journal",
        &observed.checkpoint.replayed_event_chain_sha256,
        &golden.checkpoint.replayed_event_chain_sha256,
    );
    report.field(
        "scene(390x844) digest at the end of branch A",
        &observed.checkpoint.final_scene_390x844,
        &golden.checkpoint.final_scene_390x844,
    );
    report.finish();
}

// ---------------------------------------------------------------------------
// The tests
// ---------------------------------------------------------------------------

#[test]
fn company_2026_alice_seed_1_replays_exactly() {
    check(&SCENARIOS[0]);
}

#[test]
fn company_2026_alice_seed_90210_replays_exactly() {
    check(&SCENARIOS[1]);
}

#[test]
fn company_2026_three_machines_replay_exactly() {
    check(&SCENARIOS[2]);
}

#[test]
fn agent_desktop_seed_7_replays_exactly() {
    check(&SCENARIOS[3]);
}

#[test]
fn agent_desktop_seed_31337_replays_exactly() {
    check(&SCENARIOS[4]);
}

/// A snapshot exported at the baseline commit, committed as a fixture. It must
/// still import into the engine as it is now, and still hash to what it hashed
/// to then. This is the only check that spans engine versions.
#[test]
fn a_snapshot_taken_before_the_change_still_imports_after_it() {
    let scenario = &SCENARIOS[PORTABLE_SNAPSHOT_SCENARIO];
    let path = snapshot_fixture_path();
    let stored = std::fs::read_to_string(&path).unwrap_or_else(|_| panic!("{}", missing(&path)));
    let golden = load(scenario.name);
    let definition =
        WorldDefinition::from_json(scenario.world.json()).expect("packaged world parses");
    let mut world = World::new(definition, scenario.seed).expect("world builds");
    world.import_snapshot(&stored).unwrap_or_else(|e| {
        panic!(
            "the committed baseline snapshot no longer imports: [{}] {}\n\
             A snapshot taken before an engine change must still restore after it.",
            e.code, e.message
        )
    });
    assert_eq!(
        world.state_hash().expect("state hashes"),
        golden.checkpoint.state_hash,
        "the committed baseline snapshot imported but now hashes differently"
    );
    // And the restored world carries the journal it was exported with.
    assert_eq!(
        world.interfaces().action_journal().entries.len(),
        scenario.fork_at,
        "the imported snapshot lost or gained journal entries"
    );
}

/// An application registered after a snapshot was taken: the snapshot cannot refer to it.
struct RegisteredLater;
impl cw_sdk::Application for RegisteredLater {
    fn kind(&self) -> &str {
        "registered.later"
    }
    fn event(
        &self,
        _state: &mut Value,
        _context: &cw_sdk::AppContext,
        _event: &cw_sdk::AppEvent,
    ) -> cw_protocol::Result<Vec<cw_sdk::AppEffect>> {
        Ok(Vec::new())
    }
    fn page(
        &self,
        _state: &Value,
        _context: &cw_sdk::AppContext,
    ) -> cw_protocol::Result<cw_protocol::Page> {
        Ok(cw_protocol::Page {
            version: 1,
            title: "later".into(),
            elements: Vec::new(),
            theme: None,
            lang: None,
        })
    }
}

#[test]
fn a_snapshot_imports_into_an_engine_that_has_registered_more_since() {
    // A module registered after the snapshot was taken (a new application, or a
    // service kind the world does not use, such as the `oss-web` feature's) is no
    // reason to refuse it: nothing in the snapshot can refer to it.
    let scenario = &SCENARIOS[PORTABLE_SNAPSHOT_SCENARIO];
    let stored = std::fs::read_to_string(snapshot_fixture_path()).expect("baseline snapshot");
    let golden = load(scenario.name);
    let definition =
        WorldDefinition::from_json(scenario.world.json()).expect("packaged world parses");
    let mut world = World::new(definition, scenario.seed).expect("world builds");
    world
        .register_application(RegisteredLater)
        .expect("registers");
    world
        .import_snapshot(&stored)
        .unwrap_or_else(|e| panic!("refused: [{}] {}", e.code, e.message));
    assert_eq!(
        world.state_hash().expect("state hashes"),
        golden.checkpoint.state_hash
    );
}

// ---------------------------------------------------------------------------
// The negative half: what `validate_snapshot` must keep refusing
// ---------------------------------------------------------------------------

fn expect_refusal<T>(what: &str, got: Result<T, SimError>, code: &str, message: &str) {
    match got {
        Ok(_) => panic!(
            "{what}: accepted. `validate_snapshot` must still refuse this with [{code}] {message}.\n\
             Silently accepting an invalid checkpoint is the most dangerous outcome a performance\n\
             change can have here: nothing else in the suite would catch it."
        ),
        Err(e) => assert_eq!(
            (e.code.as_str(), e.message.as_str()),
            (code, message),
            "{what}: refused, but with a different error identity"
        ),
    }
}

fn small_world() -> (World, String) {
    let definition = WorldDefinition::from_json(AGENT_DESKTOP).expect("the example world parses");
    let mut world = World::new(definition, 7).expect("world builds");
    let config: EnvironmentConfig =
        serde_json::from_value(world.definition().metadata["actor_session"].clone())
            .expect("metadata.actor_session is an EnvironmentConfig");
    let session = world.environment(config).expect("session grants are valid");
    (world, session)
}

fn company_world() -> World {
    let definition = WorldDefinition::from_json(COMPANY).expect("the reference world parses");
    let mut world = World::new(definition, 3).expect("world builds");
    world
        .environment(EnvironmentConfig {
            actor: "alice".into(),
            machines: vec!["alice-mac".into()],
            actions: ALL_FAMILIES.iter().map(|f| (*f).into()).collect(),
            observations: vec!["semantic.v1".into()],
            action_budget: 64,
        })
        .expect("session grants are valid");
    world
}

/// Export, edit one field of the JSON, and try to import it again.
fn tampered(world: &World, edit: impl FnOnce(&mut Value)) -> String {
    let mut value: Value = serde_json::from_str(
        &world
            .export_snapshot()
            .expect("a world with no live effects exports"),
    )
    .expect("an exported snapshot is JSON");
    edit(&mut value);
    serde_json::to_string(&value).expect("the edited snapshot serializes")
}

#[test]
fn a_snapshot_from_a_different_world_is_still_refused() {
    let (small, _) = small_world();
    let foreign = small.export_snapshot().expect("the small world exports");
    let mut company = company_world();
    expect_refusal(
        "a company-2026 world importing an agent-desktop checkpoint",
        company.import_snapshot(&foreign),
        "invalid",
        "checkpoint belongs to a different world definition",
    );
    // And the other way round, so neither direction is accidentally permissive.
    let company_export = company
        .export_snapshot()
        .expect("the company world exports");
    let (mut small, _) = small_world();
    expect_refusal(
        "an agent-desktop world importing a company-2026 checkpoint",
        small.import_snapshot(&company_export),
        "invalid",
        "checkpoint belongs to a different world definition",
    );
}

#[test]
fn an_incompatible_engine_or_version_is_still_refused() {
    let (world, _) = small_world();
    let (mut target, _) = small_world();
    expect_refusal(
        "a checkpoint claiming a future kernel snapshot version",
        target.import_snapshot(&tampered(&world, |v| v["kernel"]["version"] = json!(9999))),
        "invalid",
        "incompatible kernel checkpoint version",
    );
    expect_refusal(
        "a checkpoint from another engine build",
        target.import_snapshot(&tampered(&world, |v| {
            v["kernel"]["engine"] = json!("0.0.0-not-this-engine")
        })),
        "invalid",
        "incompatible kernel checkpoint version",
    );
    expect_refusal(
        "a checkpoint claiming a future environment snapshot version",
        target.import_snapshot(&tampered(&world, |v| v["version"] = json!(2))),
        "invalid",
        "unsupported environment snapshot",
    );
    expect_refusal(
        "a checkpoint whose application modules differ",
        target.import_snapshot(&tampered(&world, |v| {
            v["app_modules"] = json!({"ghost.app": 1})
        })),
        "invalid",
        "application module versions differ",
    );
    expect_refusal(
        "a checkpoint whose interface modules differ",
        target.import_snapshot(&tampered(&world, |v| {
            v["interface_modules"] = json!({"ghost.channel": 1})
        })),
        "invalid",
        "interface module versions differ",
    );
}

#[test]
fn a_machine_grant_that_is_not_in_the_world_is_still_refused() {
    let (world, _) = small_world();
    let (mut target, _) = small_world();
    expect_refusal(
        "a checkpoint granting a machine the world does not have",
        target.import_snapshot(&tampered(&world, |v| {
            let sessions = v["sessions"]
                .as_object_mut()
                .expect("sessions is an object");
            let session = sessions.values_mut().next().expect("there is one session");
            let machine = session["machines"]["workstation"].take();
            session["machines"] = json!({ "ghost-machine": machine });
            session["config"]["machines"] = json!(["ghost-machine"]);
            session["focused_machine"] = json!("ghost-machine");
        })),
        "invalid",
        "invalid machine grant",
    );
}

#[test]
fn a_tampered_action_journal_is_still_refused() {
    let (mut world, session) = small_world();
    for i in 0..3 {
        world
            .step(
                &session,
                vec![ActionEnvelope::new(
                    "terminal.v1",
                    "execute",
                    "workstation",
                    json!({"command": format!("echo {i}")}),
                )],
            )
            .expect("a granted step is dispatched");
    }
    let (mut target, _) = small_world();
    expect_refusal(
        "a checkpoint whose journal was edited after the fact",
        target.import_snapshot(&tampered(&world, |v| {
            v["journal"]["entries"][1]["value"]["actions"][0]["payload"]["command"] =
                json!("echo tampered")
        })),
        "invalid",
        "invalid action journal",
    );
}

#[test]
fn a_checkpoint_with_unresolved_live_host_effects_is_still_refused() {
    // A world whose gateway allows a host effect, so one can actually be started.
    let mut definition: Value =
        serde_json::from_str(AGENT_DESKTOP).expect("the example world parses");
    definition["network"]["gateway"] = json!({
        "allow_local": true,
        "allow_internet": false,
        "allow_host": true,
        "host_allowlist": ["example.com"],
        "sources": ["workstation"],
        "ports": [443],
        "schemes": ["https"],
        "allowed_cidrs": ["203.0.113.0/24"],
    });
    let json = serde_json::to_string(&definition).expect("the edited world serializes");
    let mut world = World::new(
        WorldDefinition::from_json(&json).expect("the edited world validates"),
        7,
    )
    .expect("world builds");

    let request = HttpRequest::json("GET", "https://example.com/", &json!({}))
        .expect("request is representable");
    world
        .runtime_mut()
        .begin_external("workstation", "ada", request, vec!["203.0.113.5".into()])
        .expect("the gateway policy above permits this host effect");

    // The source side refuses to produce a portable checkpoint at all.
    expect_refusal(
        "exporting a snapshot while a host effect is live",
        world.export_snapshot(),
        "external_effect_pending",
        "complete live host effects before portable snapshot or fork",
    );

    // And the restore side refuses one that claims a live effect.
    let snapshot = world.snapshot();
    let mut target = World::new(
        WorldDefinition::from_json(&json).expect("the edited world validates"),
        7,
    )
    .expect("world builds");
    expect_refusal(
        "restoring a checkpoint that carries an unresolved live host effect",
        target.restore(&snapshot),
        "external_effect_pending",
        "checkpoint contains live host effects",
    );
    expect_refusal(
        "forking a checkpoint that carries an unresolved live host effect",
        target.fork(&snapshot).map(|_| ()),
        "external_effect_pending",
        "checkpoint contains live host effects",
    );
    // The same refusal survives a round trip through JSON, which is how a
    // checkpoint reaches another process.
    let mut fresh = World::new(
        WorldDefinition::from_json(&json).expect("the edited world validates"),
        7,
    )
    .expect("world builds");
    let clean = fresh
        .export_snapshot()
        .expect("a world with no live effects exports");
    let mut value: Value = serde_json::from_str(&clean).expect("an exported snapshot is JSON");
    value["kernel"]["external_pending"] = json!(true);
    expect_refusal(
        "importing a checkpoint flagged with a live host effect",
        fresh.import_snapshot(&serde_json::to_string(&value).expect("serializes")),
        "external_effect_pending",
        "checkpoint contains live host effects",
    );
}

// ---------------------------------------------------------------------------
// Diagnosis
// ---------------------------------------------------------------------------

/// When the step-result digests diverge but the state hashes do not, the
/// difference is somewhere inside `StepResult` — an observation channel, an
/// outcome value, a refusal reason or an `ActionEffect`. This writes every
/// `StepResult` of every scenario out in full, so the same command run in a tree
/// at the last good commit and in the tree under test gives two files to diff,
/// and the diff names the field.
///
/// ```text
/// CW_CORPUS_DUMP_DIR=/tmp/before cargo test -p computerworld \
///   --test determinism_corpus -- --ignored --exact dump_step_results
/// ```
#[test]
#[ignore = "a diagnostic, not a check; set CW_CORPUS_DUMP_DIR"]
fn dump_step_results() {
    let dir = std::env::var("CW_CORPUS_DUMP_DIR")
        .expect("set CW_CORPUS_DUMP_DIR to the directory to write the dumps into");
    std::fs::create_dir_all(&dir).expect("the dump directory is writable");
    for scenario in SCENARIOS {
        let program = main_script(scenario);
        let (mut world, session) = build(scenario);
        let results: Vec<_> = program
            .iter()
            .map(|actions| {
                world
                    .step(&session, actions.clone())
                    .expect("a granted step is dispatched")
            })
            .collect();
        let path = PathBuf::from(&dir).join(format!("{}.json", scenario.name));
        std::fs::write(
            &path,
            serde_json::to_string_pretty(&results).expect("step results serialize"),
        )
        .expect("the dump is writable");
        println!("wrote {}", path.display());
    }
}

// ---------------------------------------------------------------------------
// Deliberate regeneration
// ---------------------------------------------------------------------------

#[test]
#[ignore = "regenerating the determinism goldens is a deliberate act; see the module docs"]
fn regenerate_determinism_goldens() {
    let phrase = std::env::var(BLESS_VAR).unwrap_or_default();
    assert_eq!(
        phrase, BLESS_PHRASE,
        "\n\nRefusing to regenerate the determinism goldens.\n\
         These fixtures record what the engine observably does. Overwriting them hides a\n\
         behaviour change rather than explaining it. If the change is intended, say so:\n\n  \
         {BLESS_VAR}={BLESS_PHRASE} \\\n    cargo test -p computerworld --test determinism_corpus \
         -- --ignored --exact regenerate_determinism_goldens --nocapture\n\n\
         and commit the result on its own, with the reason in the commit message.\n"
    );
    std::fs::create_dir_all(golden_dir()).expect("the golden directory is writable");
    for (index, scenario) in SCENARIOS.iter().enumerate() {
        let observed = observe(scenario);
        let path = golden_path(scenario.name);
        std::fs::write(
            &path,
            serde_json::to_string_pretty(&observed.golden).expect("the golden serializes") + "\n",
        )
        .expect("the golden is writable");
        println!(
            "wrote {} ({} steps, {} events, {} bytes)",
            path.display(),
            observed.golden.steps,
            observed.golden.events.count,
            std::fs::metadata(&path).map(|m| m.len()).unwrap_or(0),
        );
        if index == PORTABLE_SNAPSHOT_SCENARIO {
            std::fs::write(snapshot_fixture_path(), &observed.export)
                .expect("the snapshot fixture is writable");
            println!(
                "wrote {} ({} bytes)",
                snapshot_fixture_path().display(),
                observed.export.len()
            );
        }
    }
}
