[package]
name = "cw-services"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
cw-protocol = { path = "../protocol" }
cw-sdk = { path = "../sdk" }
cw-service-git = { path = "../../services/git" }
cw-service-issues = { path = "../../services/issues" }
cw-service-static-site = { path = "../../services/static-site" }
cw-service-mail = { path = "../../services/mail" }
cw-service-chat = { path = "../../services/chat" }
cw-service-messages = { path = "../../services/messages" }
cw-service-slack = { path = "../../services/slack" }
cw-service-discord = { path = "../../services/discord" }
cw-service-docs = { path = "../../services/docs" }
cw-service-calendar = { path = "../../services/calendar" }
cw-service-assistant = { path = "../../services/assistant" }
cw-service-bank = { path = "../../services/bank" }
cw-service-drive = { path = "../../services/drive" }
cw-service-forum = { path = "../../services/forum" }
cw-service-geo = { path = "../../services/geo" }
cw-service-media = { path = "../../services/media" }
cw-service-press = { path = "../../services/press" }
cw-service-search = { path = "../../services/search" }
cw-service-shop = { path = "../../services/shop" }
cw-service-speaker = { path = "../../services/speaker" }
cw-service-social = { path = "../../services/social" }
cw-service-wiki = { path = "../../services/wiki" }
[dev-dependencies]
serde_json.workspace = true
