// This demo builds a generic company blueprint with one touch-sized device.
import {readFile, writeFile} from 'node:fs/promises';
const definition=JSON.parse(await readFile(new URL('../../worlds/company-2026/world.json',import.meta.url),'utf8'));
definition.computers.push({id:'alice-phone',profile:'ubuntu',address:'10.0.0.15',user:'alice',initial_files:{'notes.txt':'Mobile notes\nRead http://mail.internal/ then update http://docs.internal/\n'},installed_apps:['browser','terminal','files','editor','desktop'],packages:['coreutils','curl','git']});
definition.network.nodes.push({id:'alice-phone',address:'10.0.0.15',zone:'local'});
definition.network.links.push({from:'app-server',to:'alice-phone',bidirectional:true,latency_us:10,loss_per_million:0});
definition.metadata={...definition.metadata,device_presentations:{'alice-mac':'desktop','bob-windows':'desktop','carol-ubuntu':'laptop','app-server':'server','git-server':'server','alice-phone':'phone'}};
await writeFile(new URL('./world-definition.js',import.meta.url),`// Generated by node examples/browser/build.mjs\nexport default ${JSON.stringify(definition,null,2)};\n`);
console.log('Built embedded network-console world (6 devices, 8 services).');
