// Package the world as a JavaScript asset: episodes never fetch definitions.
import {readFile, writeFile} from 'node:fs/promises';
const definition = JSON.parse(await readFile(new URL('../../worlds/company-2026/world.json', import.meta.url), 'utf8'));
await writeFile(new URL('./world-definition.js', import.meta.url), `// Generated by node examples/browser/build.mjs\nexport default ${JSON.stringify(definition,null,2)};\n`);
console.log('Embedded company-2026 world in examples/browser/world-definition.js');
