// Browser demo blueprint: OS shells are rendered by Rust, never HTML overlays.
import {readFile, writeFile} from 'node:fs/promises';
const definition=JSON.parse(await readFile(new URL('../../worlds/company-2026/world.json',import.meta.url),'utf8'));
const profiles=[
 {id:'virtual-macos-golden-gate',name:'macOS · Golden Gate',family:'macos',home:'/Users/{user}',case_sensitive:false,shell:'posix'},
 {id:'virtual-windows-11',name:'Windows 11',family:'windows',home:'C:/Users/{user}',case_sensitive:false,shell:'powershell'},
 {id:'virtual-ubuntu-24',name:'Ubuntu 24',family:'linux',home:'/home/{user}',case_sensitive:true,shell:'posix'},
 {id:'virtual-ios-18',name:'iOS 18',family:'ios',home:'/var/mobile',case_sensitive:true,shell:'posix'},
 {id:'virtual-android-12',name:'Android 12',family:'android',home:'/data/user/{user}',case_sensitive:true,shell:'posix'}
];
definition.profiles.push(...profiles);
for(const [id,profile] of [['alice-mac',profiles[0].id],['bob-windows',profiles[1].id],['carol-ubuntu',profiles[2].id]])definition.computers.find(c=>c.id===id).profile=profile;
for(const [id,profile,address,user] of [['alice-phone',profiles[3].id,'10.0.0.15','alice'],['bob-android',profiles[4].id,'10.0.0.16','bob']]){
 definition.computers.push({id,profile,address,user,initial_files:{'notes.txt':`Mobile notes for ${user}\nRead http://mail.internal/ then update http://docs.internal/\n`},installed_apps:['browser','terminal','files','editor','desktop'],packages:['coreutils','curl','git']});
 definition.network.nodes.push({id,address,zone:'local'});
 definition.network.links.push({from:'app-server',to:id,bidirectional:true,latency_us:10,loss_per_million:0});
}
definition.metadata={...definition.metadata,device_presentations:{'alice-mac':'desktop','bob-windows':'desktop','carol-ubuntu':'laptop','app-server':'server','git-server':'server','alice-phone':'phone','bob-android':'phone'}};
await writeFile(new URL('./world-definition.js',import.meta.url),`// Generated by node examples/browser/build.mjs\nexport default ${JSON.stringify(definition,null,2)};\n`);
console.log('Built embedded OS desktop world (7 devices, 5 graphical OS profiles, 8 services).');
