[package]
name = "cw-browser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cw-protocol = { path = "../../core/protocol" }
cw-scene = { path = "../../graphics/scene" }
serde.workspace = true
serde_json.workspace = true
url.workspace = true
cw-web = { path = "../engine" }
cw-ui = { path = "../ui" }
cw-determinism = { path = "../../core/determinism" }
png = "0.17"
jpeg-decoder = { version = "0.3", default-features = false, features = [
    "platform_independent",
] }
