[package]
name = "cw-computer"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
regex = "1"
cw-protocol = { path = "../protocol" }
cw-script-host = { path = "../script-host" }
cw-pyvm = { path = "../pyvm" }
cw-jsvm = { path = "../jsvm" }
[dev-dependencies]
proptest.workspace = true
