//! Rust code generation: a module's UI IR as a Rust module for `cw_ui`'s
//! `GenProgram` (see `cw_ui::program`), for apps built into the binary.
//!
//! Each IR function becomes a Rust `fn` that does what the interpreter does for its
//! statements and expressions, in the same order, through `cw_ui::gen`: the walk
//! over the IR is gone and control flow is Rust's. Frame slots are Rust locals
//! (`l<n>`), a closure's captures the `cap` slice. Expressions are flattened into
//! temporaries (`t<n>`) so evaluation order is the source's and no runtime call is
//! nested in another's arguments. Template holes check their dependency slots by
//! name, calls to module functions nobody reassigns are direct calls, and
//! templates are `static` data. `try`, optional chains and loops are labelled
//! blocks; an error inside one leaves it by `break` with the error, so a `catch`,
//! a `finally` or a chain's end sees it as the interpreter's would.
//!
//! Async functions are not translated: their IR travels in the module as JSON and
//! runs on the interpreter's suspendable walk (see `cw_ui::program`).
//!
//! The output is deterministic (a pure function of the IR), so a checked-in copy can
//! be verified by regenerating it.

use std::fmt::Write as _;

use cw_ui::ir::*;

/// Generates the Rust module `mod_name` for `m`. The module defines
/// `pub static PROGRAM: cw_ui::gen::GenProgram`.
pub fn emit(m: &Module, mod_name: &str) -> String {
    let hash = cw_ui::program::ir_hash(m);
    let mut g = Gen::new(m);
    let mut body = String::new();
    // Functions.
    for (i, f) in m.functions.iter().enumerate() {
        if f.is_async {
            continue;
        }
        let code = g.function(i as u32, f);
        body.push_str(&code);
    }
    let init = g.init();
    body.push_str(&init);

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by cw-tsx (`cw-tsx build --emit rust`) from the UI IR of `{}`",
        m.source
    );
    let _ = writeln!(
        out,
        "// (IR hash {hash:016x}). Do not edit: regenerate from the source."
    );
    out.push_str("#[rustfmt::skip]\n");
    out.push_str(
        "#[allow(unused_mut, unused_variables, unused_assignments, unused_labels, \
         unreachable_code, unused_parens, unused_braces, unused_imports, dead_code, \
         non_upper_case_globals, clippy::all)]\n",
    );
    let _ = writeln!(out, "pub mod {mod_name} {{");
    out.push_str("use std::rc::Rc;\nuse cw_ui::gen::*;\n\n");
    let _ = writeln!(out, "/// FNV-1a 64 of the IR's canonical JSON.");
    let _ = writeln!(out, "pub const IR_HASH: u64 = 0x{hash:016x};\n");
    // The program.
    let async_ir = async_ir(m);
    let hashes = "#".repeat(raw_hashes(&async_ir));
    let (container, root) = match &m.root {
        Some(r) => (format!("Some({:?})", r.container_id), r.element),
        None => ("None".to_owned(), 0),
    };
    let _ = writeln!(out, "pub static PROGRAM: GenProgram = GenProgram {{");
    let _ = writeln!(out, "    name: {:?},", m.source);
    let _ = writeln!(out, "    hash: IR_HASH,");
    let _ = writeln!(out, "    container_id: {container},");
    let _ = writeln!(out, "    root_element: {root},");
    let _ = writeln!(out, "    pure_render: {},", cw_ui::program::pure_render(m));
    let _ = writeln!(out, "    n_globals: {},", m.globals.len());
    let _ = writeln!(out, "    funcs: &FUNCS,");
    let _ = writeln!(out, "    templates: &TEMPLATES,");
    let _ = writeln!(out, "    init: init,");
    let _ = writeln!(out, "    async_ir: r{hashes}\"{async_ir}\"{hashes},");
    let _ = writeln!(out, "    async_cache: std::sync::OnceLock::new(),");
    let _ = writeln!(out, "}};\n");
    // Function table.
    let _ = writeln!(out, "static FUNCS: [GenFunc; {}] = [", m.functions.len());
    for (i, f) in m.functions.iter().enumerate() {
        let caps: Vec<String> = f.captures.iter().map(capture_lit).collect();
        let boxed: Vec<String> = f.boxed.iter().map(|b| b.to_string()).collect();
        let code = if f.is_async {
            "None".to_owned()
        } else {
            format!("Some(f{i} as GenFn)")
        };
        let _ = writeln!(
            out,
            "    GenFunc {{ name: {:?}, arity: {}, captures: &[{}], boxed: &[{}], code: {code} }},",
            f.name,
            f.arity(),
            caps.join(", "),
            boxed.join(", ")
        );
    }
    out.push_str("];\n\n");
    // Templates.
    let _ = writeln!(
        out,
        "static TEMPLATES: [STemplate; {}] = [",
        m.templates.len()
    );
    for t in &m.templates {
        let mut s = String::new();
        tnode(&t.root, &mut s);
        let _ = writeln!(
            out,
            "    STemplate {{ n_holes: {}, root: {s} }},",
            t.holes.len()
        );
    }
    out.push_str("];\n\n");
    out.push_str(&body);
    out.push_str("}\n");
    out
}

fn async_ir(m: &Module) -> String {
    let list: Vec<(u32, &Function)> = m
        .functions
        .iter()
        .enumerate()
        .filter(|(_, f)| f.is_async)
        .map(|(i, f)| (i as u32, f))
        .collect();
    if list.is_empty() {
        return String::new();
    }
    serde_json::to_string(&list).expect("IR serialises")
}

/// How many `#` a raw string needs so that `s` cannot end it.
fn raw_hashes(s: &str) -> usize {
    let mut n = 1;
    while s.contains(&format!("\"{}", "#".repeat(n))) {
        n += 1;
    }
    n
}

fn capture_lit(c: &Capture) -> String {
    match c {
        Capture::Local(n) => format!("Capture::Local({n})"),
        Capture::Capture(n) => format!("Capture::Capture({n})"),
    }
}

fn tnode(n: &TNode, out: &mut String) {
    match n {
        TNode::Element {
            tag,
            attrs,
            children,
        } => {
            let _ = write!(out, "STNode::Element {{ tag: {tag:?}, attrs: &[");
            for (i, a) in attrs.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                match a {
                    TAttr::Static(n, v) => {
                        let _ = write!(out, "STAttr::Static({n:?}, {v:?})");
                    }
                    TAttr::Dynamic(n, h) => {
                        let _ = write!(out, "STAttr::Dynamic({n:?}, {h})");
                    }
                    TAttr::Spread(h) => {
                        let _ = write!(out, "STAttr::Spread({h})");
                    }
                    TAttr::Ref(h) => {
                        let _ = write!(out, "STAttr::Ref({h})");
                    }
                }
            }
            out.push_str("], children: &[");
            for (i, c) in children.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                tnode(c, out);
            }
            out.push_str("] }");
        }
        TNode::Text(s) => {
            let _ = write!(out, "STNode::Text({s:?})");
        }
        TNode::Hole(h) => {
            let _ = write!(out, "STNode::Hole({h})");
        }
    }
}

/// A Rust `f64` literal.
fn num_lit(n: f64) -> String {
    if n.is_nan() {
        "f64::NAN".into()
    } else if n == f64::INFINITY {
        "f64::INFINITY".into()
    } else if n == f64::NEG_INFINITY {
        "f64::NEG_INFINITY".into()
    } else {
        let s = format!("{n:?}");
        if s.starts_with('-') {
            format!("({s})")
        } else {
            s
        }
    }
}

fn str_lit(s: &str) -> String {
    format!("{s:?}")
}

// ---------------------------------------------------------------- module analysis

struct Gen<'m> {
    m: &'m Module,
    /// String literals by index (`Runtime::lit`), shared by the whole program.
    lits: std::cell::RefCell<Vec<String>>,
    /// Per global: the function it holds when it is a function declaration nobody
    /// reassigns and that runs as generated code (calls to it are direct).
    direct: Vec<Option<u32>>,
    next_site: usize,
}

impl<'m> Gen<'m> {
    fn new(m: &'m Module) -> Gen<'m> {
        let mut assigned = vec![false; m.globals.len()];
        let mut mark = |e: &Expr| {
            if let Expr::Assign(lv, _, _) | Expr::Update(lv, _, _) = e {
                if let LValue::Global(g) = **lv {
                    if let Some(a) = assigned.get_mut(g as usize) {
                        *a = true;
                    }
                }
            }
        };
        for f in &m.functions {
            walk_stmts(&f.body, &mut mark);
            for p in &f.params {
                walk_pattern(p, &mut mark);
            }
        }
        for g in &m.globals {
            if let GlobalInit::Expr(e) | GlobalInit::Context(e) = &g.init {
                walk(e, &mut mark);
            }
        }
        let direct = m
            .globals
            .iter()
            .enumerate()
            .map(|(i, g)| match g.init {
                GlobalInit::Function(f)
                    if !assigned[i]
                        && m.functions
                            .get(f as usize)
                            .is_some_and(|x| !x.is_async && x.captures.is_empty()) =>
                {
                    Some(f)
                }
                _ => None,
            })
            .collect();
        Gen {
            m,
            lits: Default::default(),
            direct,
            next_site: 0,
        }
    }

    fn function(&mut self, index: u32, f: &Function) -> String {
        let mut cx = FnCx::new(self, Some(f));
        cx.prologue_params(f);
        cx.block(&f.body);
        cx.line("Ok(Value::Undefined)");
        let body = std::mem::take(&mut cx.out);
        let header = cx.header(&format!(
            "/// `{}` (line {}).\nfn f{index}(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {{\n",
            f.name.replace('`', "'"),
            f.line
        ));
        self.next_site = cx.site_next;
        format!("{header}{body}}}\n\n")
    }

    fn init(&mut self) -> String {
        let m = self.m;
        let mut cx = FnCx::new(self, None);
        for (i, g) in m.globals.iter().enumerate() {
            match &g.init {
                GlobalInit::Function(f) => {
                    cx.line(&format!("rt.set_global({i}, closure({f}, Vec::new()));"));
                }
                GlobalInit::Context(_) => {
                    cx.line(&format!("rt.set_global({i}, Value::Context({i}));"));
                }
                _ => {}
            }
        }
        for (i, g) in m.globals.iter().enumerate() {
            match &g.init {
                GlobalInit::Expr(e) => {
                    let a = cx.expr(e);
                    cx.line(&format!("rt.set_global({i}, {a});"));
                }
                GlobalInit::Context(e) => {
                    let a = cx.expr(e);
                    cx.line(&format!("rt.set_context_default({i}, {a});"));
                }
                _ => {}
            }
        }
        cx.line("Ok(())");
        let body = std::mem::take(&mut cx.out);
        let header = cx.header(
            "/// The module's globals, in declaration order.\nfn init(rt: &mut Runtime) -> R<()> {\n    let cap: &[Value] = &[];\n    let inst: Option<u32> = None;\n",
        );
        self.next_site = cx.site_next;
        format!("{header}{body}}}\n\n")
    }
}

// ---------------------------------------------------------------- functions

/// Where an error goes: out of the function (`?`), or to the end of a labelled
/// block (a `try` part or an optional chain) as its value.
#[derive(Clone)]
enum ErrTo {
    Fn,
    Label(String),
}

/// What `break`, `continue` and `return` see around them.
#[derive(Clone)]
enum Ctx {
    /// A loop: `'l<id>` ends it, `'b<id>` ends its body (a `continue`).
    Loop(u32),
    /// A `switch`: `'s<id>` ends it.
    Switch(u32),
    /// A `try` part: leaving it is `break '<label> Ok(Flow::…)`.
    Try(String),
}

struct FnCx<'g, 'm> {
    g: &'g Gen<'m>,
    boxed: Vec<bool>,
    n_locals: usize,
    out: String,
    indent: usize,
    tmp: u32,
    label: u32,
    ctx: Vec<Ctx>,
    err: Vec<ErrTo>,
    /// Template element sites of this function, by occurrence slot.
    sites: usize,
    site_next: usize,
}

impl<'g, 'm> FnCx<'g, 'm> {
    fn new(g: &'g Gen<'m>, f: Option<&Function>) -> FnCx<'g, 'm> {
        let n_locals = f.map(|f| f.n_locals as usize).unwrap_or(0);
        let mut boxed = vec![false; n_locals];
        if let Some(f) = f {
            for b in &f.boxed {
                if let Some(x) = boxed.get_mut(*b as usize) {
                    *x = true;
                }
            }
        }
        FnCx {
            g,
            boxed,
            n_locals,
            out: String::new(),
            indent: 1,
            tmp: 0,
            label: 0,
            ctx: Vec::new(),
            err: vec![ErrTo::Fn],
            sites: 0,
            site_next: g.next_site,
        }
    }

    /// The function's opening: its signature, its locals and its element-site
    /// occurrence counters.
    fn header(&self, sig: &str) -> String {
        let mut h = String::from(sig);
        if self.n_locals > 0 {
            h.push_str("    ");
            for i in 0..self.n_locals {
                let _ = write!(h, "let mut l{i}: Value = Value::Undefined; ");
            }
            h.push('\n');
        }
        if self.sites > 0 {
            let _ = writeln!(h, "    let mut occ = [0u32; {}];", self.sites);
        }
        h
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn open(&mut self, s: &str) {
        self.line(s);
        self.indent += 1;
    }

    fn close(&mut self, s: &str) {
        self.indent -= 1;
        self.line(s);
    }

    fn tmp(&mut self) -> String {
        self.tmp += 1;
        format!("t{}", self.tmp)
    }

    fn new_label(&mut self) -> u32 {
        self.label += 1;
        self.label
    }

    /// `e` (a `R<T>` expression) unwrapped, its error sent where errors go here.
    fn q(&self, e: &str) -> String {
        match self.err.last() {
            Some(ErrTo::Label(l)) => {
                format!("match {e} {{ Ok(v) => v, Err(e) => break '{l} Err(e) }}")
            }
            _ => format!("{e}?"),
        }
    }

    /// A statement throwing `t` (a `Throw`).
    fn raise(&self, t: &str) -> String {
        match self.err.last() {
            Some(ErrTo::Label(l)) => format!("break '{l} Err({t});"),
            _ => format!("return Err({t});"),
        }
    }

    /// Binds `v` to temp `name` and returns the name.
    fn bind_tmp(&mut self, v: &str) -> String {
        let t = self.tmp();
        self.line(&format!("let {t} = {v};"));
        t
    }

    /// The index of string literal `s` in the program's table.
    fn lit_index(&self, s: &str) -> usize {
        let mut lits = self.g.lits.borrow_mut();
        match lits.iter().position(|x| x == s) {
            Some(i) => i,
            None => {
                lits.push(s.to_owned());
                lits.len() - 1
            }
        }
    }

    /// A string value for literal `s` (made once per runtime).
    fn str_value(&mut self, s: &str) -> String {
        let i = self.lit_index(s);
        self.bind_tmp(&format!("rt.lit({i}, {})", str_lit(s)))
    }

    /// A property key `Str` for literal `k`.
    fn key_str(&mut self, k: &str) -> String {
        let i = self.lit_index(k);
        self.bind_tmp(&format!("rt.lit_key({i}, {})", str_lit(k)))
    }

    /// `e` as something to borrow: a non-boxed local's own slot when nothing in
    /// `later` (evaluated before the borrow is used) assigns it, else a temp.
    fn operand(&mut self, e: &Expr, later: &[&Expr]) -> String {
        if let Expr::Local(n) = e {
            if self.boxed.get(*n as usize) != Some(&true)
                && !later.iter().any(|x| writes_local(x, *n))
            {
                return format!("l{n}");
            }
        }
        self.expr(e)
    }

    /// `e` as a Rust `bool` (its truthiness), without boxing a comparison's result.
    fn cond(&mut self, e: &Expr) -> String {
        match e {
            Expr::Unary(UnaryOp::Not, x) => {
                let c = self.cond(x);
                format!("!({c})")
            }
            Expr::Binary(op, a, b) => match self.binary_bool(*op, a, b) {
                Some(c) => c,
                None => {
                    let v = self.expr(e);
                    format!("{v}.truthy()")
                }
            },
            Expr::Bool(b) => b.to_string(),
            _ => {
                let v = self.expr(e);
                format!("{v}.truthy()")
            }
        }
    }

    /// A comparison or equality as a Rust `bool` expression (operands evaluated
    /// first, in order); `None` for other operators.
    fn binary_bool(&mut self, op: BinaryOp, a: &Expr, b: &Expr) -> Option<String> {
        use BinaryOp as B;
        if !matches!(
            op,
            B::StrictEq | B::StrictNotEq | B::Eq | B::NotEq | B::Lt | B::LtEq | B::Gt | B::GtEq
        ) {
            return None;
        }
        let not = if matches!(op, B::StrictNotEq | B::NotEq) {
            "!"
        } else {
            ""
        };
        // Against a string literal: no string made.
        if matches!(op, B::StrictEq | B::StrictNotEq) {
            if let Expr::Str(lit) = b {
                let x = self.operand(a, &[]);
                return Some(format!("{not}eq_str(&{x}, {})", str_lit(lit)));
            }
            if let Expr::Str(lit) = a {
                let x = self.operand(b, &[]);
                return Some(format!("{not}eq_str(&{x}, {})", str_lit(lit)));
            }
        }
        // Against a number literal: a numeric comparison (a string compares as a
        // number with a number).
        if matches!(op, B::Lt | B::LtEq | B::Gt | B::GtEq) {
            let sym = match op {
                B::Lt => "<",
                B::LtEq => "<=",
                B::Gt => ">",
                _ => ">=",
            };
            if let Expr::Num(n) = b {
                let x = self.operand(a, &[]);
                return Some(format!("({x}.to_number() {sym} {})", num_lit(*n)));
            }
            if let Expr::Num(n) = a {
                let x = self.operand(b, &[]);
                return Some(format!("({} {sym} {x}.to_number())", num_lit(*n)));
            }
        }
        let x = self.operand(a, &[b]);
        let y = self.operand(b, &[]);
        Some(match op {
            B::StrictEq | B::StrictNotEq => format!("{not}strict_equals(&{x}, &{y})"),
            B::Eq | B::NotEq => format!("{not}loose_equals(&{x}, &{y})"),
            _ => format!("compare(BinaryOp::{op:?}, &{x}, &{y})"),
        })
    }

    // ------------------------------------------------------------ slots

    fn local_read(&self, n: u32) -> String {
        if self.boxed.get(n as usize) == Some(&true) {
            format!("read(&l{n})")
        } else {
            format!("l{n}.clone()")
        }
    }

    fn capture_read(&self, n: u32) -> String {
        format!("read(&cap[{n}])")
    }

    /// A slot as a closure copies it (a boxed slot's cell itself).
    fn slot_raw(&self, c: &Capture) -> String {
        match c {
            Capture::Local(n) => format!("l{n}.clone()"),
            Capture::Capture(n) => format!("cap[{n}].clone()"),
        }
    }

    /// A slot's value, as a hole's dependency reads it.
    fn slot_value(&self, c: &Capture) -> String {
        match c {
            Capture::Local(n) => format!("read(&l{n})"),
            Capture::Capture(n) => self.capture_read(*n),
        }
    }

    // ------------------------------------------------------------ patterns

    fn prologue_params(&mut self, f: &Function) {
        if f.params.is_empty() && f.rest.is_none() {
            return;
        }
        self.line("let mut args = args.into_iter();");
        for p in &f.params {
            let v = self.tmp();
            self.line(&format!(
                "let {v} = args.next().unwrap_or(Value::Undefined);"
            ));
            self.bind(p, &v);
        }
        if let Some(r) = &f.rest {
            let v = self.tmp();
            self.line(&format!("let {v} = Value::array(args.collect());"));
            self.bind(r, &v);
        }
    }

    /// Binds the value in temp `v` (moved) to pattern `p`.
    fn bind(&mut self, p: &Pattern, v: &str) {
        match p {
            Pattern::Local(n) => {
                if self.boxed.get(*n as usize) == Some(&true) {
                    self.line(&format!("l{n} = new_cell({v});"));
                } else {
                    self.line(&format!("l{n} = {v};"));
                }
            }
            Pattern::Ignore => {
                self.line(&format!("let _ = {v};"));
            }
            Pattern::Default(inner, d) => {
                let t = self.tmp();
                self.open(&format!("let {t} = if matches!({v}, Value::Undefined) {{"));
                let a = self.expr(d);
                self.line(&a);
                self.close(&format!("}} else {{ {v} }};"));
                self.bind(inner, &t);
            }
            Pattern::Array { items, rest } => {
                let arr = self.tmp();
                let e = self.q(&format!("array_items(&{v})"));
                self.line(&format!("let {arr} = {e};"));
                for (i, item) in items.iter().enumerate() {
                    if let Some(p) = item {
                        let x =
                            self.bind_tmp(&format!("{arr}.get({i}).cloned().unwrap_or_default()"));
                        self.bind(p, &x);
                    }
                }
                if let Some(r) = rest {
                    let x = self.bind_tmp(&format!("array_rest(&{arr}, {})", items.len()));
                    self.bind(r, &x);
                }
            }
            Pattern::Object { props, rest } => {
                let e = self.q(&format!("destructure_check(&{v})"));
                self.line(&format!("{e};"));
                for (k, p) in props {
                    let e = self.q(&format!("rt.member(&{v}, {})", str_lit(k)));
                    let x = self.bind_tmp(&e);
                    self.bind(p, &x);
                }
                if let Some(r) = rest {
                    let names: Vec<String> = props.iter().map(|(k, _)| str_lit(k)).collect();
                    let x = self.bind_tmp(&format!(
                        "object_rest(&{v}, &mut [{}].into_iter())",
                        names.join(", ")
                    ));
                    self.bind(r, &x);
                }
            }
        }
    }

    // ------------------------------------------------------------ statements

    fn block(&mut self, stmts: &[Stmt]) {
        for s in stmts {
            self.stmt(s);
        }
    }

    /// The statement leaving to loop or switch `target` by `break`.
    fn goto_break(&self, target_pos: usize) -> String {
        // A `try` part between here and the target is left with its flow.
        let id = match self.ctx[target_pos] {
            Ctx::Loop(id) | Ctx::Switch(id) => id,
            Ctx::Try(_) => unreachable!(),
        };
        if let Some(Ctx::Try(l)) = self.ctx[target_pos + 1..]
            .iter()
            .rev()
            .find(|c| matches!(c, Ctx::Try(_)))
        {
            return format!("break '{l} Ok(Flow::Break({id}));");
        }
        match self.ctx[target_pos] {
            Ctx::Loop(id) => format!("break 'l{id};"),
            Ctx::Switch(id) => format!("break 's{id};"),
            Ctx::Try(_) => unreachable!(),
        }
    }

    fn goto_continue(&self, target_pos: usize) -> String {
        let Ctx::Loop(id) = self.ctx[target_pos] else {
            unreachable!()
        };
        if let Some(Ctx::Try(l)) = self.ctx[target_pos + 1..]
            .iter()
            .rev()
            .find(|c| matches!(c, Ctx::Try(_)))
        {
            return format!("break '{l} Ok(Flow::Continue({id}));");
        }
        format!("break 'b{id};")
    }

    fn goto_return(&self, v: &str) -> String {
        match self.ctx.iter().rev().find(|c| matches!(c, Ctx::Try(_))) {
            Some(Ctx::Try(l)) => format!("break '{l} Ok(Flow::Return({v}));"),
            _ => format!("return Ok({v});"),
        }
    }

    fn break_stmt(&mut self) {
        let pos = self
            .ctx
            .iter()
            .rposition(|c| matches!(c, Ctx::Loop(_) | Ctx::Switch(_)));
        match pos {
            Some(p) => {
                let s = self.goto_break(p);
                self.line(&s);
            }
            None => {
                // Outside any loop: the interpreter's `Flow::Break` ends the function.
                let s = self.goto_return("Value::Undefined");
                self.line(&s);
            }
        }
    }

    fn continue_stmt(&mut self) {
        let pos = self.ctx.iter().rposition(|c| matches!(c, Ctx::Loop(_)));
        match pos {
            Some(p) => {
                let s = self.goto_continue(p);
                self.line(&s);
            }
            None => {
                let s = self.goto_return("Value::Undefined");
                self.line(&s);
            }
        }
    }

    /// Carries out the flow in temp `f` (a `Flow`) where the `try` it left stood.
    fn dispatch_flow(&mut self, f: &str) {
        self.open(&format!("match {f} {{"));
        self.line("Flow::Normal => {}");
        let r = self.goto_return("v");
        self.line(&format!("Flow::Return(v) => {{ {r} }}"));
        let mut breaks = Vec::new();
        let mut conts = Vec::new();
        for (i, c) in self.ctx.iter().enumerate() {
            match c {
                Ctx::Loop(id) => {
                    breaks.push((*id, self.goto_break(i)));
                    conts.push((*id, self.goto_continue(i)));
                }
                Ctx::Switch(id) => breaks.push((*id, self.goto_break(i))),
                Ctx::Try(_) => {}
            }
        }
        self.open("Flow::Break(id) => match id {");
        for (id, s) in breaks {
            self.line(&format!("{id} => {{ {s} }}"));
        }
        self.line("_ => unreachable!(),");
        self.close("},");
        self.open("Flow::Continue(id) => match id {");
        for (id, s) in conts {
            self.line(&format!("{id} => {{ {s} }}"));
        }
        self.line("_ => unreachable!(),");
        self.close("},");
        self.close("}");
    }

    fn stmt(&mut self, s: &Stmt) {
        match s {
            Stmt::Let(p, init) => {
                let v = match init {
                    Some(e) => self.expr(e),
                    None => "Value::Undefined".into(),
                };
                let v = self.bind_tmp(&v);
                self.bind(p, &v);
            }
            Stmt::Expr(e) => {
                let a = self.expr(e);
                self.line(&format!("let _ = {a};"));
            }
            Stmt::If(c, a, b) => {
                let c = self.cond(c);
                self.open(&format!("if {c} {{"));
                self.block(a);
                if b.is_empty() {
                    self.close("}");
                } else {
                    self.indent -= 1;
                    self.line("} else {");
                    self.indent += 1;
                    self.block(b);
                    self.close("}");
                }
            }
            Stmt::Return(e) => {
                let v = match e {
                    Some(e) => self.expr(e),
                    None => "Value::Undefined".into(),
                };
                let s = self.goto_return(&v);
                self.line(&s);
            }
            Stmt::Block(b) => {
                self.open("{");
                self.block(b);
                self.close("}");
            }
            Stmt::ForOf(p, it, body) => {
                let v = self.expr(it);
                let items = self.tmp();
                let e = self.q(&format!("rt.items_of(&{v})"));
                self.line(&format!("let {items} = {e};"));
                let id = self.new_label();
                let x = self.tmp();
                self.open(&format!("'l{id}: for {x} in {items} {{"));
                self.bind(p, &x);
                self.ctx.push(Ctx::Loop(id));
                self.open(&format!("'b{id}: {{"));
                self.block(body);
                self.close("}");
                self.ctx.pop();
                self.close("}");
            }
            Stmt::For {
                init,
                test,
                update,
                body,
            } => {
                self.block(init);
                let id = self.new_label();
                let guard = self.tmp();
                self.line(&format!("let mut {guard}: u64 = 0;"));
                self.open(&format!("'l{id}: loop {{"));
                if let Some(t) = test {
                    let t = self.cond(t);
                    self.line(&format!("if !({t}) {{ break 'l{id}; }}"));
                }
                self.ctx.push(Ctx::Loop(id));
                self.open(&format!("'b{id}: {{"));
                self.block(body);
                self.close("}");
                self.ctx.pop();
                if let Some(u) = update {
                    let a = self.expr(u);
                    self.line(&format!("let _ = {a};"));
                }
                self.line(&format!("{guard} += 1;"));
                let e = self.raise(
                    "Throw::Value(Value::error(\"RangeError\", \"loop did not terminate\"))",
                );
                self.line(&format!("if {guard} > 50_000_000 {{ {e} }}"));
                self.close("}");
            }
            Stmt::Switch(d, cases) => {
                let d = self.expr(d);
                let id = self.new_label();
                let start = self.tmp();
                self.line(&format!("let mut {start}: usize = usize::MAX;"));
                self.open(&format!("'m{id}: {{"));
                for (i, (t, _)) in cases.iter().enumerate() {
                    if let Some(t) = t {
                        let t = self.expr(t);
                        self.line(&format!(
                            "if strict_equals(&{d}, &{t}) {{ {start} = {i}; break 'm{id}; }}"
                        ));
                    }
                }
                if let Some(def) = cases.iter().position(|(t, _)| t.is_none()) {
                    self.line(&format!("{start} = {def};"));
                }
                self.close("}");
                self.ctx.push(Ctx::Switch(id));
                self.open(&format!("'s{id}: {{"));
                for (i, (_, body)) in cases.iter().enumerate() {
                    self.open(&format!("if {start} <= {i} {{"));
                    self.block(body);
                    self.close("}");
                }
                self.close("}");
                self.ctx.pop();
            }
            Stmt::Break => self.break_stmt(),
            Stmt::Continue => self.continue_stmt(),
            Stmt::Throw(e) => {
                let v = self.expr(e);
                let s = self.raise(&format!("Throw::Value({v})"));
                self.line(&s);
            }
            Stmt::Try {
                block,
                param,
                handler,
                finalizer,
            } => {
                let id = self.new_label();
                let r = self.tmp();
                // The block.
                let lt = format!("t{id}");
                self.open(&format!("let {r}: R<Flow> = '{lt}: {{"));
                self.ctx.push(Ctx::Try(lt.clone()));
                self.err.push(ErrTo::Label(lt));
                self.block(block);
                self.err.pop();
                self.ctx.pop();
                self.line("Ok(Flow::Normal)");
                self.close("};");
                // The handler, for a thrown value (not an optional chain's end).
                if let Some(h) = handler {
                    let lh = format!("h{id}");
                    let ex = self.tmp();
                    self.open(&format!("let {r}: R<Flow> = match {r} {{"));
                    self.open(&format!("Err(Throw::Value({ex})) => '{lh}: {{"));
                    self.ctx.push(Ctx::Try(lh.clone()));
                    self.err.push(ErrTo::Label(lh));
                    match param {
                        Some(p) => self.bind(p, &ex),
                        None => self.line(&format!("let _ = {ex};")),
                    }
                    self.block(h);
                    self.err.pop();
                    self.ctx.pop();
                    self.line("Ok(Flow::Normal)");
                    self.close("}");
                    self.line("other => other,");
                    self.close("};");
                }
                // The finaliser: its own abrupt completion wins.
                if let Some(f) = finalizer {
                    let lf = format!("f{id}");
                    let fr = self.tmp();
                    self.open(&format!("let {fr}: R<Flow> = '{lf}: {{"));
                    self.ctx.push(Ctx::Try(lf.clone()));
                    self.err.push(ErrTo::Label(lf));
                    self.block(f);
                    self.err.pop();
                    self.ctx.pop();
                    self.line("Ok(Flow::Normal)");
                    self.close("};");
                    let e = self.q(&fr);
                    let ff = self.bind_tmp(&e);
                    self.dispatch_flow(&ff);
                }
                let e = self.q(&r);
                let rf = self.bind_tmp(&e);
                self.dispatch_flow(&rf);
            }
        }
    }

    // ------------------------------------------------------------ expressions

    /// Evaluates `items` into a new `Vec<Value>` temp.
    fn items(&mut self, items: &[ArrayItem]) -> String {
        let a = self.tmp();
        self.line(&format!(
            "let mut {a}: Vec<Value> = Vec::with_capacity({});",
            items.len()
        ));
        for i in items {
            match i {
                ArrayItem::Item(e) => {
                    let v = self.expr(e);
                    self.line(&format!("{a}.push({v});"));
                }
                ArrayItem::Spread(e) => {
                    let v = self.expr(e);
                    let s = self.q(&format!("rt.spread(&mut {a}, &{v})"));
                    self.line(&format!("{s};"));
                }
            }
        }
        a
    }

    fn short_if_nullish(&mut self, v: &str) {
        let s = self.raise("Throw::Short");
        self.line(&format!("if {v}.is_nullish() {{ {s} }}"));
    }

    /// Generates `e`, returning an atom: a temp or a constant expression, used once.
    fn expr(&mut self, e: &Expr) -> String {
        match e {
            Expr::Undefined => "Value::Undefined".into(),
            Expr::Null => "Value::Null".into(),
            Expr::Bool(b) => format!("Value::Bool({b})"),
            Expr::Num(n) => format!("Value::Num({})", num_lit(*n)),
            Expr::Str(s) => self.str_value(s),
            Expr::Local(n) => {
                let r = self.local_read(*n);
                self.bind_tmp(&r)
            }
            Expr::Capture(n) => {
                let r = self.capture_read(*n);
                self.bind_tmp(&r)
            }
            Expr::Global(n) => self.bind_tmp(&format!("rt.global({n})")),
            Expr::Template(quasis, exprs) => {
                let s = self.tmp();
                self.line(&format!("let mut {s} = String::new();"));
                for (i, q) in quasis.iter().enumerate() {
                    if !q.is_empty() {
                        self.line(&format!("{s}.push_str({});", str_lit(q)));
                    }
                    if let Some(e) = exprs.get(i) {
                        let v = self.expr(e);
                        self.line(&format!("{s}.push_str(&{v}.to_js_string());"));
                    }
                }
                self.bind_tmp(&format!("Value::str(&{s})"))
            }
            Expr::Array(items) => {
                let a = self.items(items);
                self.bind_tmp(&format!("Value::array({a})"))
            }
            Expr::Object(props) => {
                let o = self.tmp();
                self.line(&format!(
                    "let mut {o}: Vec<(Str, Value)> = Vec::with_capacity({});",
                    props.len()
                ));
                for p in props {
                    match p {
                        Prop::KeyValue(k, v) => {
                            let v = self.expr(v);
                            let k = self.key_str(k);
                            self.line(&format!("obj_put_str(&mut {o}, {k}, {v});"));
                        }
                        Prop::Computed(k, v) => {
                            let k = self.expr(k);
                            let v = self.expr(v);
                            self.line(&format!("obj_put_key(&mut {o}, &{k}, {v});"));
                        }
                        Prop::Spread(v) => {
                            let v = self.expr(v);
                            self.line(&format!("obj_spread(&mut {o}, &{v});"));
                        }
                    }
                }
                self.bind_tmp(&format!("Value::object({o})"))
            }
            Expr::Member(o, name, optional) => {
                let o = self.operand(o, &[]);
                if *optional {
                    self.short_if_nullish(&o);
                }
                let e = self.q(&format!("rt.member(&{o}, {})", str_lit(name)));
                self.bind_tmp(&e)
            }
            Expr::Index(o, k, optional) => {
                let o = self.operand(o, &[k]);
                if *optional {
                    self.short_if_nullish(&o);
                }
                let k = self.operand(k, &[]);
                let e = self.q(&format!("rt.index(&{o}, &{k})"));
                self.bind_tmp(&e)
            }
            Expr::Call(f, args, optional) => {
                if let (Expr::Global(g), false) = (&**f, optional) {
                    if let Some(Some(fi)) = self.g.direct.get(*g as usize) {
                        let fi = *fi;
                        let a = self.items(args);
                        let e = self.q(&format!("f{fi}(rt, &[], {a}, None)"));
                        return self.bind_tmp(&e);
                    }
                }
                let f = self.expr(f);
                if *optional {
                    self.short_if_nullish(&f);
                }
                let a = self.items(args);
                let e = self.q(&format!("rt.call(&{f}, {a})"));
                self.bind_tmp(&e)
            }
            Expr::Method {
                recv,
                method,
                args,
                optional,
            } => {
                let later: Vec<&Expr> = args
                    .iter()
                    .map(|a| match a {
                        ArrayItem::Item(e) | ArrayItem::Spread(e) => e,
                    })
                    .collect();
                let r = self.operand(recv, &later);
                if *optional {
                    self.short_if_nullish(&r);
                }
                let a = self.items(args);
                let e = self.q(&format!("rt.call_method(&{r}, Method::{method:?}, {a})"));
                self.bind_tmp(&e)
            }
            Expr::BuiltinFn(b) => self.bind_tmp(&format!("builtin_fn(Builtin::{b:?})")),
            Expr::Invoke {
                recv,
                name,
                args,
                optional,
            } => {
                let later: Vec<&Expr> = args
                    .iter()
                    .map(|a| match a {
                        ArrayItem::Item(e) | ArrayItem::Spread(e) => e,
                    })
                    .collect();
                let r = self.operand(recv, &later);
                if *optional {
                    self.short_if_nullish(&r);
                }
                let a = self.items(args);
                let e = self.q(&format!("rt.invoke(&{r}, {}, {a})", str_lit(name)));
                self.bind_tmp(&e)
            }
            Expr::Builtin(b, args) => {
                let a = self.items(args);
                let e = self.q(&format!("rt.call_builtin(Builtin::{b:?}, {a})"));
                self.bind_tmp(&e)
            }
            Expr::Unary(UnaryOp::Not, x) => {
                let c = self.cond(x);
                self.bind_tmp(&format!("Value::Bool(!({c}))"))
            }
            Expr::Unary(op, x) => {
                let v = self.expr(x);
                match op {
                    UnaryOp::Not => unreachable!(),
                    UnaryOp::Neg => self.bind_tmp(&format!("Value::Num(-{v}.to_number())")),
                    UnaryOp::Plus => self.bind_tmp(&format!("Value::Num({v}.to_number())")),
                    UnaryOp::BitNot => {
                        self.bind_tmp(&format!("Value::Num(!to_int32({v}.to_number()) as f64)"))
                    }
                    UnaryOp::Void => {
                        self.line(&format!("let _ = {v};"));
                        "Value::Undefined".into()
                    }
                }
            }
            Expr::TypeOf(x) => {
                let v = self.expr(x);
                self.bind_tmp(&format!("Value::str({v}.type_of())"))
            }
            Expr::Binary(op, a, b) => {
                if let Some(c) = self.binary_bool(*op, a, b) {
                    return self.bind_tmp(&format!("Value::Bool({c})"));
                }
                use BinaryOp as B;
                match (op, &**a, &**b) {
                    (B::Add, Expr::Str(l), _) => {
                        let y = self.operand(b, &[]);
                        return self.bind_tmp(&format!("add_str_left({}, &{y})", str_lit(l)));
                    }
                    (B::Add, _, Expr::Str(l)) => {
                        let x = self.operand(a, &[]);
                        return self.bind_tmp(&format!("add_str_right(&{x}, {})", str_lit(l)));
                    }
                    (B::Sub | B::Mul | B::Div | B::Rem, _, Expr::Num(n)) => {
                        let x = self.operand(a, &[]);
                        let sym = arith_sym(*op);
                        return self.bind_tmp(&format!(
                            "Value::Num({x}.to_number() {sym} {})",
                            num_lit(*n)
                        ));
                    }
                    (B::Sub | B::Mul | B::Div | B::Rem, Expr::Num(n), _) => {
                        let y = self.operand(b, &[]);
                        let sym = arith_sym(*op);
                        return self.bind_tmp(&format!(
                            "Value::Num({} {sym} {y}.to_number())",
                            num_lit(*n)
                        ));
                    }
                    _ => {}
                }
                let x = self.operand(a, &[b]);
                let y = self.operand(b, &[]);
                self.binary(*op, &x, &y)
            }
            Expr::Logical(op, a, b) => {
                let a = self.expr(a);
                let t = self.tmp();
                let cond = match op {
                    LogicalOp::And => format!("{a}.truthy()"),
                    LogicalOp::Or => format!("!{a}.truthy()"),
                    LogicalOp::Nullish => format!("{a}.is_nullish()"),
                };
                self.open(&format!("let {t} = if {cond} {{"));
                let v = self.expr(b);
                self.line(&v);
                self.close(&format!("}} else {{ {a} }};"));
                t
            }
            Expr::Cond(c, a, b) => {
                let c = self.cond(c);
                let t = self.tmp();
                self.open(&format!("let {t} = if {c} {{"));
                let v = self.expr(a);
                self.line(&v);
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                let v = self.expr(b);
                self.line(&v);
                self.close("};");
                t
            }
            Expr::Assign(lv, op, v) => match op {
                None => {
                    let v = self.expr(v);
                    let v = self.bind_tmp(&v);
                    self.write_lvalue(lv, &format!("{v}.clone()"));
                    v
                }
                Some(op) => {
                    let cur = self.read_lvalue(lv);
                    let rhs = self.expr(v);
                    let new = self.binary(*op, &cur, &rhs);
                    self.write_lvalue(lv, &format!("{new}.clone()"));
                    new
                }
            },
            Expr::Update(lv, prefix, delta) => {
                let cur = self.read_lvalue(lv);
                let c = self.bind_tmp(&format!("{cur}.to_number()"));
                let n = self.bind_tmp(&format!("{c} + {}", num_lit(*delta)));
                self.write_lvalue(lv, &format!("Value::Num({n})"));
                self.bind_tmp(&format!("Value::Num({})", if *prefix { &n } else { &c }))
            }
            Expr::Closure(f) => {
                let caps: Vec<String> = self
                    .g
                    .m
                    .functions
                    .get(*f as usize)
                    .map(|func| func.captures.iter().map(|c| self.slot_raw(c)).collect())
                    .unwrap_or_default();
                self.bind_tmp(&format!("closure({f}, vec![{}])", caps.join(", ")))
            }
            Expr::Hook(h, args) => self.hook(*h, args),
            Expr::Element(el) => self.element(el),
            Expr::Seq(xs) => {
                let mut last = "Value::Undefined".to_owned();
                for (i, x) in xs.iter().enumerate() {
                    let v = self.expr(x);
                    if i + 1 == xs.len() {
                        last = v;
                    } else {
                        self.line(&format!("let _ = {v};"));
                    }
                }
                last
            }
            Expr::Regex(p, f) => {
                let e = self.q(&format!("rt.regex({}, {})", str_lit(p), str_lit(f)));
                self.bind_tmp(&e)
            }
            Expr::Await(_) => {
                let s = self.raise(
                    "Throw::Value(Value::error(\"SyntaxError\", \"await is only valid in an async function\"))",
                );
                self.line(&s);
                "Value::Undefined".into()
            }
            Expr::Chain(x) => {
                let id = self.new_label();
                let l = format!("c{id}");
                let r = self.tmp();
                self.open(&format!("let {r}: R<Value> = '{l}: {{"));
                self.err.push(ErrTo::Label(l));
                let v = self.expr(x);
                self.err.pop();
                self.line(&format!("Ok({v})"));
                self.close("};");
                let t = self.tmp();
                let e = self.q("other");
                self.line(&format!(
                    "let {t} = match {r} {{ Err(Throw::Short) => Value::Undefined, other => {e} }};"
                ));
                t
            }
        }
    }

    fn binary(&mut self, op: BinaryOp, a: &str, b: &str) -> String {
        use BinaryOp as B;
        let e = match op {
            B::Add => format!("add(&{a}, &{b})"),
            B::Sub => format!("Value::Num({a}.to_number() - {b}.to_number())"),
            B::Mul => format!("Value::Num({a}.to_number() * {b}.to_number())"),
            B::Div => format!("Value::Num({a}.to_number() / {b}.to_number())"),
            B::Rem => format!("Value::Num({a}.to_number() % {b}.to_number())"),
            B::StrictEq => format!("Value::Bool(strict_equals(&{a}, &{b}))"),
            B::StrictNotEq => format!("Value::Bool(!strict_equals(&{a}, &{b}))"),
            B::Eq => format!("Value::Bool(loose_equals(&{a}, &{b}))"),
            B::NotEq => format!("Value::Bool(!loose_equals(&{a}, &{b}))"),
            B::Lt | B::LtEq | B::Gt | B::GtEq => {
                format!("Value::Bool(compare(BinaryOp::{op:?}, &{a}, &{b}))")
            }
            _ => self.q(&format!("rt.op(BinaryOp::{op:?}, &{a}, &{b})")),
        };
        self.bind_tmp(&e)
    }

    /// Reads an assignment target (evaluating its object and key).
    fn read_lvalue(&mut self, lv: &LValue) -> String {
        match lv {
            LValue::Local(n) => {
                let r = self.local_read(*n);
                self.bind_tmp(&r)
            }
            LValue::Capture(n) => {
                let r = self.capture_read(*n);
                self.bind_tmp(&r)
            }
            LValue::Global(n) => self.bind_tmp(&format!("rt.global({n})")),
            LValue::Member(o, k) => {
                let o = self.expr(o);
                let e = self.q(&format!("rt.member(&{o}, {})", str_lit(k)));
                self.bind_tmp(&e)
            }
            LValue::Index(o, k) => {
                let o = self.expr(o);
                let k = self.expr(k);
                let e = self.q(&format!("rt.index(&{o}, &{k})"));
                self.bind_tmp(&e)
            }
        }
    }

    /// Writes `v` (an expression) to an assignment target (evaluating its object and
    /// key again, as the interpreter does).
    fn write_lvalue(&mut self, lv: &LValue, v: &str) {
        match lv {
            LValue::Local(n) => {
                if self.boxed.get(*n as usize) == Some(&true) {
                    self.line(&format!("write_slot(&mut l{n}, {v});"));
                } else {
                    self.line(&format!("l{n} = {v};"));
                }
            }
            LValue::Capture(n) => {
                let e = self.q(&format!("write_capture(&cap[{n}], {v})"));
                self.line(&format!("{e};"));
            }
            LValue::Global(n) => self.line(&format!("rt.set_global({n}, {v});")),
            LValue::Member(o, k) => {
                let o = self.expr(o);
                let x = self.bind_tmp(v);
                let e = self.q(&format!("rt.put_member(&{o}, {}, {x})", str_lit(k)));
                self.line(&format!("{e};"));
            }
            LValue::Index(o, k) => {
                let o = self.expr(o);
                let k = self.expr(k);
                let x = self.bind_tmp(v);
                let e = self.q(&format!("rt.put_index(&{o}, &{k}, {x})"));
                self.line(&format!("{e};"));
            }
        }
    }

    fn hook(&mut self, h: Hook, args: &[Expr]) -> String {
        let t = self.tmp();
        if args.is_empty() {
            let e = self.q(&format!(
                "rt.hook_with(Hook::{h:?}, 0, &mut |_: &mut Runtime, _: usize| Ok(Value::Undefined))"
            ));
            self.line(&format!("let {t} = {e};"));
            return t;
        }
        let r = self.tmp();
        self.open(&format!(
            "let {r} = rt.hook_with(Hook::{h:?}, {}, &mut |rt: &mut Runtime, i: usize| -> R<Value> {{",
            args.len()
        ));
        self.err.push(ErrTo::Fn);
        let saved_ctx = std::mem::take(&mut self.ctx);
        self.open("match i {");
        for (i, a) in args.iter().enumerate() {
            self.open(&format!("{i} => {{"));
            let v = self.expr(a);
            self.line(&format!("Ok({v})"));
            self.close("}");
        }
        self.line("_ => Ok(Value::Undefined),");
        self.close("}");
        self.ctx = saved_ctx;
        self.err.pop();
        self.close("});");
        let e = self.q(&r);
        self.line(&format!("let {t} = {e};"));
        t
    }

    fn key(&mut self, key: &Option<Expr>) -> String {
        match key {
            Some(k) => {
                let v = self.expr(k);
                self.bind_tmp(&format!("key_of(&{v})"))
            }
            None => "None".into(),
        }
    }

    fn element(&mut self, el: &ElementExpr) -> String {
        match el {
            ElementExpr::Template {
                template,
                holes,
                key,
            } => {
                let key = self.key(key);
                let site = self.site_next;
                self.site_next += 1;
                let slot = self.sites;
                self.sites += 1;
                let meta = &self.g.m.templates[*template as usize].holes;
                let caching = self.tmp();
                self.line(&format!(
                    "let {caching} = inst.is_some() && rt.is_pure_render();"
                ));
                let n = self.tmp();
                self.line(&format!(
                    "let {n} = if {caching} {{ occ[{slot}] += 1; occ[{slot}] }} else {{ 0 }};"
                ));
                let b = self.tmp();
                self.line(&format!(
                    "let mut {b} = rt.tpl_begin({caching}, {site}, {n}, {template}, {});",
                    holes.len()
                ));
                // Every hole reading the same slots: one comparison decides them all.
                let shared = match meta.first() {
                    Some(first) if !first.deps.is_empty() => meta
                        .iter()
                        .all(|h| !h.always && h.deps == first.deps)
                        .then(|| first.deps.clone()),
                    _ => None,
                };
                let result = self.tmp();
                if let Some(deps) = &shared {
                    let d = self.tmp();
                    let reads: Vec<String> = deps.iter().map(|c| self.slot_value(c)).collect();
                    self.line(&format!(
                        "let {d}: Vec<Value> = if {b}.caching() {{ vec![{}] }} else {{ Vec::new() }};",
                        reads.join(", ")
                    ));
                    self.open(&format!(
                        "let {result} = if rt.tpl_reuse_all(&mut {b}, &{d}) {{"
                    ));
                    self.line(&format!("rt.tpl_finish({b}, {key})"));
                    self.indent -= 1;
                    self.line("} else {");
                    self.indent += 1;
                } else {
                    self.open(&format!("let {result} = {{"));
                }
                for (i, h) in holes.iter().enumerate() {
                    let (deps, always) = meta
                        .get(i)
                        .map(|m| (m.deps.clone(), m.always))
                        .unwrap_or_default();
                    let d = self.tmp();
                    if deps.is_empty() {
                        self.line(&format!("let {d}: Vec<Value> = Vec::new();"));
                    } else {
                        let reads: Vec<String> = deps.iter().map(|c| self.slot_value(c)).collect();
                        self.line(&format!(
                            "let {d}: Vec<Value> = if {b}.caching() {{ vec![{}] }} else {{ Vec::new() }};",
                            reads.join(", ")
                        ));
                    }
                    self.open(&format!("match rt.tpl_reuse(&{b}, {i}, {always}, &{d}) {{"));
                    self.line(&format!("Some(v) => rt.tpl_push(&mut {b}, v, {d}, false),"));
                    self.open("None => {");
                    let v = self.expr(h);
                    self.line(&format!("rt.tpl_push(&mut {b}, {v}, {d}, true);"));
                    self.close("}");
                    self.close("}");
                }
                self.line(&format!("rt.tpl_finish({b}, {key})"));
                self.close("};");
                result
            }
            ElementExpr::Component {
                callee,
                props,
                children,
                key,
            } => {
                let f = self.expr(callee);
                let e = self.q(&format!("component_callee({f})"));
                let func = self.bind_tmp(&e);
                let p = self.tmp();
                self.line(&format!(
                    "let mut {p}: Vec<(Str, Value)> = Vec::with_capacity({});",
                    props.len() + 1
                ));
                for pr in props {
                    match pr {
                        Prop::KeyValue(k, v) => {
                            let v = self.expr(v);
                            let k = self.key_str(k);
                            self.line(&format!("obj_put_str(&mut {p}, {k}, {v});"));
                        }
                        Prop::Computed(k, v) => {
                            let k = self.expr(k);
                            let v = self.expr(v);
                            self.line(&format!("obj_put_key(&mut {p}, &{k}, {v});"));
                        }
                        Prop::Spread(v) => {
                            let v = self.expr(v);
                            self.line(&format!("props_spread(&mut {p}, &{v});"));
                        }
                    }
                }
                let c = match children {
                    Some(c) => {
                        let v = self.expr(c);
                        format!("Some({v})")
                    }
                    None => "None".into(),
                };
                let c = self.bind_tmp(&c);
                let key = self.key(key);
                self.bind_tmp(&format!("component_elem({func}, {p}, {c}, {key})"))
            }
            ElementExpr::Fragment { children, key } => {
                let c = self.tmp();
                self.line(&format!(
                    "let mut {c}: Vec<Value> = Vec::with_capacity({});",
                    children.len()
                ));
                for x in children {
                    let v = self.expr(x);
                    self.line(&format!("{c}.push({v});"));
                }
                let key = self.key(key);
                self.bind_tmp(&format!("fragment({c}, {key})"))
            }
            ElementExpr::Provider {
                context,
                value,
                children,
                key,
            } => {
                let ctx = self.expr(context);
                let e = self.q(&format!("provider_context({ctx})"));
                let ctx = self.bind_tmp(&e);
                let v = self.expr(value);
                let v = self.bind_tmp(&v);
                let c = self.tmp();
                self.line(&format!(
                    "let mut {c}: Vec<Value> = Vec::with_capacity({});",
                    children.len()
                ));
                for x in children {
                    let a = self.expr(x);
                    self.line(&format!("{c}.push({a});"));
                }
                let key = self.key(key);
                self.bind_tmp(&format!("provider({ctx}, {v}, {c}, {key})"))
            }
        }
    }
}

fn arith_sym(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        _ => "%",
    }
}

/// Whether evaluating `e` can assign local slot `n` (only an assignment or an
/// update in this function can: a callee sees a slot only through its cell, and a
/// boxed slot is never borrowed in place).
fn writes_local(e: &Expr, n: u32) -> bool {
    let mut found = false;
    walk(e, &mut |x| {
        if let Expr::Assign(lv, _, _) | Expr::Update(lv, _, _) = x {
            if matches!(**lv, LValue::Local(m) if m == n) {
                found = true;
            }
        }
    });
    found
}

// ---------------------------------------------------------------- IR walks

fn walk_pattern(p: &Pattern, f: &mut impl FnMut(&Expr)) {
    match p {
        Pattern::Default(inner, d) => {
            walk(d, f);
            walk_pattern(inner, f);
        }
        Pattern::Array { items, rest } => {
            for p in items.iter().flatten() {
                walk_pattern(p, f);
            }
            if let Some(r) = rest {
                walk_pattern(r, f);
            }
        }
        Pattern::Object { props, rest } => {
            for (_, p) in props {
                walk_pattern(p, f);
            }
            if let Some(r) = rest {
                walk_pattern(r, f);
            }
        }
        _ => {}
    }
}

fn walk_stmts(stmts: &[Stmt], f: &mut impl FnMut(&Expr)) {
    for s in stmts {
        match s {
            Stmt::Let(p, e) => {
                walk_pattern(p, f);
                if let Some(e) = e {
                    walk(e, f);
                }
            }
            Stmt::Expr(e) | Stmt::Throw(e) => walk(e, f),
            Stmt::Return(e) => {
                if let Some(e) = e {
                    walk(e, f);
                }
            }
            Stmt::If(c, a, b) => {
                walk(c, f);
                walk_stmts(a, f);
                walk_stmts(b, f);
            }
            Stmt::ForOf(p, e, b) => {
                walk_pattern(p, f);
                walk(e, f);
                walk_stmts(b, f);
            }
            Stmt::For {
                init,
                test,
                update,
                body,
            } => {
                walk_stmts(init, f);
                if let Some(t) = test {
                    walk(t, f);
                }
                if let Some(u) = update {
                    walk(u, f);
                }
                walk_stmts(body, f);
            }
            Stmt::Switch(d, cases) => {
                walk(d, f);
                for (t, b) in cases {
                    if let Some(t) = t {
                        walk(t, f);
                    }
                    walk_stmts(b, f);
                }
            }
            Stmt::Block(b) => walk_stmts(b, f),
            Stmt::Try {
                block,
                param,
                handler,
                finalizer,
            } => {
                walk_stmts(block, f);
                if let Some(p) = param {
                    walk_pattern(p, f);
                }
                if let Some(h) = handler {
                    walk_stmts(h, f);
                }
                if let Some(x) = finalizer {
                    walk_stmts(x, f);
                }
            }
            Stmt::Break | Stmt::Continue => {}
        }
    }
}

fn walk(e: &Expr, f: &mut impl FnMut(&Expr)) {
    f(e);
    fn items(xs: &[ArrayItem], f: &mut impl FnMut(&Expr)) {
        for i in xs {
            match i {
                ArrayItem::Item(e) | ArrayItem::Spread(e) => walk(e, f),
            }
        }
    }
    fn props(ps: &[Prop], f: &mut impl FnMut(&Expr)) {
        for p in ps {
            match p {
                Prop::KeyValue(_, v) | Prop::Spread(v) => walk(v, f),
                Prop::Computed(k, v) => {
                    walk(k, f);
                    walk(v, f);
                }
            }
        }
    }
    fn lvalue(lv: &LValue, f: &mut impl FnMut(&Expr)) {
        match lv {
            LValue::Member(o, _) => walk(o, f),
            LValue::Index(o, k) => {
                walk(o, f);
                walk(k, f);
            }
            _ => {}
        }
    }
    match e {
        Expr::Template(_, es) | Expr::Seq(es) | Expr::Hook(_, es) => {
            for e in es {
                walk(e, f);
            }
        }
        Expr::Array(xs) | Expr::Builtin(_, xs) => items(xs, f),
        Expr::Object(ps) => props(ps, f),
        Expr::Member(o, _, _)
        | Expr::Unary(_, o)
        | Expr::TypeOf(o)
        | Expr::Chain(o)
        | Expr::Await(o) => walk(o, f),
        Expr::Index(o, k, _) => {
            walk(o, f);
            walk(k, f);
        }
        Expr::Call(c, args, _) => {
            walk(c, f);
            items(args, f);
        }
        Expr::Method { recv, args, .. } | Expr::Invoke { recv, args, .. } => {
            walk(recv, f);
            items(args, f);
        }
        Expr::Binary(_, a, b) | Expr::Logical(_, a, b) => {
            walk(a, f);
            walk(b, f);
        }
        Expr::Cond(a, b, c) => {
            walk(a, f);
            walk(b, f);
            walk(c, f);
        }
        Expr::Assign(lv, _, v) => {
            lvalue(lv, f);
            walk(v, f);
        }
        Expr::Update(lv, _, _) => lvalue(lv, f),
        Expr::Element(el) => match &**el {
            ElementExpr::Template { holes, key, .. } => {
                for h in holes {
                    walk(h, f);
                }
                if let Some(k) = key {
                    walk(k, f);
                }
            }
            ElementExpr::Component {
                callee,
                props: ps,
                children,
                key,
            } => {
                walk(callee, f);
                props(ps, f);
                if let Some(c) = children {
                    walk(c, f);
                }
                if let Some(k) = key {
                    walk(k, f);
                }
            }
            ElementExpr::Fragment { children, key } => {
                for c in children {
                    walk(c, f);
                }
                if let Some(k) = key {
                    walk(k, f);
                }
            }
            ElementExpr::Provider {
                context,
                value,
                children,
                key,
            } => {
                walk(context, f);
                walk(value, f);
                for c in children {
                    walk(c, f);
                }
                if let Some(k) = key {
                    walk(k, f);
                }
            }
        },
        _ => {}
    }
}
