use super::*;
use crate::check;

check!(computed_style_basic, "<style>#d { color: rgb(1, 2, 3); width: 50px; display: block; margin: 4px 8px }</style><div id=d></div>", "const cs=getComputedStyle(document.getElementById('d')); console.log(cs.color, cs.width, cs.display, cs.getPropertyValue('margin-left'), cs.marginLeft, cs.margin, cs['margin-top'], cs.length>50, typeof cs.item(0), cs instanceof CSSStyleDeclaration, cs.getPropertyValue('nope'), cs.position, cs.fontSize); try { cs.color='red' } catch(e) { console.log(e.name) } cs.setProperty; console.log(cs.getPropertyPriority('color'), cs.cssText);", "rgb(1, 2, 3) 50px block 8px 8px 4px 8px 4px true string true  static 16px\n ");
check!(computed_style_inherits_and_pseudo, "<style>#p { font-size: 20px } #p::before { content: 'x'; color: rgb(9, 9, 9) }</style><p id=p><span id=s>t</span></p>", "console.log(getComputedStyle(document.getElementById('s')).fontSize, getComputedStyle(document.getElementById('p'), '::before').color, getComputedStyle(document.getElementById('p'), ':before').content, getComputedStyle(document.getElementById('p'), '::after').content);", "20px rgb(9, 9, 9) \"x\" ");
check!(computed_style_follows_class_change, "<style>.red { color: rgb(255, 0, 0) } .big { font-size: 30px }</style><div id=d class=red></div>", "const d=document.getElementById('d'); const cs=getComputedStyle(d); console.log(cs.color); d.classList.replace('red','big'); console.log(cs.color, cs.fontSize); d.style.color='rgb(0, 0, 255)'; console.log(cs.color); d.setAttribute('style',''); console.log(cs.color);", "rgb(255, 0, 0)\nrgb(0, 0, 0) 30px\nrgb(0, 0, 255)\nrgb(0, 0, 0)");
check!(computed_style_custom_property, "<style>:root { --gap: 12px } #d { padding-left: var(--gap) }</style><div id=d></div>", "const cs=getComputedStyle(document.getElementById('d')); console.log(cs.paddingLeft, cs.getPropertyValue('--gap').trim(), getComputedStyle(document.documentElement).getPropertyValue('--gap').trim()); document.documentElement.style.setProperty('--gap', '3px'); console.log(cs.paddingLeft);", "12px 12px 12px\n3px");
check!(style_sheets_list, "<style id=a>p{color:red}</style><style id=b media=print>q{}</style><link rel=stylesheet href=/s.css>", "const l=document.styleSheets; console.log(l.length, l[0] instanceof CSSStyleSheet, l[0].ownerNode.id, l.item(1).media.mediaText, l[2].href, l[0].href, l[0].type, l[0].disabled, l[0].cssRules.length, l[0].cssRules[0].selectorText, l[0].cssRules[0].style.color, l[0].cssRules[0].type, l[0].cssRules[0] instanceof CSSStyleRule, l[0].cssRules[0].parentStyleSheet===l[0], l[0].rules===l[0].cssRules||l[0].rules.length===1, l instanceof StyleSheetList, document.getElementById('a').sheet===l[0]);", "3 true a print https://example.test/s.css null text/css false 1 p red 1 true true true true true");
check!(insert_rule_restyles, "<style id=s>#d { color: red }</style><div id=d></div>", "const sh=document.getElementById('s').sheet; const cs=getComputedStyle(document.getElementById('d')); console.log(cs.color); const i=sh.insertRule('#d { color: blue; font-weight: bold }', 1); console.log(i, sh.cssRules.length, cs.color, cs.fontWeight, sh.cssRules[1].cssText); sh.deleteRule(0); console.log(sh.cssRules.length, cs.color); sh.cssRules[0].style.color='green'; console.log(cs.color, sh.cssRules[0].style.cssText); sh.cssRules[0].style.setProperty('color','purple'); sh.cssRules[0].style.removeProperty('font-weight'); console.log(cs.color, cs.fontWeight); sh.cssRules[0].selectorText='#zz'; console.log(cs.color, sh.cssRules[0].selectorText); try { sh.insertRule('#a{}', 9) } catch(e) { console.log(e.name) } try { sh.insertRule('garbage', 0) } catch(e) { console.log(e.name) }", "rgb(255, 0, 0)\n1 2 rgb(0, 0, 255) 700 #d { color: blue; font-weight: bold; }\n1 rgb(0, 0, 255)\nrgb(0, 128, 0) color: green; font-weight: bold;\nrgb(128, 0, 128) 400\nrgb(0, 0, 0) #zz\nIndexSizeError\nSyntaxError");
check!(grouping_rules, "<style id=s>@import url(x.css); @media screen and (min-width: 100px) { p { color: red } } @supports (display: grid) { q { x: 1 } } @font-face { font-family: F; src: url(f.woff) } @keyframes k { from { opacity: 0 } 50% { opacity: 0.5 } to { opacity: 1 } } @layer base { a { color: blue } } @page { margin: 1in } @layer x, y;</style>", "const r=document.getElementById('s').sheet.cssRules; const types=[]; for (const x of r) types.push(x.type + ':' + x.constructor.name); console.log(types.join()); const m=r[1]; console.log(m.conditionText, m.media.mediaText, m.cssRules.length, m.cssRules[0].selectorText, m.cssRules[0].parentRule===m, m.cssText.replace(/\\n/g,' ')); console.log(r[2].conditionText, r[2].cssRules[0].cssText); console.log(r[0].href, r[3].style.fontFamily, r[4].name, r[4].cssRules.length, r[4].cssRules[1].keyText, r[4].findRule('to').style.getPropertyValue('opacity'), r[5].name, r[5].cssRules[0].selectorText, r[6].cssText, r[7].nameList.join()); m.insertRule('b { color: green }', 1); m.deleteRule(0); console.log(m.cssRules.length, m.cssRules[0].selectorText);", "3:CSSImportRule,4:CSSMediaRule,12:CSSSupportsRule,5:CSSFontFaceRule,7:CSSKeyframesRule,0:CSSLayerBlockRule,6:CSSPageRule,0:CSSLayerStatementRule\nscreen and (min-width: 100px) screen and (min-width: 100px) 1 p true @media screen and (min-width: 100px) {   p { color: red; } }\n(display: grid) q { x: 1; }\nx.css F k 3 50% 1 base a @page { margin: 1in; } x,y\n1 b");
check!(constructed_sheets, "<div id=d></div>", "const s=new CSSStyleSheet(); s.replaceSync('#d { color: red }'); console.log(s.cssRules.length, getComputedStyle(d).color, document.adoptedStyleSheets.length); document.adoptedStyleSheets=[s]; console.log(getComputedStyle(d).color, document.adoptedStyleSheets.length, document.adoptedStyleSheets[0]===s); s.replace('#d { color: blue }').then(x=>console.log('replaced', x===s, getComputedStyle(d).color)); s.insertRule('#d { font-size: 40px }'); console.log(getComputedStyle(d).fontSize); s.disabled=true; console.log(getComputedStyle(d).fontSize, s.disabled); s.disabled=false; document.adoptedStyleSheets=[]; console.log(getComputedStyle(d).fontSize); try { document.adoptedStyleSheets=[document.styleSheets[0] || {}] } catch(e) { console.log(e.name) } try { document.styleSheets.length && document.styleSheets[0].replaceSync('') } catch(e) { console.log(e.name) }", "1 rgb(0, 0, 0) 0\nrgb(255, 0, 0) 1 true\n40px\n16px true\n16px\nNotAllowedError\nreplaced true rgb(0, 0, 0)");
check!(style_element_text_change_restyles, "<style id=s>#d { color: red }</style><div id=d></div>", "const cs=getComputedStyle(d); console.log(cs.color); s.textContent='#d { color: blue }'; console.log(cs.color); s.remove(); console.log(cs.color); const n=document.createElement('style'); n.textContent='#d { color: green }'; document.head.appendChild(n); console.log(cs.color, document.styleSheets.length); n.disabled=true; console.log(cs.color);", "rgb(255, 0, 0)\nrgb(0, 0, 255)\nrgb(0, 0, 0)\nrgb(0, 128, 0) 1\nrgb(0, 128, 0)");
check!(link_sheet_fetched, "<link id=l rel=stylesheet href=/s.css><div id=d></div>", "console.log(getComputedStyle(d).color, document.styleSheets[0].href, document.styleSheets[0].cssRules[0].cssText);", "rgb(255, 0, 0) https://example.test/s.css #d { color: red; }");
check!(css_namespace, "", "console.log(CSS.supports('display', 'flex'), CSS.supports('display', 'bogus'), CSS.supports('(display: grid)'), CSS.supports('(color: red) and (bogus: 1)'), CSS.supports('not (bogus: 1)'), CSS.escape('a b.c'), CSS.escape('1x'), CSS.escape('-'), typeof CSS.px(3), CSS.px(3)+'');", "true false true false true a\\ b\\.c \\31 x \\- object 3px");
check!(match_media, "", "const m=matchMedia('(min-width: 500px)'); console.log(m.matches, m.media, m instanceof MediaQueryList, matchMedia('(max-width: 100px)').matches, matchMedia('screen').matches, matchMedia('print').matches, matchMedia('(prefers-color-scheme: dark)').matches, matchMedia('(hover: hover)').matches, matchMedia('all and (min-width:1px)').media); let n=0; m.addListener(()=>n++); m.onchange=()=>n+=10; console.log(n);", "true (min-width: 500px) true false true false false true (min-width: 1px)\n0");
check!(inline_style_camel_and_important, "<div id=d></div>", "d.style.setProperty('color','red','important'); d.style.WebkitTransition='none'; d.style.borderTopLeftRadius='3px'; d.style.zIndex=5; d.style.opacity=0.5; d.style.width='calc(100% - 10px)'; d.style.bogusProp='x'; console.log(d.getAttribute('style'), d.style.zIndex, d.style.opacity, d.style.width, d.style.bogusProp);", "color: red !important; -webkit-transition: none; border-top-left-radius: 3px; z-index: 5; opacity: 0.5; width: calc(100% - 10px); 5 0.5 calc(100% - 10px) x");
check!(inline_style_invalid_value_ignored, "<div id=d style='color: red'></div>", "d.style.color='not a color'; d.style.width='garbage'; console.log(d.style.color, d.style.width, d.getAttribute('style')); d.style.color=null; console.log(JSON.stringify(d.style.cssText));", "red  color: red\n\"\"");
check!(style_property_enumeration, "<div id=d style='top: 1px; left: 2px'></div>", "console.log(Object.keys(d.style).join(), [...d.style].join(), 'top' in d.style, d.style.length, d.style[1]);", "0,1 top,left true 2 left");
check!(document_style_sheets_live, "", "console.log(document.styleSheets.length); const s=document.createElement('style'); document.head.appendChild(s); console.log(document.styleSheets.length, s.sheet.cssRules.length); s.sheet.insertRule('body { margin: 0 }', 0); console.log(s.sheet.cssRules[0].cssText, getComputedStyle(document.body).marginTop);", "0\n1 0\nbody { margin: 0; } 0px");
check!(target_pseudo_and_hash, "<style>#t:target { color: rgb(1, 1, 1) }</style><div id=t></div>", "console.log(getComputedStyle(t).color); location.hash='#t'; console.log(getComputedStyle(t).color, location.hash, t.matches(':target')); location.hash=''; console.log(getComputedStyle(t).color);", "rgb(0, 0, 0)\nrgb(1, 1, 1) #t true\nrgb(0, 0, 0)");
check!(hover_focus_styles_via_state, "<style>#i:focus { color: rgb(5, 5, 5) }</style><input id=i>", "console.log(getComputedStyle(i).color); i.focus(); console.log(getComputedStyle(i).color); i.blur(); console.log(getComputedStyle(i).color);", "rgb(0, 0, 0)\nrgb(5, 5, 5)\nrgb(0, 0, 0)");
check!(checked_disabled_styles_via_state, "<style>#c:checked + span { color: rgb(1, 1, 1) } #b:disabled { color: rgb(2, 2, 2) }</style><input id=c type=checkbox><span id=s></span><button id=b></button>", "console.log(getComputedStyle(s).color); c.checked=true; console.log(getComputedStyle(s).color); b.disabled=true; console.log(getComputedStyle(b).color);", "rgb(0, 0, 0)\nrgb(1, 1, 1)\nrgb(2, 2, 2)");

#[test]
fn link_sheet_from_host() {
    let host = MemoryHost::new().with_response("https://example.test/s.css", "text/css", "#d { color: red }");
    let r = realm_with("<link rel=stylesheet href=/s.css><div id=d></div><script>console.log(getComputedStyle(d).color)</script>", host);
    assert_eq!(logs(&r), "rgb(255, 0, 0)");
}

#[test]
fn import_rule_expands() {
    let host = MemoryHost::new().with_response("https://example.test/imp.css", "text/css", "#d { font-size: 33px }");
    let r = realm_with("<style>@import url(/imp.css); #d { color: red }</style><div id=d></div><script>console.log(getComputedStyle(d).fontSize, getComputedStyle(d).color, document.styleSheets.length)</script>", host);
    assert_eq!(logs(&r), "33px rgb(255, 0, 0) 1");
}

check!(offset_and_client_metrics, "<style>body{margin:0} #a{width:200px;height:100px;padding:10px;border:5px solid;margin-top:20px} #b{width:50px;height:30px;margin-left:15px}</style><div id=a><div id=b></div></div><span id=s>x</span>", "console.log(a.offsetWidth, a.offsetHeight, a.offsetTop, a.offsetLeft, a.clientWidth, a.clientHeight, a.clientTop, a.clientLeft, b.offsetTop, b.offsetLeft, b.offsetParent===document.body, a.offsetParent===document.body, document.body.offsetParent, s.offsetWidth>0, s.clientWidth);", "230 130 20 0 220 120 5 5 35 30 true true null true 0");
check!(bounding_client_rect, "<style>body{margin:0} #a{position:absolute;left:10px;top:20px;width:30px;height:40px} #h{display:none}</style><div id=a></div><div id=h></div>", "const r=a.getBoundingClientRect(); console.log(r.x, r.y, r.width, r.height, r.left, r.top, r.right, r.bottom, r instanceof DOMRect, JSON.stringify(h.getBoundingClientRect()), a.getClientRects().length, h.getClientRects().length, JSON.stringify(document.createElement('div').getBoundingClientRect().width));", "10 20 30 40 10 20 40 60 true {\"x\":0,\"y\":0,\"width\":0,\"height\":0,\"top\":0,\"right\":0,\"bottom\":0,\"left\":0} 1 0 0");
check!(rect_after_class_change_forces_layout, "<style>.w { width: 77px; height: 11px } .x { width: 200px }</style><div id=d class=w></div>", "console.log(d.getBoundingClientRect().width, d.offsetWidth); d.classList.add('x'); console.log(d.getBoundingClientRect().width, d.offsetWidth); d.style.width='5px'; console.log(d.offsetWidth); d.style.display='none'; console.log(d.offsetWidth, d.offsetHeight, d.offsetParent);", "77 77\n200 200\n5\n0 0 null");
check!(inline_text_metrics, "<style>body{margin:0;font-size:16px;line-height:20px}</style><p id=p>hello</p>", "console.log(p.offsetHeight, p.getBoundingClientRect().top, p.offsetWidth===document.body.clientWidth, p.clientHeight);", "20 16 true 20");
check!(scroll_metrics_and_setting, "<style>#s{height:100px;width:100px;overflow:auto} #c{height:1000px;width:50px}</style><div id=s><div id=c></div></div>", "console.log(s.scrollHeight, s.clientHeight, s.scrollTop, s.scrollWidth>=50, s.scrollTopMax>0); s.scrollTop=50; console.log(s.scrollTop); s.scrollTop=99999; console.log(s.scrollTop===s.scrollHeight-s.clientHeight, s.scrollTop); s.scrollTo(0, 10); s.scrollBy({top: 5}); console.log(s.scrollTop); s.scrollTop=-4; console.log(s.scrollTop);", "1000 85 0 true true\n50\ntrue 915\n15\n0");
check!(window_scroll, "<style>body{margin:0}</style><div style='height:5000px'></div><div id=t style='height:10px'></div>", "console.log(scrollX, scrollY, pageYOffset, innerWidth, innerHeight, document.documentElement.scrollHeight, document.documentElement.clientHeight, document.body.scrollHeight>=5000); scrollTo(0, 100); console.log(scrollY, document.documentElement.scrollTop, t.getBoundingClientRect().top); scrollBy(0, 50); console.log(scrollY); window.scroll({top: 20}); console.log(scrollY); document.documentElement.scrollTop=3; console.log(scrollY); t.scrollIntoView(); console.log(scrollY, t.getBoundingClientRect().top); scrollTo(0, 99999); console.log(scrollY);", "0 0 0 1280 800 5010 800 true\n100 100 4900\n150\n20\n3\n4210 790\n4210");
check!(element_from_point, "<style>body{margin:0} #a{height:50px} #b{position:absolute;top:0;left:0;width:20px;height:20px} #hid{position:absolute;top:0;left:30px;width:10px;height:10px;pointer-events:none}</style><div id=a></div><div id=b></div><div id=hid></div>", "console.log(document.elementFromPoint(5,5).id, document.elementFromPoint(100,10).id, document.elementFromPoint(35,5).id, document.elementsFromPoint(5,5).map(e=>e.id||e.tagName).join(), document.elementFromPoint(5,5000), document.elementFromPoint(10, 100).tagName);", "b a a b,BODY,HTML null HTML");
check!(viewport_and_screen, "", "console.log(innerWidth, innerHeight, outerWidth, devicePixelRatio, screen.width, screen.height, screen.availWidth, screen.colorDepth, screen.orientation.type, visualViewport.width, document.documentElement.clientWidth);", "1280 800 1280 1 1280 800 1280 24 landscape-primary 1280 1280");
check!(check_visibility_and_rendered, "<div id=a></div><div id=b style='display:none'></div><div id=c style='visibility:hidden'></div>", "console.log(a.checkVisibility(), b.checkVisibility(), c.checkVisibility(), c.checkVisibility({checkVisibilityCSS:true}));", "true false true false");
check!(client_rects_of_inline, "<style>body{margin:0;width:100px;font-size:16px;line-height:20px}</style><span id=s>aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa</span>", "const r=s.getClientRects(); console.log(r.length>1, s.getBoundingClientRect().height>20, r[0].top, s.offsetWidth>0);", "true true 0 true");
check!(layout_read_after_innerhtml, "<style>li{height:10px}</style><ul id=u></ul>", "u.innerHTML='<li></li><li></li><li></li>'; console.log(u.offsetHeight, u.children[2].offsetTop-u.children[0].offsetTop); u.firstElementChild.remove(); console.log(u.offsetHeight);", "30 20\n20");
check!(computed_style_of_detached, "", "const d=document.createElement('div'); d.style.color='red'; console.log(JSON.stringify(getComputedStyle(d).color), d.offsetWidth, JSON.stringify(getComputedStyle(d).display)); const f=document.createElement('div'); document.body.appendChild(f); console.log(getComputedStyle(f).display);", "\"\" 0 \"\"\nblock");
