#!/usr/bin/env python3
"""Fetches the pinned inputs of the HTML module and regenerates what is checked in.

Two things are fetched over the network, each verified against a pinned SHA-256:

1. The WHATWG named character reference table (`entities.json`), from which
   `crates/web/src/html/entities.rs` is generated. The table has 2231 names, 106 of
   which have no trailing semicolon; the generated file is sorted by name so the
   tokenizer can binary-search it.
2. The html5lib-tests repository at a pinned commit, from which the tree-construction
   `.dat` files (including `scripted/`) and the MIT LICENSE are copied into
   `crates/web/tests/html5lib/`. The pinned commit is the last one before the
   tree-construction tests moved to web-platform-tests.

Run from anywhere: `python3 crates/web/tools/fetch-html5lib.py`. Requires only the
standard library. Pass `--check` to verify the checked-in files match without writing.
"""

import hashlib
import io
import json
import os
import sys
import tarfile
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(HERE)

ENTITIES_URL = "https://html.spec.whatwg.org/entities.json"
ENTITIES_SHA256 = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
ENTITIES_RS = os.path.join(CRATE, "src", "html", "entities.rs")

TESTS_COMMIT = "9329e64694e7835d0dcff9811e22856ef6ad16f9"
TESTS_URL = f"https://github.com/html5lib/html5lib-tests/archive/{TESTS_COMMIT}.tar.gz"
TESTS_SHA256 = "37d2a0619856234e0631cfb08cf77f32420cba07ad4f3b3871ea991126cc5b57"
TESTS_DIR = os.path.join(CRATE, "tests", "html5lib")


def fetch(url, sha256):
    print(f"fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=120) as r:
        data = r.read()
    got = hashlib.sha256(data).hexdigest()
    if got != sha256:
        sys.exit(f"{url}: SHA-256 {got} does not match the pinned {sha256}")
    return data


def rust_str(s):
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == '"' or ch == "\\":
            out.append("\\" + ch)
        elif 0x20 <= cp < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{{{cp:x}}}")
    return '"' + "".join(out) + '"'


def generate_entities(data):
    table = json.loads(data.decode("utf-8"))
    rows = []
    for name, entry in table.items():
        assert name.startswith("&")
        rows.append((name[1:], entry["characters"]))
    rows.sort(key=lambda r: r[0].encode("utf-8"))
    without_semicolon = sum(1 for n, _ in rows if not n.endswith(";"))
    longest = max(len(n) for n, _ in rows)
    lines = [
        "//! The WHATWG named character reference table, generated by",
        "//! `crates/web/tools/fetch-html5lib.py` from",
        f"//! <{ENTITIES_URL}> (SHA-256 {ENTITIES_SHA256}).",
        "//! Do not edit by hand; rerun the script.",
        "//!",
        f"//! {len(rows)} names, {without_semicolon} of them without a trailing semicolon,",
        "//! sorted by name (byte order) so `lookup` can binary-search.",
        "",
        "/// Number of names in the table.",
        f"pub const COUNT: usize = {len(rows)};",
        "/// Length of the longest name (including its semicolon).",
        f"pub const LONGEST_NAME: usize = {longest};",
        "",
        "/// `(name without the leading ampersand, replacement text)`, sorted by name.",
        "pub static ENTITIES: &[(&str, &str)] = &[",
    ]
    for name, chars in rows:
        lines.append(f"    ({rust_str(name)}, {rust_str(chars)}),")
    lines.append("];")
    lines.append("")
    lines.append("/// The replacement for a name (without `&`), if it is in the table.")
    lines.append("pub fn lookup(name: &str) -> Option<&'static str> {")
    lines.append("    ENTITIES.binary_search_by(|(n, _)| n.as_bytes().cmp(name.as_bytes())).ok().map(|i| ENTITIES[i].1)")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def extract_tests(data):
    files = {}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        for m in tar.getmembers():
            if not m.isfile():
                continue
            parts = m.name.split("/", 1)
            if len(parts) != 2:
                continue
            rel = parts[1]
            if rel == "LICENSE":
                files["LICENSE"] = tar.extractfile(m).read()
            elif rel.startswith("tree-construction/") and rel.endswith(".dat"):
                files[rel[len("tree-construction/"):]] = tar.extractfile(m).read()
    assert "LICENSE" in files and len(files) > 50, "unexpected archive layout"
    return files


def write(path, content, check):
    if isinstance(content, str):
        content = content.encode("utf-8")
    if check:
        try:
            with open(path, "rb") as f:
                same = f.read() == content
        except FileNotFoundError:
            same = False
        if not same:
            sys.exit(f"{path} is out of date; rerun without --check")
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(content)


def main():
    check = "--check" in sys.argv[1:]
    write(ENTITIES_RS, generate_entities(fetch(ENTITIES_URL, ENTITIES_SHA256)), check)
    files = extract_tests(fetch(TESTS_URL, TESTS_SHA256))
    for rel, content in sorted(files.items()):
        write(os.path.join(TESTS_DIR, rel), content, check)
    readme = (
        f"Tree-construction tests from https://github.com/html5lib/html5lib-tests\n"
        f"at commit {TESTS_COMMIT} (MIT, see LICENSE), copied by\n"
        f"crates/web/tools/fetch-html5lib.py. The runner is tests/html5lib.rs.\n"
    )
    write(os.path.join(TESTS_DIR, "README"), readme, check)
    print(f"wrote {ENTITIES_RS} and {len(files)} files under {TESTS_DIR}", file=sys.stderr)


if __name__ == "__main__":
    main()
