// @generated by cw-tsx (`cw-tsx build --emit rust`) from the UI IR of `Notes.tsx`
// (IR hash fdeed7c5e528a986). Do not edit: regenerate from the source.
#[rustfmt::skip]
#[allow(unused_mut, unused_variables, unused_assignments, unused_labels, unreachable_code, unused_parens, unused_braces, unused_imports, dead_code, non_upper_case_globals, clippy::all)]
pub mod notes {
use std::rc::Rc;
use cw_ui::gen::*;

/// FNV-1a 64 of the IR's canonical JSON.
pub const IR_HASH: u64 = 0xfdeed7c5e528a986;

pub static PROGRAM: GenProgram = GenProgram {
    name: "Notes.tsx",
    hash: IR_HASH,
    container_id: Some("root"),
    root_element: 25,
    pure_render: false,
    n_globals: 22,
    funcs: &FUNCS,
    templates: &TEMPLATES,
    init: init,
    async_ir: r#""#,
    async_cache: std::sync::OnceLock::new(),
};

static FUNCS: [GenFunc; 51] = [
    GenFunc { name: "declaredStore", arity: 1, captures: &[], boxed: &[], code: Some(f0 as GenFn) },
    GenFunc { name: "useStore", arity: 1, captures: &[], boxed: &[], code: Some(f1 as GenFn) },
    GenFunc { name: "useEnv", arity: 0, captures: &[], boxed: &[], code: Some(f2 as GenFn) },
    GenFunc { name: "byCodePoint", arity: 2, captures: &[], boxed: &[], code: Some(f3 as GenFn) },
    GenFunc { name: "describe", arity: 1, captures: &[], boxed: &[], code: Some(f4 as GenFn) },
    GenFunc { name: "list", arity: 0, captures: &[], boxed: &[], code: Some(f5 as GenFn) },
    GenFunc { name: "save", arity: 0, captures: &[], boxed: &[], code: Some(f6 as GenFn) },
    GenFunc { name: "newNote", arity: 0, captures: &[], boxed: &[], code: Some(f7 as GenFn) },
    GenFunc { name: "open", arity: 1, captures: &[], boxed: &[], code: Some(f8 as GenFn) },
    GenFunc { name: "close", arity: 0, captures: &[], boxed: &[], code: Some(f9 as GenFn) },
    GenFunc { name: "edit", arity: 1, captures: &[], boxed: &[], code: Some(f10 as GenFn) },
    GenFunc { name: "onKey", arity: 1, captures: &[], boxed: &[], code: Some(f11 as GenFn) },
    GenFunc { name: "title", arity: 1, captures: &[], boxed: &[], code: Some(f12 as GenFn) },
    GenFunc { name: "Action", arity: 1, captures: &[], boxed: &[], code: Some(f13 as GenFn) },
    GenFunc { name: "List", arity: 1, captures: &[], boxed: &[], code: Some(f14 as GenFn) },
    GenFunc { name: "Notice", arity: 1, captures: &[], boxed: &[], code: Some(f15 as GenFn) },
    GenFunc { name: "Buttons", arity: 0, captures: &[], boxed: &[], code: Some(f16 as GenFn) },
    GenFunc { name: "Note", arity: 1, captures: &[], boxed: &[], code: Some(f17 as GenFn) },
    GenFunc { name: "Notes", arity: 0, captures: &[], boxed: &[], code: Some(f18 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(3), Capture::Local(4)], boxed: &[], code: Some(f19 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(3)], boxed: &[], code: Some(f20 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(5), Capture::Local(3)], boxed: &[], code: Some(f21 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(4)], boxed: &[], code: Some(f22 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Capture(0), Capture::Local(0)], boxed: &[], code: Some(f23 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[], boxed: &[], code: Some(f24 as GenFn) },
    GenFunc { name: "<root>", arity: 0, captures: &[], boxed: &[], code: Some(f25 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(1)], boxed: &[], code: Some(f26 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(4), Capture::Local(5)], boxed: &[], code: Some(f27 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(4), Capture::Local(5)], boxed: &[], code: Some(f28 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Capture(0), Capture::Capture(1)], boxed: &[], code: Some(f29 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(0)], boxed: &[], code: Some(f30 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[], boxed: &[], code: Some(f31 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f32 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(0)], boxed: &[], code: Some(f33 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f34 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f35 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(0)], boxed: &[], code: Some(f36 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[], boxed: &[], code: Some(f37 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(0)], boxed: &[], code: Some(f38 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[], boxed: &[], code: Some(f39 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(0)], boxed: &[], code: Some(f40 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f41 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f42 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[], boxed: &[], code: Some(f43 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f44 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(0)], boxed: &[], code: Some(f45 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(1)], boxed: &[], code: Some(f46 as GenFn) },
    GenFunc { name: "<arrow>", arity: 0, captures: &[Capture::Local(0)], boxed: &[], code: Some(f47 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Local(0)], boxed: &[], code: Some(f48 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[Capture::Capture(0), Capture::Local(0)], boxed: &[], code: Some(f49 as GenFn) },
    GenFunc { name: "<arrow>", arity: 1, captures: &[], boxed: &[], code: Some(f50 as GenFn) },
];

static TEMPLATES: [STemplate; 16] = [
    STemplate { n_holes: 2, root: STNode::Element { tag: "h2", attrs: &[STAttr::Static("id", "notes-folder"), STAttr::Dynamic("hidden", 0)], children: &[STNode::Hole(1)] } },
    STemplate { n_holes: 2, root: STNode::Element { tag: "button", attrs: &[STAttr::Static("id", "notes:close"), STAttr::Static("data-cw-back", ""), STAttr::Static("class", "back"), STAttr::Static("aria-label", "Back to notes"), STAttr::Dynamic("onClick", 0)], children: &[STNode::Element { tag: "svg", attrs: &[STAttr::Static("class", "chevron"), STAttr::Static("width", "20"), STAttr::Static("height", "20"), STAttr::Static("viewBox", "0 0 20 20"), STAttr::Static("aria-hidden", "true")], children: &[STNode::Element { tag: "path", attrs: &[STAttr::Static("d", "M12.5 4.5 L7 10 L12.5 15.5"), STAttr::Static("fill", "none"), STAttr::Static("stroke", "currentColor"), STAttr::Static("stroke-width", "2.2"), STAttr::Static("stroke-linecap", "round"), STAttr::Static("stroke-linejoin", "round")], children: &[] }] }, STNode::Element { tag: "span", attrs: &[STAttr::Static("class", "back-title")], children: &[STNode::Hole(1)] }] } },
    STemplate { n_holes: 0, root: STNode::Element { tag: "span", attrs: &[STAttr::Static("class", "empty"), STAttr::Static("aria-hidden", "true")], children: &[STNode::Text("Empty note")] } },
    STemplate { n_holes: 12, root: STNode::Element { tag: "section", attrs: &[STAttr::Dynamic("className", 0)], children: &[STNode::Hole(1), STNode::Element { tag: "strong", attrs: &[STAttr::Static("class", "name")], children: &[STNode::Hole(2)] }, STNode::Element { tag: "textarea", attrs: &[STAttr::Static("id", "notes:body"), STAttr::Static("data-page-id", "notes-body"), STAttr::Static("data-cw-pane", "note"), STAttr::Static("aria-label", "Note"), STAttr::Static("class", "body"), STAttr::Dynamic("value", 3), STAttr::Dynamic("maxLength", 4), STAttr::Dynamic("spellCheck", 5), STAttr::Dynamic("onChange", 6), STAttr::Dynamic("onClick", 7)], children: &[] }, STNode::Hole(8), STNode::Element { tag: "button", attrs: &[STAttr::Static("id", "notes:save"), STAttr::Dynamic("className", 9), STAttr::Dynamic("onClick", 10)], children: &[STNode::Hole(11)] }] } },
    STemplate { n_holes: 2, root: STNode::Element { tag: "div", attrs: &[STAttr::Static("class", "app narrow")], children: &[STNode::Hole(0), STNode::Hole(1)] } },
    STemplate { n_holes: 1, root: STNode::Element { tag: "header", attrs: &[STAttr::Static("class", "appbar")], children: &[STNode::Element { tag: "strong", attrs: &[], children: &[STNode::Hole(0)] }] } },
    STemplate { n_holes: 1, root: STNode::Element { tag: "strong", attrs: &[STAttr::Static("class", "large-title")], children: &[STNode::Hole(0)] } },
    STemplate { n_holes: 1, root: STNode::Element { tag: "p", attrs: &[STAttr::Static("id", "notes-problem"), STAttr::Static("role", "alert"), STAttr::Static("class", "notice listed")], children: &[STNode::Hole(0)] } },
    STemplate { n_holes: 0, root: STNode::Element { tag: "p", attrs: &[STAttr::Static("class", "notice listed")], children: &[STNode::Text("No notes yet")] } },
    STemplate { n_holes: 4, root: STNode::Element { tag: "button", attrs: &[STAttr::Dynamic("id", 0), STAttr::Dynamic("className", 1), STAttr::Dynamic("onClick", 2)], children: &[STNode::Hole(3)] } },
    STemplate { n_holes: 2, root: STNode::Element { tag: "div", attrs: &[STAttr::Static("class", "buttons")], children: &[STNode::Hole(0), STNode::Hole(1)] } },
    STemplate { n_holes: 5, root: STNode::Element { tag: "button", attrs: &[STAttr::Dynamic("id", 0), STAttr::Dynamic("aria-label", 1), STAttr::Dynamic("className", 2), STAttr::Dynamic("onClick", 3)], children: &[STNode::Hole(4)] } },
    STemplate { n_holes: 9, root: STNode::Element { tag: "div", attrs: &[STAttr::Dynamic("className", 0)], children: &[STNode::Hole(1), STNode::Hole(2), STNode::Element { tag: "div", attrs: &[STAttr::Static("id", "main"), STAttr::Static("class", "main"), STAttr::Dynamic("data-cw-large-title", 3), STAttr::Dynamic("data-cw-large-title-height", 4)], children: &[STNode::Hole(5), STNode::Element { tag: "div", attrs: &[STAttr::Static("class", "sheet")], children: &[STNode::Hole(6), STNode::Hole(7), STNode::Element { tag: "div", attrs: &[STAttr::Static("class", "rows")], children: &[STNode::Hole(8)] }] }] }] } },
    STemplate { n_holes: 0, root: STNode::Element { tag: "p", attrs: &[STAttr::Static("class", "notice")], children: &[STNode::Text("Select a note")] } },
    STemplate { n_holes: 1, root: STNode::Element { tag: "main", attrs: &[STAttr::Static("class", "pane")], children: &[STNode::Hole(0)] } },
    STemplate { n_holes: 7, root: STNode::Element { tag: "div", attrs: &[STAttr::Dynamic("className", 0)], children: &[STNode::Hole(1), STNode::Element { tag: "header", attrs: &[STAttr::Static("class", "toolbar")], children: &[STNode::Element { tag: "strong", attrs: &[], children: &[STNode::Hole(2)] }] }, STNode::Element { tag: "aside", attrs: &[STAttr::Static("class", "sidebar")], children: &[STNode::Hole(3), STNode::Hole(4), STNode::Element { tag: "div", attrs: &[STAttr::Static("id", "list"), STAttr::Static("class", "list")], children: &[STNode::Hole(5)] }] }, STNode::Hole(6)] } },
];

/// `declaredStore` (line 20).
fn f0(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; let mut l2: Value = Value::Undefined; let mut l3: Value = Value::Undefined; let mut l4: Value = Value::Undefined; let mut l5: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<Value> = Vec::with_capacity(0);
    let t3 = rt.call_builtin(Builtin::CwStateGet, t2)?;
    let t4 = t3;
    l1 = t4;
    let t5 = l1.clone();
    let t6 = Value::Bool(strict_equals(&t5, &Value::Null));
    let t7 = t6;
    l2 = t7;
    let mut t8: Vec<(Str, Value)> = Vec::with_capacity(1);
    let t9 = l1.clone();
    let t10 = Value::Bool(strict_equals(&t9, &Value::Null));
    let t11 = if t10.truthy() {
        let t12 = l0.clone();
        let mut t13: Vec<Value> = Vec::with_capacity(0);
        let t14 = rt.call(&t12, t13)?;
        t14
    } else {
        let t15 = l1.clone();
        t15
    };
    obj_put(&mut t8, "current", t11);
    let t16 = Value::object(t8);
    let t17 = t16;
    l3 = t17;
    let t18 = l2.clone();
    if t18.truthy() {
        let mut t19: Vec<Value> = Vec::with_capacity(1);
        let t20 = l3.clone();
        let t21 = rt.member(&t20, "current")?;
        t19.push(t21);
        let t22 = rt.call_builtin(Builtin::CwStateSet, t19)?;
        let _ = t22;
    }
    let mut t23: Vec<Value> = Vec::with_capacity(0);
    let t24 = rt.call_builtin(Builtin::NewSet, t23)?;
    let t25 = t24;
    l4 = t25;
    let t26 = closure(19, vec![l3.clone(), l4.clone()]);
    let t27 = t26;
    l5 = t27;
    let mut t28: Vec<(Str, Value)> = Vec::with_capacity(5);
    let t29 = l2.clone();
    let t30 = Value::Bool(!t29.truthy());
    obj_put(&mut t28, "restored", t30);
    let t31 = closure(20, vec![l3.clone()]);
    obj_put(&mut t28, "get", t31);
    let t32 = l5.clone();
    obj_put(&mut t28, "set", t32);
    let t33 = closure(21, vec![l5.clone(), l3.clone()]);
    obj_put(&mut t28, "update", t33);
    let t34 = closure(22, vec![l4.clone()]);
    obj_put(&mut t28, "subscribe", t34);
    let t35 = Value::object(t28);
    return Ok(t35);
    Ok(Value::Undefined)
}

/// `useStore` (line 47).
fn f1(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t3 = rt.hook_with(Hook::SyncExternalStore, 2, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t4 = l0.clone();
                let t5 = rt.member(&t4, "subscribe")?;
                Ok(t5)
            }
            1 => {
                let t6 = l0.clone();
                let t7 = rt.member(&t6, "get")?;
                Ok(t7)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t2 = t3?;
    return Ok(t2);
    Ok(Value::Undefined)
}

/// `useEnv` (line 52).
fn f2(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let t2 = rt.hook_with(Hook::State, 1, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let mut t3: Vec<Value> = Vec::with_capacity(0);
                let t4 = rt.call_builtin(Builtin::CwEnv, t3)?;
                Ok(t4)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t1 = t2?;
    let t5 = t1;
    let t6 = array_items(&t5)?;
    let t7 = t6.get(0).cloned().unwrap_or_default();
    l0 = t7;
    let t8 = t6.get(1).cloned().unwrap_or_default();
    l1 = t8;
    let t10 = rt.hook_with(Hook::Effect, 2, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t11 = closure(26, vec![l1.clone()]);
                Ok(t11)
            }
            1 => {
                let mut t12: Vec<Value> = Vec::with_capacity(0);
                let t13 = Value::array(t12);
                Ok(t13)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t9 = t10?;
    let _ = t9;
    let t14 = l0.clone();
    return Ok(t14);
    Ok(Value::Undefined)
}

/// `byCodePoint` (line 39).
fn f3(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; let mut l2: Value = Value::Undefined; let mut l3: Value = Value::Undefined; let mut l4: Value = Value::Undefined; let mut l5: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = args.next().unwrap_or(Value::Undefined);
    l1 = t2;
    let mut t3: Vec<Value> = Vec::with_capacity(1);
    let t4 = l0.clone();
    t3.push(t4);
    let t5 = rt.call_builtin(Builtin::ArrayFrom, t3)?;
    let t6 = t5;
    l2 = t6;
    let mut t7: Vec<Value> = Vec::with_capacity(1);
    let t8 = l1.clone();
    t7.push(t8);
    let t9 = rt.call_builtin(Builtin::ArrayFrom, t7)?;
    let t10 = t9;
    l3 = t10;
    let t11 = Value::Num(0.0);
    l4 = t11;
    let mut t12: u64 = 0;
    'l1: loop {
        let t13 = l4.clone();
        let mut t14: Vec<Value> = Vec::with_capacity(2);
        let t15 = l2.clone();
        let t16 = rt.member(&t15, "length")?;
        t14.push(t16);
        let t17 = l3.clone();
        let t18 = rt.member(&t17, "length")?;
        t14.push(t18);
        let t19 = rt.call_builtin(Builtin::MathMin, t14)?;
        let t20 = Value::Bool(compare(BinaryOp::Lt, &t13, &t19));
        if !t20.truthy() { break 'l1; }
        'b1: {
            let t21 = l2.clone();
            let t22 = l4.clone();
            let t23 = rt.index(&t21, &t22)?;
            let mut t24: Vec<Value> = Vec::with_capacity(1);
            t24.push(Value::Num(0.0));
            let t25 = rt.call_method(&t23, Method::StrCodePointAt, t24)?;
            let t26 = if t25.is_nullish() {
                Value::Num(0.0)
            } else { t25 };
            let t27 = l3.clone();
            let t28 = l4.clone();
            let t29 = rt.index(&t27, &t28)?;
            let mut t30: Vec<Value> = Vec::with_capacity(1);
            t30.push(Value::Num(0.0));
            let t31 = rt.call_method(&t29, Method::StrCodePointAt, t30)?;
            let t32 = if t31.is_nullish() {
                Value::Num(0.0)
            } else { t31 };
            let t33 = Value::Num(t26.to_number() - t32.to_number());
            let t34 = t33;
            l5 = t34;
            let t35 = l5.clone();
            let t36 = Value::Bool(!strict_equals(&t35, &Value::Num(0.0)));
            if t36.truthy() {
                let t37 = l5.clone();
                return Ok(t37);
            }
        }
        let t38 = l4.clone();
        let t39 = t38.to_number();
        let t40 = t39 + 1.0;
        l4 = Value::Num(t40);
        let t41 = Value::Num(t39);
        let _ = t41;
        t12 += 1;
        if t12 > 50_000_000 { return Err(Throw::Value(Value::error("RangeError", "loop did not terminate"))); }
    }
    let t42 = l2.clone();
    let t43 = rt.member(&t42, "length")?;
    let t44 = l3.clone();
    let t45 = rt.member(&t44, "length")?;
    let t46 = Value::Num(t43.to_number() - t45.to_number());
    return Ok(t46);
    Ok(Value::Undefined)
}

/// `describe` (line 49).
fn f4(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<Value> = Vec::with_capacity(2);
    let t3 = l0.clone();
    t2.push(t3);
    t2.push(str("Error"));
    let t4 = rt.call_builtin(Builtin::IsError, t2)?;
    let t5 = if t4.truthy() {
        let t6 = l0.clone();
        let t7 = rt.member(&t6, "message")?;
        t7
    } else {
        let mut t8: Vec<Value> = Vec::with_capacity(1);
        let t9 = l0.clone();
        t8.push(t9);
        let t10 = rt.call_builtin(Builtin::String, t8)?;
        t10
    };
    return Ok(t5);
    Ok(Value::Undefined)
}

/// `list` (line 53).
fn f5(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let t1 = rt.global(20);
    let t2 = rt.member(&t1, "get")?;
    let mut t3: Vec<Value> = Vec::with_capacity(0);
    let t4 = rt.call(&t2, t3)?;
    let t5 = t4;
    destructure_check(&t5)?;
    let t6 = rt.member(&t5, "folder")?;
    l0 = t6;
    let mut t7: Vec<Value> = Vec::with_capacity(1);
    let t8 = l0.clone();
    t7.push(t8);
    let t9 = rt.call_builtin(Builtin::CwList, t7)?;
    let mut t10: Vec<Value> = Vec::with_capacity(2);
    let t11 = closure(32, vec![]);
    t10.push(t11);
    let t12 = closure(35, vec![]);
    t10.push(t12);
    let t13 = rt.call_method(&t9, Method::PromiseThen, t10)?;
    let _ = t13;
    Ok(Value::Undefined)
}

/// `save` (line 66).
fn f6(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let t1 = rt.global(20);
    let t2 = rt.member(&t1, "get")?;
    let mut t3: Vec<Value> = Vec::with_capacity(0);
    let t4 = rt.call(&t2, t3)?;
    let t5 = t4;
    l0 = t5;
    let t6 = l0.clone();
    let t7 = rt.member(&t6, "open")?;
    let t8 = Value::Bool(strict_equals(&t7, &Value::Null));
    if t8.truthy() {
        let mut t9: Vec<Value> = Vec::with_capacity(1);
        t9.push(str("no note is open"));
        let t10 = rt.call_builtin(Builtin::CwRefuse, t9)?;
        let _ = t10;
        return Ok(Value::Bool(false));
    }
    let mut t11 = String::new();
    let t12 = l0.clone();
    let t13 = rt.member(&t12, "folder")?;
    t11.push_str(&t13.to_js_string());
    t11.push_str("/");
    let t14 = l0.clone();
    let t15 = rt.member(&t14, "open")?;
    t11.push_str(&t15.to_js_string());
    let t16 = Value::str(&t11);
    let t17 = t16;
    l1 = t17;
    let t18 = rt.global(20);
    let t19 = rt.member(&t18, "set")?;
    let mut t20: Vec<Value> = Vec::with_capacity(1);
    let mut t21: Vec<(Str, Value)> = Vec::with_capacity(2);
    let t22 = l0.clone();
    obj_spread(&mut t21, &t22);
    obj_put(&mut t21, "dirty", Value::Bool(false));
    let t23 = Value::object(t21);
    t20.push(t23);
    let t24 = rt.call(&t19, t20)?;
    let _ = t24;
    let mut t25: Vec<Value> = Vec::with_capacity(1);
    let t26 = l0.clone();
    let t27 = rt.member(&t26, "folder")?;
    t25.push(t27);
    let t28 = rt.call_builtin(Builtin::CwMkdir, t25)?;
    let _ = t28;
    let mut t29: Vec<Value> = Vec::with_capacity(2);
    let t30 = l1.clone();
    t29.push(t30);
    let t31 = l0.clone();
    let t32 = rt.member(&t31, "text")?;
    t29.push(t32);
    let t33 = rt.call_builtin(Builtin::CwWriteFile, t29)?;
    let mut t34: Vec<Value> = Vec::with_capacity(1);
    let t35 = rt.global(5);
    t34.push(t35);
    let t36 = rt.call_method(&t33, Method::PromiseThen, t34)?;
    let _ = t36;
    return Ok(Value::Bool(true));
    Ok(Value::Undefined)
}

/// `newNote` (line 80).
fn f7(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut t1 = String::new();
    t1.push_str("note-");
    let mut t2: Vec<Value> = Vec::with_capacity(1);
    let mut t3: Vec<Value> = Vec::with_capacity(0);
    let t4 = rt.call_builtin(Builtin::CwNow, t3)?;
    let t5 = Value::Num(t4.to_number() / Value::Num(1000000.0).to_number());
    t2.push(t5);
    let t6 = rt.call_builtin(Builtin::MathFloor, t2)?;
    t1.push_str(&t6.to_js_string());
    t1.push_str(".txt");
    let t7 = Value::str(&t1);
    let t8 = t7;
    l0 = t8;
    let t9 = rt.global(20);
    let t10 = rt.member(&t9, "update")?;
    let mut t11: Vec<Value> = Vec::with_capacity(1);
    let t12 = closure(45, vec![l0.clone()]);
    t11.push(t12);
    let t13 = rt.call(&t10, t11)?;
    let _ = t13;
    Ok(Value::Undefined)
}

/// `open` (line 93).
fn f8(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = rt.global(20);
    let t3 = rt.member(&t2, "get")?;
    let mut t4: Vec<Value> = Vec::with_capacity(0);
    let t5 = rt.call(&t3, t4)?;
    let t6 = t5;
    l1 = t6;
    let t7 = l1.clone();
    let t8 = rt.member(&t7, "entries")?;
    let mut t9: Vec<Value> = Vec::with_capacity(1);
    let t10 = l0.clone();
    t9.push(t10);
    let t11 = rt.call_method(&t8, Method::ArrayIncludes, t9)?;
    let t12 = Value::Bool(!t11.truthy());
    if t12.truthy() {
        let mut t13: Vec<Value> = Vec::with_capacity(1);
        t13.push(str("note not found"));
        let t14 = rt.call_builtin(Builtin::CwRefuse, t13)?;
        let _ = t14;
        return Ok(Value::Undefined);
    }
    let t15 = rt.global(20);
    let t16 = rt.member(&t15, "set")?;
    let mut t17: Vec<Value> = Vec::with_capacity(1);
    let mut t18: Vec<(Str, Value)> = Vec::with_capacity(5);
    let t19 = l1.clone();
    obj_spread(&mut t18, &t19);
    let t20 = l0.clone();
    obj_put(&mut t18, "open", t20);
    obj_put(&mut t18, "editing", Value::Bool(false));
    obj_put(&mut t18, "text", str(""));
    obj_put(&mut t18, "dirty", Value::Bool(false));
    let t21 = Value::object(t18);
    t17.push(t21);
    let t22 = rt.call(&t16, t17)?;
    let _ = t22;
    let mut t23: Vec<Value> = Vec::with_capacity(1);
    let mut t24 = String::new();
    let t25 = l1.clone();
    let t26 = rt.member(&t25, "folder")?;
    t24.push_str(&t26.to_js_string());
    t24.push_str("/");
    let t27 = l0.clone();
    t24.push_str(&t27.to_js_string());
    let t28 = Value::str(&t24);
    t23.push(t28);
    let t29 = rt.call_builtin(Builtin::CwReadFile, t23)?;
    let mut t30: Vec<Value> = Vec::with_capacity(2);
    let t31 = closure(48, vec![l0.clone()]);
    t30.push(t31);
    let t32 = closure(50, vec![]);
    t30.push(t32);
    let t33 = rt.call_method(&t29, Method::PromiseThen, t30)?;
    let _ = t33;
    Ok(Value::Undefined)
}

/// `close` (line 109).
fn f9(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let t1 = rt.global(20);
    let t2 = rt.member(&t1, "get")?;
    let mut t3: Vec<Value> = Vec::with_capacity(0);
    let t4 = rt.call(&t2, t3)?;
    let t5 = rt.member(&t4, "dirty")?;
    if t5.truthy() {
        let mut t6: Vec<Value> = Vec::with_capacity(0);
        let t7 = f6(rt, &[], t6, None)?;
        let _ = t7;
    }
    let t8 = rt.global(20);
    let t9 = rt.member(&t8, "update")?;
    let mut t10: Vec<Value> = Vec::with_capacity(1);
    let t11 = closure(41, vec![]);
    t10.push(t11);
    let t12 = rt.call(&t9, t10)?;
    let _ = t12;
    Ok(Value::Undefined)
}

/// `edit` (line 114).
fn f10(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = rt.global(20);
    let t3 = rt.member(&t2, "update")?;
    let mut t4: Vec<Value> = Vec::with_capacity(1);
    let t5 = closure(38, vec![l0.clone()]);
    t4.push(t5);
    let t6 = rt.call(&t3, t4)?;
    let _ = t6;
    Ok(Value::Undefined)
}

/// `onKey` (line 133).
fn f11(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; let mut l2: Value = Value::Undefined; let mut l3: Value = Value::Undefined; let mut l4: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = rt.global(20);
    let t3 = rt.member(&t2, "get")?;
    let mut t4: Vec<Value> = Vec::with_capacity(0);
    let t5 = rt.call(&t3, t4)?;
    let t6 = t5;
    l1 = t6;
    let t7 = l0.clone();
    let t8 = rt.member(&t7, "ctrlKey")?;
    let t9 = if !t8.truthy() {
        let t10 = l0.clone();
        let t11 = rt.member(&t10, "metaKey")?;
        t11
    } else { t8 };
    let t12 = t9;
    l2 = t12;
    let t13 = l2.clone();
    let t14 = if t13.truthy() {
        let t15 = l0.clone();
        let t16 = rt.member(&t15, "key")?;
        let mut t17: Vec<Value> = Vec::with_capacity(0);
        let t18 = rt.call_method(&t16, Method::StrToLowerCase, t17)?;
        let t19 = Value::Bool(strict_equals(&t18, &str("s")));
        t19
    } else { t13 };
    if t14.truthy() {
        let t20 = l0.clone();
        let mut t21: Vec<Value> = Vec::with_capacity(0);
        let t22 = rt.call_method(&t20, Method::EventPreventDefault, t21)?;
        let _ = t22;
        let mut t23: Vec<Value> = Vec::with_capacity(0);
        let t24 = f6(rt, &[], t23, None)?;
        let _ = t24;
        return Ok(Value::Undefined);
    }
    let mut t25: Vec<Value> = Vec::with_capacity(1);
    let t26 = l0.clone();
    let t27 = rt.member(&t26, "key")?;
    t25.push(t27);
    let t28 = rt.call_builtin(Builtin::ArrayFrom, t25)?;
    let t29 = rt.member(&t28, "length")?;
    let t30 = Value::Bool(strict_equals(&t29, &Value::Num(1.0)));
    let t31 = if t30.truthy() {
        let t32 = l2.clone();
        let t33 = Value::Bool(!t32.truthy());
        t33
    } else { t30 };
    let t34 = if t31.truthy() {
        let t35 = l0.clone();
        let t36 = rt.member(&t35, "altKey")?;
        let t37 = Value::Bool(!t36.truthy());
        t37
    } else { t31 };
    let t38 = t34;
    l3 = t38;
    let t39 = l1.clone();
    let t40 = rt.member(&t39, "open")?;
    let t41 = Value::Bool(strict_equals(&t40, &Value::Null));
    if t41.truthy() {
        let t42 = l0.clone();
        let mut t43: Vec<Value> = Vec::with_capacity(0);
        let t44 = rt.call_method(&t42, Method::EventPreventDefault, t43)?;
        let _ = t44;
        let mut t45: Vec<Value> = Vec::with_capacity(1);
        let t46 = l0.clone();
        let t47 = rt.member(&t46, "key")?;
        let t48 = Value::Bool(strict_equals(&t47, &str("Backspace")));
        let t49 = if !t48.truthy() {
            let t50 = l0.clone();
            let t51 = rt.member(&t50, "key")?;
            let t52 = Value::Bool(strict_equals(&t51, &str("Enter")));
            t52
        } else { t48 };
        let t53 = if t49.truthy() {
            str("no note is open")
        } else {
            let mut t54 = String::new();
            t54.push_str("unsupported notes key ");
            let t55 = l0.clone();
            let t56 = rt.member(&t55, "key")?;
            t54.push_str(&t56.to_js_string());
            let t57 = Value::str(&t54);
            t57
        };
        t45.push(t53);
        let t58 = rt.call_builtin(Builtin::CwRefuse, t45)?;
        let _ = t58;
        return Ok(Value::Undefined);
    }
    let t59 = l0.clone();
    let t60 = rt.member(&t59, "target")?;
    let mut t61: Vec<Value> = Vec::with_capacity(1);
    t61.push(str("notes:body"));
    let t62 = rt.call_builtin(Builtin::GetElementById, t61)?;
    let t63 = Value::Bool(strict_equals(&t60, &t62));
    let t64 = t63;
    l4 = t64;
    let t65 = l4.clone();
    let t66 = Value::Bool(!t65.truthy());
    if t66.truthy() {
        let t67 = l0.clone();
        let t68 = rt.member(&t67, "key")?;
        let t69 = Value::Bool(strict_equals(&t68, &str("Backspace")));
        if t69.truthy() {
            let t70 = l0.clone();
            let mut t71: Vec<Value> = Vec::with_capacity(0);
            let t72 = rt.call_method(&t70, Method::EventPreventDefault, t71)?;
            let _ = t72;
            let mut t73: Vec<Value> = Vec::with_capacity(1);
            let mut t74: Vec<Value> = Vec::with_capacity(1);
            let t75 = l1.clone();
            let t76 = rt.member(&t75, "text")?;
            t74.push(t76);
            let t77 = rt.call_builtin(Builtin::ArrayFrom, t74)?;
            let mut t78: Vec<Value> = Vec::with_capacity(2);
            t78.push(Value::Num(0.0));
            t78.push(Value::Num((-1.0)));
            let t79 = rt.call_method(&t77, Method::ArraySlice, t78)?;
            let mut t80: Vec<Value> = Vec::with_capacity(1);
            t80.push(str(""));
            let t81 = rt.call_method(&t79, Method::ArrayJoin, t80)?;
            t73.push(t81);
            let t82 = f10(rt, &[], t73, None)?;
            let _ = t82;
        } else {
            let t83 = l0.clone();
            let t84 = rt.member(&t83, "key")?;
            let t85 = Value::Bool(strict_equals(&t84, &str("Enter")));
            if t85.truthy() {
                let t86 = l0.clone();
                let mut t87: Vec<Value> = Vec::with_capacity(0);
                let t88 = rt.call_method(&t86, Method::EventPreventDefault, t87)?;
                let _ = t88;
                let mut t89: Vec<Value> = Vec::with_capacity(1);
                let t90 = l1.clone();
                let t91 = rt.member(&t90, "text")?;
                let t92 = add(&t91, &str("\n"));
                t89.push(t92);
                let t93 = f10(rt, &[], t89, None)?;
                let _ = t93;
            } else {
                let t94 = l3.clone();
                if t94.truthy() {
                    let t95 = l0.clone();
                    let mut t96: Vec<Value> = Vec::with_capacity(0);
                    let t97 = rt.call_method(&t95, Method::EventPreventDefault, t96)?;
                    let _ = t97;
                    let mut t98: Vec<Value> = Vec::with_capacity(1);
                    let t99 = l1.clone();
                    let t100 = rt.member(&t99, "text")?;
                    let t101 = l0.clone();
                    let t102 = rt.member(&t101, "key")?;
                    let t103 = add(&t100, &t102);
                    t98.push(t103);
                    let t104 = f10(rt, &[], t98, None)?;
                    let _ = t104;
                } else {
                    let t105 = l0.clone();
                    let mut t106: Vec<Value> = Vec::with_capacity(0);
                    let t107 = rt.call_method(&t105, Method::EventPreventDefault, t106)?;
                    let _ = t107;
                    let mut t108: Vec<Value> = Vec::with_capacity(1);
                    let mut t109 = String::new();
                    t109.push_str("unsupported notes key ");
                    let t110 = l0.clone();
                    let t111 = rt.member(&t110, "key")?;
                    t109.push_str(&t111.to_js_string());
                    let t112 = Value::str(&t109);
                    t108.push(t112);
                    let t113 = rt.call_builtin(Builtin::CwRefuse, t108)?;
                    let _ = t113;
                }
            }
        }
        return Ok(Value::Undefined);
    }
    let t114 = l3.clone();
    let t115 = Value::Bool(!t114.truthy());
    let t116 = if t115.truthy() {
        let t117 = rt.global(21);
        let mut t118: Vec<Value> = Vec::with_capacity(1);
        let t119 = l0.clone();
        let t120 = rt.member(&t119, "key")?;
        t118.push(t120);
        let t121 = rt.call_method(&t117, Method::SetHas, t118)?;
        let t122 = Value::Bool(!t121.truthy());
        t122
    } else { t115 };
    if t116.truthy() {
        let t123 = l0.clone();
        let mut t124: Vec<Value> = Vec::with_capacity(0);
        let t125 = rt.call_method(&t123, Method::EventPreventDefault, t124)?;
        let _ = t125;
        let mut t126: Vec<Value> = Vec::with_capacity(1);
        let mut t127 = String::new();
        t127.push_str("unsupported notes key ");
        let t128 = l0.clone();
        let t129 = rt.member(&t128, "key")?;
        t127.push_str(&t129.to_js_string());
        let t130 = Value::str(&t127);
        t126.push(t130);
        let t131 = rt.call_builtin(Builtin::CwRefuse, t126)?;
        let _ = t131;
    } else {
        let t132 = l0.clone();
        let t133 = rt.member(&t132, "key")?;
        let t134 = Value::Bool(strict_equals(&t133, &str("Backspace")));
        let t135 = if t134.truthy() {
            let t136 = l1.clone();
            let t137 = rt.member(&t136, "text")?;
            let t138 = Value::Bool(strict_equals(&t137, &str("")));
            t138
        } else { t134 };
        if t135.truthy() {
            let t139 = rt.global(20);
            let t140 = rt.member(&t139, "set")?;
            let mut t141: Vec<Value> = Vec::with_capacity(1);
            let mut t142: Vec<(Str, Value)> = Vec::with_capacity(2);
            let t143 = l1.clone();
            obj_spread(&mut t142, &t143);
            obj_put(&mut t142, "dirty", Value::Bool(true));
            let t144 = Value::object(t142);
            t141.push(t144);
            let t145 = rt.call(&t140, t141)?;
            let _ = t145;
        }
    }
    Ok(Value::Undefined)
}

/// `title` (line 180).
fn f12(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = Value::Bool(strict_equals(&t2, &str("windows")));
    let t4 = if t3.truthy() {
        str("Sticky Notes")
    } else {
        let t5 = l0.clone();
        let t6 = Value::Bool(strict_equals(&t5, &str("android")));
        let t7 = if t6.truthy() {
            str("Keep")
        } else {
            str("Notes")
        };
        t7
    };
    return Ok(t4);
    Ok(Value::Undefined)
}

/// `Action` (line 184).
fn f13(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut occ = [0u32; 1];
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = inst.is_some() && rt.is_pure_render();
    let t3 = if t2 { occ[0] += 1; occ[0] } else { 0 };
    let mut t4 = rt.tpl_begin(t2, 0, t3, 9, 4);
    let t5: Vec<Value> = if t4.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t4, 0, false, &t5) {
        Some(v) => rt.tpl_push(&mut t4, v, t5, false),
        None => {
            let t6 = l0.clone();
            let t7 = rt.member(&t6, "id")?;
            rt.tpl_push(&mut t4, t7, t5, true);
        }
    }
    let t8: Vec<Value> = if t4.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t4, 1, false, &t8) {
        Some(v) => rt.tpl_push(&mut t4, v, t8, false),
        None => {
            let mut t9 = String::new();
            t9.push_str("action ");
            let t10 = l0.clone();
            let t11 = rt.member(&t10, "place")?;
            t9.push_str(&t11.to_js_string());
            let t12 = l0.clone();
            let t13 = rt.member(&t12, "primary")?;
            let t14 = if t13.truthy() {
                str(" primary")
            } else {
                str("")
            };
            t9.push_str(&t14.to_js_string());
            let t15 = Value::str(&t9);
            rt.tpl_push(&mut t4, t15, t8, true);
        }
    }
    let t16: Vec<Value> = if t4.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t4, 2, false, &t16) {
        Some(v) => rt.tpl_push(&mut t4, v, t16, false),
        None => {
            let t17 = l0.clone();
            let t18 = rt.member(&t17, "onClick")?;
            rt.tpl_push(&mut t4, t18, t16, true);
        }
    }
    let t19: Vec<Value> = if t4.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t4, 3, false, &t19) {
        Some(v) => rt.tpl_push(&mut t4, v, t19, false),
        None => {
            let t20 = l0.clone();
            let t21 = rt.member(&t20, "label")?;
            rt.tpl_push(&mut t4, t21, t19, true);
        }
    }
    let t22 = rt.tpl_finish(t4, None);
    return Ok(t22);
    Ok(Value::Undefined)
}

/// `List` (line 196).
fn f14(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = t2;
    destructure_check(&t3)?;
    let t4 = rt.member(&t3, "s")?;
    l1 = t4;
    let mut t5: Vec<Value> = Vec::with_capacity(1);
    let t6 = l1.clone();
    let t7 = rt.member(&t6, "entries")?;
    let mut t8: Vec<Value> = Vec::with_capacity(1);
    let t9 = closure(46, vec![l1.clone()]);
    t8.push(t9);
    let t10 = rt.call_method(&t7, Method::ArrayMap, t8)?;
    t5.push(t10);
    let t11 = fragment(t5, None);
    return Ok(t11);
    Ok(Value::Undefined)
}

/// `Notice` (line 216).
fn f15(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let mut occ = [0u32; 2];
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = t2;
    destructure_check(&t3)?;
    let t4 = rt.member(&t3, "s")?;
    l1 = t4;
    let t5 = l1.clone();
    let t6 = rt.member(&t5, "problem")?;
    let t7 = Value::Bool(!strict_equals(&t6, &Value::Null));
    if t7.truthy() {
        let t8 = inst.is_some() && rt.is_pure_render();
        let t9 = if t8 { occ[0] += 1; occ[0] } else { 0 };
        let mut t10 = rt.tpl_begin(t8, 1, t9, 7, 1);
        let t11: Vec<Value> = if t10.caching() { vec![read(&l1)] } else { Vec::new() };
        match rt.tpl_reuse(&t10, 0, false, &t11) {
            Some(v) => rt.tpl_push(&mut t10, v, t11, false),
            None => {
                let t12 = l1.clone();
                let t13 = rt.member(&t12, "problem")?;
                rt.tpl_push(&mut t10, t13, t11, true);
            }
        }
        let t14 = rt.tpl_finish(t10, None);
        return Ok(t14);
    }
    let t15 = l1.clone();
    let t16 = rt.member(&t15, "entries")?;
    let t17 = rt.member(&t16, "length")?;
    let t18 = Value::Bool(strict_equals(&t17, &Value::Num(0.0)));
    let t19 = if t18.truthy() {
        let t20 = inst.is_some() && rt.is_pure_render();
        let t21 = if t20 { occ[1] += 1; occ[1] } else { 0 };
        let mut t22 = rt.tpl_begin(t20, 2, t21, 8, 0);
        let t23 = rt.tpl_finish(t22, None);
        t23
    } else {
        Value::Null
    };
    return Ok(t19);
    Ok(Value::Undefined)
}

/// `Buttons` (line 228).
fn f16(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut occ = [0u32; 1];
    let t1 = inst.is_some() && rt.is_pure_render();
    let t2 = if t1 { occ[0] += 1; occ[0] } else { 0 };
    let mut t3 = rt.tpl_begin(t1, 3, t2, 10, 2);
    let t4: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t3, 0, false, &t4) {
        Some(v) => rt.tpl_push(&mut t3, v, t4, false),
        None => {
            let t5 = rt.global(13);
            let t6 = component_callee(t5)?;
            let mut t7: Vec<(Str, Value)> = Vec::with_capacity(6);
            obj_put(&mut t7, "id", str("notes:new"));
            obj_put(&mut t7, "place", str("new"));
            obj_put(&mut t7, "label", str("New note"));
            obj_put(&mut t7, "primary", Value::Bool(true));
            let t8 = rt.global(7);
            obj_put(&mut t7, "onClick", t8);
            let t9 = None;
            let t10 = component_elem(t6, t7, t9, None);
            rt.tpl_push(&mut t3, t10, t4, true);
        }
    }
    let t11: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t3, 1, false, &t11) {
        Some(v) => rt.tpl_push(&mut t3, v, t11, false),
        None => {
            let t12 = rt.global(13);
            let t13 = component_callee(t12)?;
            let mut t14: Vec<(Str, Value)> = Vec::with_capacity(6);
            obj_put(&mut t14, "id", str("notes:reload"));
            obj_put(&mut t14, "place", str("reload"));
            obj_put(&mut t14, "label", str("Reload"));
            obj_put(&mut t14, "primary", Value::Bool(false));
            let t15 = rt.global(5);
            obj_put(&mut t14, "onClick", t15);
            let t16 = None;
            let t17 = component_elem(t13, t14, t16, None);
            rt.tpl_push(&mut t3, t17, t11, true);
        }
    }
    let t18 = rt.tpl_finish(t3, None);
    return Ok(t18);
    Ok(Value::Undefined)
}

/// `Note` (line 238).
fn f17(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; let mut l2: Value = Value::Undefined; let mut l3: Value = Value::Undefined; let mut l4: Value = Value::Undefined; 
    let mut occ = [0u32; 3];
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = t2;
    destructure_check(&t3)?;
    let t4 = rt.member(&t3, "s")?;
    l1 = t4;
    let t5 = rt.member(&t3, "phone")?;
    l2 = t5;
    let t6 = rt.member(&t3, "heading")?;
    l3 = t6;
    let t7 = l1.clone();
    let t8 = rt.member(&t7, "open")?;
    let t9 = if t8.is_nullish() {
        str("")
    } else { t8 };
    let mut t10: Vec<Value> = Vec::with_capacity(2);
    let t11 = rt.regex("\\.txt$", "")?;
    t10.push(t11);
    t10.push(str(""));
    let t12 = rt.call_method(&t9, Method::StrReplace, t10)?;
    let t13 = t12;
    l4 = t13;
    let t14 = inst.is_some() && rt.is_pure_render();
    let t15 = if t14 { occ[0] += 1; occ[0] } else { 0 };
    let mut t16 = rt.tpl_begin(t14, 4, t15, 3, 12);
    let t17: Vec<Value> = if t16.caching() { vec![read(&l2)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 0, false, &t17) {
        Some(v) => rt.tpl_push(&mut t16, v, t17, false),
        None => {
            let t18 = l2.clone();
            let t19 = if t18.truthy() {
                str("note phone")
            } else {
                str("note")
            };
            rt.tpl_push(&mut t16, t19, t17, true);
        }
    }
    let t20: Vec<Value> = if t16.caching() { vec![read(&l2), read(&l3)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 1, false, &t20) {
        Some(v) => rt.tpl_push(&mut t16, v, t20, false),
        None => {
            let t21 = l2.clone();
            let t22 = if t21.truthy() {
                let t23 = inst.is_some() && rt.is_pure_render();
                let t24 = if t23 { occ[1] += 1; occ[1] } else { 0 };
                let mut t25 = rt.tpl_begin(t23, 5, t24, 1, 2);
                let t26: Vec<Value> = Vec::new();
                match rt.tpl_reuse(&t25, 0, false, &t26) {
                    Some(v) => rt.tpl_push(&mut t25, v, t26, false),
                    None => {
                        let t27 = rt.global(9);
                        rt.tpl_push(&mut t25, t27, t26, true);
                    }
                }
                let t28: Vec<Value> = if t25.caching() { vec![read(&l3)] } else { Vec::new() };
                match rt.tpl_reuse(&t25, 1, false, &t28) {
                    Some(v) => rt.tpl_push(&mut t25, v, t28, false),
                    None => {
                        let t29 = l3.clone();
                        rt.tpl_push(&mut t25, t29, t28, true);
                    }
                }
                let t30 = rt.tpl_finish(t25, None);
                t30
            } else { t21 };
            rt.tpl_push(&mut t16, t22, t20, true);
        }
    }
    let t31: Vec<Value> = if t16.caching() { vec![read(&l4)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 2, false, &t31) {
        Some(v) => rt.tpl_push(&mut t16, v, t31, false),
        None => {
            let t32 = l4.clone();
            rt.tpl_push(&mut t16, t32, t31, true);
        }
    }
    let t33: Vec<Value> = if t16.caching() { vec![read(&l1)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 3, false, &t33) {
        Some(v) => rt.tpl_push(&mut t16, v, t33, false),
        None => {
            let t34 = l1.clone();
            let t35 = rt.member(&t34, "text")?;
            rt.tpl_push(&mut t16, t35, t33, true);
        }
    }
    let t36: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t16, 4, false, &t36) {
        Some(v) => rt.tpl_push(&mut t16, v, t36, false),
        None => {
            let t37 = rt.global(19);
            rt.tpl_push(&mut t16, t37, t36, true);
        }
    }
    let t38: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t16, 5, false, &t38) {
        Some(v) => rt.tpl_push(&mut t16, v, t38, false),
        None => {
            rt.tpl_push(&mut t16, Value::Bool(false), t38, true);
        }
    }
    let t39: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t16, 6, true, &t39) {
        Some(v) => rt.tpl_push(&mut t16, v, t39, false),
        None => {
            let t40 = closure(42, vec![]);
            rt.tpl_push(&mut t16, t40, t39, true);
        }
    }
    let t41: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t16, 7, false, &t41) {
        Some(v) => rt.tpl_push(&mut t16, v, t41, false),
        None => {
            let t42 = closure(43, vec![]);
            rt.tpl_push(&mut t16, t42, t41, true);
        }
    }
    let t43: Vec<Value> = if t16.caching() { vec![read(&l1)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 8, false, &t43) {
        Some(v) => rt.tpl_push(&mut t16, v, t43, false),
        None => {
            let t44 = l1.clone();
            let t45 = rt.member(&t44, "text")?;
            let t46 = Value::Bool(strict_equals(&t45, &str("")));
            let t47 = if t46.truthy() {
                let t48 = inst.is_some() && rt.is_pure_render();
                let t49 = if t48 { occ[2] += 1; occ[2] } else { 0 };
                let mut t50 = rt.tpl_begin(t48, 6, t49, 2, 0);
                let t51 = rt.tpl_finish(t50, None);
                t51
            } else { t46 };
            rt.tpl_push(&mut t16, t47, t43, true);
        }
    }
    let t52: Vec<Value> = if t16.caching() { vec![read(&l1)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 9, false, &t52) {
        Some(v) => rt.tpl_push(&mut t16, v, t52, false),
        None => {
            let t53 = l1.clone();
            let t54 = rt.member(&t53, "dirty")?;
            let t55 = if t54.truthy() {
                str("action primary save")
            } else {
                str("action save")
            };
            rt.tpl_push(&mut t16, t55, t52, true);
        }
    }
    let t56: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t16, 10, false, &t56) {
        Some(v) => rt.tpl_push(&mut t16, v, t56, false),
        None => {
            let t57 = rt.global(6);
            rt.tpl_push(&mut t16, t57, t56, true);
        }
    }
    let t58: Vec<Value> = if t16.caching() { vec![read(&l1)] } else { Vec::new() };
    match rt.tpl_reuse(&t16, 11, false, &t58) {
        Some(v) => rt.tpl_push(&mut t16, v, t58, false),
        None => {
            let t59 = l1.clone();
            let t60 = rt.member(&t59, "dirty")?;
            let t61 = if t60.truthy() {
                str("Save •")
            } else {
                str("Save")
            };
            rt.tpl_push(&mut t16, t61, t58, true);
        }
    }
    let t62 = rt.tpl_finish(t16, None);
    return Ok(t62);
    Ok(Value::Undefined)
}

/// `Notes` (line 283).
fn f18(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; let mut l2: Value = Value::Undefined; let mut l3: Value = Value::Undefined; let mut l4: Value = Value::Undefined; let mut l5: Value = Value::Undefined; let mut l6: Value = Value::Undefined; 
    let mut occ = [0u32; 8];
    let mut t1: Vec<Value> = Vec::with_capacity(1);
    let t2 = rt.global(20);
    t1.push(t2);
    let t3 = f1(rt, &[], t1, None)?;
    let t4 = t3;
    l0 = t4;
    let mut t5: Vec<Value> = Vec::with_capacity(0);
    let t6 = f2(rt, &[], t5, None)?;
    let t7 = t6;
    l1 = t7;
    let t8 = l1.clone();
    let t9 = rt.member(&t8, "mobile")?;
    let t10 = if !t9.truthy() {
        let t11 = l1.clone();
        let t12 = rt.member(&t11, "width")?;
        let t13 = Value::Bool(compare(BinaryOp::Lt, &t12, &Value::Num(480.0)));
        t13
    } else { t9 };
    let t14 = t10;
    l2 = t14;
    let mut t15: Vec<Value> = Vec::with_capacity(1);
    let t16 = l1.clone();
    let t17 = rt.member(&t16, "platform")?;
    t15.push(t17);
    let t18 = f12(rt, &[], t15, None)?;
    let t19 = t18;
    l3 = t19;
    let t21 = rt.hook_with(Hook::Ref, 1, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                Ok(Value::Null)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t20 = t21?;
    let t22 = t20;
    l4 = t22;
    let t23 = l0.clone();
    let t24 = rt.member(&t23, "open")?;
    let t25 = Value::Bool(!strict_equals(&t24, &Value::Null));
    let t26 = if t25.truthy() {
        let t27 = l0.clone();
        let t28 = rt.member(&t27, "editing")?;
        let t29 = if !t28.truthy() {
            let t30 = l1.clone();
            let t31 = rt.member(&t30, "mobile")?;
            let t32 = Value::Bool(!t31.truthy());
            t32
        } else { t28 };
        t29
    } else { t25 };
    let t33 = t26;
    l5 = t33;
    let t35 = rt.hook_with(Hook::LayoutEffect, 1, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t36 = closure(27, vec![l4.clone(), l5.clone()]);
                Ok(t36)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t34 = t35?;
    let _ = t34;
    let t38 = rt.hook_with(Hook::Effect, 2, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t39 = closure(28, vec![l4.clone(), l5.clone()]);
                Ok(t39)
            }
            1 => {
                let mut t40: Vec<Value> = Vec::with_capacity(1);
                let t41 = l5.clone();
                t40.push(t41);
                let t42 = Value::array(t40);
                Ok(t42)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t37 = t38?;
    let _ = t37;
    let t44 = rt.hook_with(Hook::Effect, 2, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t45 = closure(31, vec![]);
                Ok(t45)
            }
            1 => {
                let mut t46: Vec<Value> = Vec::with_capacity(0);
                let t47 = Value::array(t46);
                Ok(t47)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t43 = t44?;
    let _ = t43;
    let t49 = rt.hook_with(Hook::Effect, 2, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t50 = closure(37, vec![]);
                Ok(t50)
            }
            1 => {
                let mut t51: Vec<Value> = Vec::with_capacity(0);
                let t52 = Value::array(t51);
                Ok(t52)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t48 = t49?;
    let _ = t48;
    let t54 = rt.hook_with(Hook::Effect, 2, &mut |rt: &mut Runtime, i: usize| -> R<Value> {
        match i {
            0 => {
                let t55 = closure(40, vec![l0.clone()]);
                Ok(t55)
            }
            1 => {
                let mut t56: Vec<Value> = Vec::with_capacity(3);
                let t57 = l0.clone();
                let t58 = rt.member(&t57, "folder")?;
                t56.push(t58);
                let t59 = l0.clone();
                let t60 = rt.member(&t59, "open")?;
                t56.push(t60);
                let t61 = l0.clone();
                let t62 = rt.member(&t61, "dirty")?;
                t56.push(t62);
                let t63 = Value::array(t56);
                Ok(t63)
            }
            _ => Ok(Value::Undefined),
        }
    });
    let t53 = t54?;
    let _ = t53;
    let t64 = inst.is_some() && rt.is_pure_render();
    let t65 = if t64 { occ[0] += 1; occ[0] } else { 0 };
    let mut t66 = rt.tpl_begin(t64, 7, t65, 0, 2);
    let t67: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t66, 0, false, &t67) {
        Some(v) => rt.tpl_push(&mut t66, v, t67, false),
        None => {
            rt.tpl_push(&mut t66, Value::Bool(true), t67, true);
        }
    }
    let t68: Vec<Value> = if t66.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t66, 1, false, &t68) {
        Some(v) => rt.tpl_push(&mut t66, v, t68, false),
        None => {
            let t69 = l0.clone();
            let t70 = rt.member(&t69, "folder")?;
            rt.tpl_push(&mut t66, t70, t68, true);
        }
    }
    let t71 = rt.tpl_finish(t66, None);
    let t72 = t71;
    l6 = t72;
    let t73 = l2.clone();
    let t74 = if t73.truthy() {
        let t75 = l0.clone();
        let t76 = rt.member(&t75, "open")?;
        let t77 = Value::Bool(!strict_equals(&t76, &Value::Null));
        t77
    } else { t73 };
    if t74.truthy() {
        let t78 = inst.is_some() && rt.is_pure_render();
        let t79 = if t78 { occ[1] += 1; occ[1] } else { 0 };
        let mut t80 = rt.tpl_begin(t78, 8, t79, 4, 2);
        let t81: Vec<Value> = if t80.caching() { vec![read(&l6)] } else { Vec::new() };
        match rt.tpl_reuse(&t80, 0, false, &t81) {
            Some(v) => rt.tpl_push(&mut t80, v, t81, false),
            None => {
                let t82 = l6.clone();
                rt.tpl_push(&mut t80, t82, t81, true);
            }
        }
        let t83: Vec<Value> = if t80.caching() { vec![read(&l0), read(&l3)] } else { Vec::new() };
        match rt.tpl_reuse(&t80, 1, false, &t83) {
            Some(v) => rt.tpl_push(&mut t80, v, t83, false),
            None => {
                let t84 = rt.global(17);
                let t85 = component_callee(t84)?;
                let mut t86: Vec<(Str, Value)> = Vec::with_capacity(4);
                let t87 = l0.clone();
                obj_put(&mut t86, "s", t87);
                obj_put(&mut t86, "phone", Value::Bool(true));
                let t88 = l3.clone();
                obj_put(&mut t86, "heading", t88);
                let t89 = None;
                let t90 = component_elem(t85, t86, t89, None);
                rt.tpl_push(&mut t80, t90, t83, true);
            }
        }
        let t91 = rt.tpl_finish(t80, None);
        return Ok(t91);
    }
    let t92 = l1.clone();
    let t93 = rt.member(&t92, "mobile")?;
    if t93.truthy() {
        let t94 = inst.is_some() && rt.is_pure_render();
        let t95 = if t94 { occ[2] += 1; occ[2] } else { 0 };
        let mut t96 = rt.tpl_begin(t94, 9, t95, 12, 9);
        let t97: Vec<Value> = if t96.caching() { vec![read(&l1)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 0, false, &t97) {
            Some(v) => rt.tpl_push(&mut t96, v, t97, false),
            None => {
                let mut t98 = String::new();
                t98.push_str("app narrow ");
                let t99 = l1.clone();
                let t100 = rt.member(&t99, "platform")?;
                t98.push_str(&t100.to_js_string());
                let t101 = Value::str(&t98);
                rt.tpl_push(&mut t96, t101, t97, true);
            }
        }
        let t102: Vec<Value> = if t96.caching() { vec![read(&l6)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 1, false, &t102) {
            Some(v) => rt.tpl_push(&mut t96, v, t102, false),
            None => {
                let t103 = l6.clone();
                rt.tpl_push(&mut t96, t103, t102, true);
            }
        }
        let t104: Vec<Value> = if t96.caching() { vec![read(&l1), read(&l3)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 2, false, &t104) {
            Some(v) => rt.tpl_push(&mut t96, v, t104, false),
            None => {
                let t105 = l1.clone();
                let t106 = rt.member(&t105, "platform")?;
                let t107 = Value::Bool(strict_equals(&t106, &str("android")));
                let t108 = if t107.truthy() {
                    let t109 = inst.is_some() && rt.is_pure_render();
                    let t110 = if t109 { occ[3] += 1; occ[3] } else { 0 };
                    let mut t111 = rt.tpl_begin(t109, 10, t110, 5, 1);
                    let t112: Vec<Value> = if t111.caching() { vec![read(&l3)] } else { Vec::new() };
                    match rt.tpl_reuse(&t111, 0, false, &t112) {
                        Some(v) => rt.tpl_push(&mut t111, v, t112, false),
                        None => {
                            let t113 = l3.clone();
                            rt.tpl_push(&mut t111, t113, t112, true);
                        }
                    }
                    let t114 = rt.tpl_finish(t111, None);
                    t114
                } else { t107 };
                rt.tpl_push(&mut t96, t108, t104, true);
            }
        }
        let t115: Vec<Value> = if t96.caching() { vec![read(&l1), read(&l3)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 3, false, &t115) {
            Some(v) => rt.tpl_push(&mut t96, v, t115, false),
            None => {
                let t116 = l1.clone();
                let t117 = rt.member(&t116, "platform")?;
                let t118 = Value::Bool(strict_equals(&t117, &str("ios")));
                let t119 = if t118.truthy() {
                    let t120 = l3.clone();
                    t120
                } else {
                    Value::Undefined
                };
                rt.tpl_push(&mut t96, t119, t115, true);
            }
        }
        let t121: Vec<Value> = if t96.caching() { vec![read(&l1)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 4, false, &t121) {
            Some(v) => rt.tpl_push(&mut t96, v, t121, false),
            None => {
                let t122 = l1.clone();
                let t123 = rt.member(&t122, "platform")?;
                let t124 = Value::Bool(strict_equals(&t123, &str("ios")));
                let t125 = if t124.truthy() {
                    str("52")
                } else {
                    Value::Undefined
                };
                rt.tpl_push(&mut t96, t125, t121, true);
            }
        }
        let t126: Vec<Value> = if t96.caching() { vec![read(&l1), read(&l3)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 5, false, &t126) {
            Some(v) => rt.tpl_push(&mut t96, v, t126, false),
            None => {
                let t127 = l1.clone();
                let t128 = rt.member(&t127, "platform")?;
                let t129 = Value::Bool(strict_equals(&t128, &str("ios")));
                let t130 = if t129.truthy() {
                    let t131 = inst.is_some() && rt.is_pure_render();
                    let t132 = if t131 { occ[4] += 1; occ[4] } else { 0 };
                    let mut t133 = rt.tpl_begin(t131, 11, t132, 6, 1);
                    let t134: Vec<Value> = if t133.caching() { vec![read(&l3)] } else { Vec::new() };
                    match rt.tpl_reuse(&t133, 0, false, &t134) {
                        Some(v) => rt.tpl_push(&mut t133, v, t134, false),
                        None => {
                            let t135 = l3.clone();
                            rt.tpl_push(&mut t133, t135, t134, true);
                        }
                    }
                    let t136 = rt.tpl_finish(t133, None);
                    t136
                } else { t129 };
                rt.tpl_push(&mut t96, t130, t126, true);
            }
        }
        let t137: Vec<Value> = if t96.caching() { vec![read(&l0)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 6, false, &t137) {
            Some(v) => rt.tpl_push(&mut t96, v, t137, false),
            None => {
                let t138 = rt.global(15);
                let t139 = component_callee(t138)?;
                let mut t140: Vec<(Str, Value)> = Vec::with_capacity(2);
                let t141 = l0.clone();
                obj_put(&mut t140, "s", t141);
                let t142 = None;
                let t143 = component_elem(t139, t140, t142, None);
                rt.tpl_push(&mut t96, t143, t137, true);
            }
        }
        let t144: Vec<Value> = Vec::new();
        match rt.tpl_reuse(&t96, 7, false, &t144) {
            Some(v) => rt.tpl_push(&mut t96, v, t144, false),
            None => {
                let t145 = rt.global(16);
                let t146 = component_callee(t145)?;
                let mut t147: Vec<(Str, Value)> = Vec::with_capacity(1);
                let t148 = None;
                let t149 = component_elem(t146, t147, t148, None);
                rt.tpl_push(&mut t96, t149, t144, true);
            }
        }
        let t150: Vec<Value> = if t96.caching() { vec![read(&l0)] } else { Vec::new() };
        match rt.tpl_reuse(&t96, 8, false, &t150) {
            Some(v) => rt.tpl_push(&mut t96, v, t150, false),
            None => {
                let t151 = rt.global(14);
                let t152 = component_callee(t151)?;
                let mut t153: Vec<(Str, Value)> = Vec::with_capacity(2);
                let t154 = l0.clone();
                obj_put(&mut t153, "s", t154);
                let t155 = None;
                let t156 = component_elem(t152, t153, t155, None);
                rt.tpl_push(&mut t96, t156, t150, true);
            }
        }
        let t157 = rt.tpl_finish(t96, None);
        return Ok(t157);
    }
    let t158 = inst.is_some() && rt.is_pure_render();
    let t159 = if t158 { occ[5] += 1; occ[5] } else { 0 };
    let mut t160 = rt.tpl_begin(t158, 12, t159, 15, 7);
    let t161: Vec<Value> = if t160.caching() { vec![read(&l2)] } else { Vec::new() };
    match rt.tpl_reuse(&t160, 0, false, &t161) {
        Some(v) => rt.tpl_push(&mut t160, v, t161, false),
        None => {
            let t162 = l2.clone();
            let t163 = if t162.truthy() {
                str("app desktop narrow")
            } else {
                str("app desktop")
            };
            rt.tpl_push(&mut t160, t163, t161, true);
        }
    }
    let t164: Vec<Value> = if t160.caching() { vec![read(&l6)] } else { Vec::new() };
    match rt.tpl_reuse(&t160, 1, false, &t164) {
        Some(v) => rt.tpl_push(&mut t160, v, t164, false),
        None => {
            let t165 = l6.clone();
            rt.tpl_push(&mut t160, t165, t164, true);
        }
    }
    let t166: Vec<Value> = if t160.caching() { vec![read(&l3)] } else { Vec::new() };
    match rt.tpl_reuse(&t160, 2, false, &t166) {
        Some(v) => rt.tpl_push(&mut t160, v, t166, false),
        None => {
            let t167 = l3.clone();
            rt.tpl_push(&mut t160, t167, t166, true);
        }
    }
    let t168: Vec<Value> = if t160.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t160, 3, false, &t168) {
        Some(v) => rt.tpl_push(&mut t160, v, t168, false),
        None => {
            let t169 = rt.global(15);
            let t170 = component_callee(t169)?;
            let mut t171: Vec<(Str, Value)> = Vec::with_capacity(2);
            let t172 = l0.clone();
            obj_put(&mut t171, "s", t172);
            let t173 = None;
            let t174 = component_elem(t170, t171, t173, None);
            rt.tpl_push(&mut t160, t174, t168, true);
        }
    }
    let t175: Vec<Value> = Vec::new();
    match rt.tpl_reuse(&t160, 4, false, &t175) {
        Some(v) => rt.tpl_push(&mut t160, v, t175, false),
        None => {
            let t176 = rt.global(16);
            let t177 = component_callee(t176)?;
            let mut t178: Vec<(Str, Value)> = Vec::with_capacity(1);
            let t179 = None;
            let t180 = component_elem(t177, t178, t179, None);
            rt.tpl_push(&mut t160, t180, t175, true);
        }
    }
    let t181: Vec<Value> = if t160.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t160, 5, false, &t181) {
        Some(v) => rt.tpl_push(&mut t160, v, t181, false),
        None => {
            let t182 = rt.global(14);
            let t183 = component_callee(t182)?;
            let mut t184: Vec<(Str, Value)> = Vec::with_capacity(2);
            let t185 = l0.clone();
            obj_put(&mut t184, "s", t185);
            let t186 = None;
            let t187 = component_elem(t183, t184, t186, None);
            rt.tpl_push(&mut t160, t187, t181, true);
        }
    }
    let t188: Vec<Value> = if t160.caching() { vec![read(&l0), read(&l2), read(&l3)] } else { Vec::new() };
    match rt.tpl_reuse(&t160, 6, false, &t188) {
        Some(v) => rt.tpl_push(&mut t160, v, t188, false),
        None => {
            let t189 = l2.clone();
            let t190 = Value::Bool(!t189.truthy());
            let t191 = if t190.truthy() {
                let t192 = inst.is_some() && rt.is_pure_render();
                let t193 = if t192 { occ[6] += 1; occ[6] } else { 0 };
                let mut t194 = rt.tpl_begin(t192, 13, t193, 14, 1);
                let t195: Vec<Value> = if t194.caching() { vec![read(&l0), read(&l3)] } else { Vec::new() };
                match rt.tpl_reuse(&t194, 0, false, &t195) {
                    Some(v) => rt.tpl_push(&mut t194, v, t195, false),
                    None => {
                        let t196 = l0.clone();
                        let t197 = rt.member(&t196, "open")?;
                        let t198 = Value::Bool(!strict_equals(&t197, &Value::Null));
                        let t199 = if t198.truthy() {
                            let t200 = rt.global(17);
                            let t201 = component_callee(t200)?;
                            let mut t202: Vec<(Str, Value)> = Vec::with_capacity(4);
                            let t203 = l0.clone();
                            obj_put(&mut t202, "s", t203);
                            obj_put(&mut t202, "phone", Value::Bool(false));
                            let t204 = l3.clone();
                            obj_put(&mut t202, "heading", t204);
                            let t205 = None;
                            let t206 = component_elem(t201, t202, t205, None);
                            t206
                        } else {
                            let t207 = inst.is_some() && rt.is_pure_render();
                            let t208 = if t207 { occ[7] += 1; occ[7] } else { 0 };
                            let mut t209 = rt.tpl_begin(t207, 14, t208, 13, 0);
                            let t210 = rt.tpl_finish(t209, None);
                            t210
                        };
                        rt.tpl_push(&mut t194, t199, t195, true);
                    }
                }
                let t211 = rt.tpl_finish(t194, None);
                t211
            } else { t190 };
            rt.tpl_push(&mut t160, t191, t188, true);
        }
    }
    let t212 = rt.tpl_finish(t160, None);
    return Ok(t212);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 26).
fn f19(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<Value> = Vec::with_capacity(2);
    let t3 = l0.clone();
    t2.push(t3);
    let t4 = read(&cap[0]);
    let t5 = rt.member(&t4, "current")?;
    t2.push(t5);
    let t6 = rt.call_builtin(Builtin::ObjectIs, t2)?;
    if t6.truthy() {
        return Ok(Value::Undefined);
    }
    let t7 = l0.clone();
    let t8 = t7;
    let t9 = read(&cap[0]);
    let t10 = t8.clone();
    rt.put_member(&t9, "current", t10)?;
    let _ = t8;
    let mut t11: Vec<Value> = Vec::with_capacity(1);
    let t12 = l0.clone();
    t11.push(t12);
    let t13 = rt.call_builtin(Builtin::CwStateSet, t11)?;
    let _ = t13;
    let mut t14: Vec<Value> = Vec::with_capacity(1);
    let t15 = read(&cap[1]);
    t14.push(t15);
    let t16 = rt.call_builtin(Builtin::ArrayFrom, t14)?;
    let t17 = rt.items_of(&t16)?;
    'l1: for t18 in t17 {
        l1 = t18;
        'b1: {
            let t19 = l1.clone();
            let mut t20: Vec<Value> = Vec::with_capacity(0);
            let t21 = rt.call(&t19, t20)?;
            let _ = t21;
        }
    }
    Ok(Value::Undefined)
}

/// `<arrow>` (line 34).
fn f20(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let t1 = read(&cap[0]);
    let t2 = rt.member(&t1, "current")?;
    return Ok(t2);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 36).
fn f21(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = read(&cap[0]);
    let mut t3: Vec<Value> = Vec::with_capacity(1);
    let t4 = l0.clone();
    let mut t5: Vec<Value> = Vec::with_capacity(1);
    let t6 = read(&cap[1]);
    let t7 = rt.member(&t6, "current")?;
    t5.push(t7);
    let t8 = rt.call(&t4, t5)?;
    t3.push(t8);
    let t9 = rt.call(&t2, t3)?;
    return Ok(t9);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 37).
fn f22(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = read(&cap[0]);
    let mut t3: Vec<Value> = Vec::with_capacity(1);
    let t4 = l0.clone();
    t3.push(t4);
    let t5 = rt.call_method(&t2, Method::SetAdd, t3)?;
    let _ = t5;
    let t6 = closure(23, vec![cap[0].clone(), l0.clone()]);
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 39).
fn f23(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let t1 = read(&cap[0]);
    let mut t2: Vec<Value> = Vec::with_capacity(1);
    let t3 = read(&cap[1]);
    t2.push(t3);
    let t4 = rt.call_method(&t1, Method::SetDelete, t2)?;
    let _ = t4;
    Ok(Value::Undefined)
}

/// `<arrow>` (line 28).
fn f24(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<(Str, Value)> = Vec::with_capacity(7);
    let mut t2: Vec<Value> = Vec::with_capacity(0);
    let t3 = rt.call_builtin(Builtin::CwArgument, t2)?;
    let t4 = if t3.truthy() {
        let mut t5: Vec<Value> = Vec::with_capacity(0);
        let t6 = rt.call_builtin(Builtin::CwArgument, t5)?;
        let mut t7: Vec<Value> = Vec::with_capacity(2);
        let t8 = rt.regex("\\/+$", "")?;
        t7.push(t8);
        t7.push(str(""));
        let t9 = rt.call_method(&t6, Method::StrReplace, t7)?;
        t9
    } else {
        str("Notes")
    };
    obj_put(&mut t1, "folder", t4);
    let mut t10: Vec<Value> = Vec::with_capacity(0);
    let t11 = Value::array(t10);
    obj_put(&mut t1, "entries", t11);
    obj_put(&mut t1, "open", Value::Null);
    obj_put(&mut t1, "text", str(""));
    obj_put(&mut t1, "dirty", Value::Bool(false));
    obj_put(&mut t1, "problem", Value::Null);
    obj_put(&mut t1, "editing", Value::Bool(false));
    let t12 = Value::object(t1);
    return Ok(t12);
    Ok(Value::Undefined)
}

/// `<root>` (line 397).
fn f25(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let t1 = rt.global(18);
    let t2 = component_callee(t1)?;
    let mut t3: Vec<(Str, Value)> = Vec::with_capacity(1);
    let t4 = None;
    let t5 = component_elem(t2, t3, t4, None);
    return Ok(t5);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 54).
fn f26(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<Value> = Vec::with_capacity(1);
    let t2 = read(&cap[0]);
    t1.push(t2);
    let t3 = rt.call_builtin(Builtin::CwOnEnv, t1)?;
    return Ok(t3);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 294).
fn f27(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; let mut l1: Value = Value::Undefined; 
    let mut t1: Vec<Value> = Vec::with_capacity(1);
    t1.push(str("notes:body"));
    let t2 = rt.call_builtin(Builtin::GetElementById, t1)?;
    let t3 = t2;
    l0 = t3;
    let t4 = l0.clone();
    let t5 = t4;
    let t6 = read(&cap[0]);
    let t7 = t5.clone();
    rt.put_member(&t6, "current", t7)?;
    let _ = t5;
    let t8 = read(&cap[1]);
    let t9 = if t8.truthy() {
        let t10 = l0.clone();
        t10
    } else { t8 };
    let t11 = if t9.truthy() {
        let mut t12: Vec<Value> = Vec::with_capacity(0);
        let t13 = rt.call_builtin(Builtin::ActiveElement, t12)?;
        let t14 = l0.clone();
        let t15 = Value::Bool(!strict_equals(&t13, &t14));
        t15
    } else { t9 };
    if t11.truthy() {
        let t16 = l0.clone();
        let mut t17: Vec<Value> = Vec::with_capacity(0);
        let t18 = rt.call_method(&t16, Method::NodeFocus, t17)?;
        let _ = t18;
        let t19 = l0.clone();
        let t20 = rt.member(&t19, "value")?;
        let t21 = rt.member(&t20, "length")?;
        let t22 = t21;
        l1 = t22;
        let t23 = l0.clone();
        let mut t24: Vec<Value> = Vec::with_capacity(2);
        let t25 = l1.clone();
        t24.push(t25);
        let t26 = l1.clone();
        t24.push(t26);
        let t27 = rt.call_method(&t23, Method::NodeSetSelectionRange, t24)?;
        let _ = t27;
    } else {
        let t28 = read(&cap[1]);
        let t29 = Value::Bool(!t28.truthy());
        let t30 = if t29.truthy() {
            let t31 = l0.clone();
            t31
        } else { t29 };
        let t32 = if t30.truthy() {
            let mut t33: Vec<Value> = Vec::with_capacity(0);
            let t34 = rt.call_builtin(Builtin::ActiveElement, t33)?;
            let t35 = l0.clone();
            let t36 = Value::Bool(strict_equals(&t34, &t35));
            t36
        } else { t30 };
        if t32.truthy() {
            let t37 = l0.clone();
            let mut t38: Vec<Value> = Vec::with_capacity(0);
            let t39 = rt.call_method(&t37, Method::NodeBlur, t38)?;
            let _ = t39;
        }
    }
    Ok(Value::Undefined)
}

/// `<arrow>` (line 306).
fn f28(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let t1 = closure(29, vec![cap[0].clone(), cap[1].clone()]);
    let t2 = t1;
    l0 = t2;
    let mut t3: Vec<Value> = Vec::with_capacity(2);
    t3.push(str("focusin"));
    let t4 = l0.clone();
    t3.push(t4);
    let t5 = rt.call_builtin(Builtin::DocumentAddListener, t3)?;
    let _ = t5;
    let t6 = closure(30, vec![l0.clone()]);
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 307).
fn f29(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let t1 = read(&cap[0]);
    let t2 = rt.member(&t1, "current")?;
    let t3 = t2;
    l0 = t3;
    let t4 = read(&cap[1]);
    let t5 = if t4.truthy() {
        let t6 = l0.clone();
        t6
    } else { t4 };
    let t7 = if t5.truthy() {
        let mut t8: Vec<Value> = Vec::with_capacity(0);
        let t9 = rt.call_builtin(Builtin::ActiveElement, t8)?;
        let t10 = l0.clone();
        let t11 = Value::Bool(!strict_equals(&t9, &t10));
        t11
    } else { t5 };
    if t7.truthy() {
        let t12 = l0.clone();
        let mut t13: Vec<Value> = Vec::with_capacity(0);
        let t14 = rt.call_method(&t12, Method::NodeFocus, t13)?;
        let _ = t14;
    }
    Ok(Value::Undefined)
}

/// `<arrow>` (line 312).
fn f30(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<Value> = Vec::with_capacity(2);
    t1.push(str("focusin"));
    let t2 = read(&cap[0]);
    t1.push(t2);
    let t3 = rt.call_builtin(Builtin::DocumentRemoveListener, t1)?;
    return Ok(t3);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 315).
fn f31(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let t1 = rt.global(20);
    let t2 = rt.member(&t1, "restored")?;
    let t3 = Value::Bool(!t2.truthy());
    if t3.truthy() {
        let mut t4: Vec<Value> = Vec::with_capacity(0);
        let t5 = f5(rt, &[], t4, None)?;
        let _ = t5;
    }
    Ok(Value::Undefined)
}

/// `<arrow>` (line 56).
fn f32(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = rt.global(20);
    let t3 = rt.member(&t2, "update")?;
    let mut t4: Vec<Value> = Vec::with_capacity(1);
    let t5 = closure(33, vec![l0.clone()]);
    t4.push(t5);
    let t6 = rt.call(&t3, t4)?;
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 57).
fn f33(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<(Str, Value)> = Vec::with_capacity(3);
    let t3 = l0.clone();
    obj_spread(&mut t2, &t3);
    let t4 = read(&cap[0]);
    let mut t5: Vec<Value> = Vec::with_capacity(1);
    let t6 = closure(34, vec![]);
    t5.push(t6);
    let t7 = rt.call_method(&t4, Method::ArrayFilter, t5)?;
    obj_put(&mut t2, "entries", t7);
    obj_put(&mut t2, "problem", Value::Null);
    let t8 = Value::object(t2);
    return Ok(t8);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 59).
fn f34(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let mut t3: Vec<Value> = Vec::with_capacity(1);
    t3.push(str("/"));
    let t4 = rt.call_method(&t2, Method::StrEndsWith, t3)?;
    let t5 = Value::Bool(!t4.truthy());
    return Ok(t5);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 62).
fn f35(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = rt.global(20);
    let t3 = rt.member(&t2, "update")?;
    let mut t4: Vec<Value> = Vec::with_capacity(1);
    let t5 = closure(36, vec![l0.clone()]);
    t4.push(t5);
    let t6 = rt.call(&t3, t4)?;
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 62).
fn f36(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<(Str, Value)> = Vec::with_capacity(2);
    let t3 = l0.clone();
    obj_spread(&mut t2, &t3);
    let mut t4: Vec<Value> = Vec::with_capacity(1);
    let t5 = read(&cap[0]);
    t4.push(t5);
    let t6 = f4(rt, &[], t4, None)?;
    obj_put(&mut t2, "problem", t6);
    let t7 = Value::object(t2);
    return Ok(t7);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 318).
fn f37(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<Value> = Vec::with_capacity(2);
    t1.push(str("keydown"));
    let t2 = rt.global(11);
    t1.push(t2);
    let t3 = rt.call_builtin(Builtin::DocumentAddListener, t1)?;
    let _ = t3;
    let t4 = closure(39, vec![]);
    return Ok(t4);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 115).
fn f38(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<(Str, Value)> = Vec::with_capacity(3);
    let t3 = l0.clone();
    obj_spread(&mut t2, &t3);
    let t4 = read(&cap[0]);
    let mut t5: Vec<Value> = Vec::with_capacity(2);
    t5.push(Value::Num(0.0));
    let t6 = rt.global(19);
    t5.push(t6);
    let t7 = rt.call_method(&t4, Method::StrSlice, t5)?;
    obj_put(&mut t2, "text", t7);
    obj_put(&mut t2, "dirty", Value::Bool(true));
    let t8 = Value::object(t2);
    return Ok(t8);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 320).
fn f39(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<Value> = Vec::with_capacity(2);
    t1.push(str("keydown"));
    let t2 = rt.global(11);
    t1.push(t2);
    let t3 = rt.call_builtin(Builtin::DocumentRemoveListener, t1)?;
    return Ok(t3);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 322).
fn f40(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<Value> = Vec::with_capacity(1);
    let mut t2: Vec<(Str, Value)> = Vec::with_capacity(3);
    let t3 = read(&cap[0]);
    let t4 = rt.member(&t3, "open")?;
    let t5 = Value::Bool(strict_equals(&t4, &Value::Null));
    let t6 = if t5.truthy() {
        str("")
    } else {
        let mut t7 = String::new();
        let t8 = read(&cap[0]);
        let t9 = rt.member(&t8, "folder")?;
        t7.push_str(&t9.to_js_string());
        t7.push_str("/");
        let t10 = read(&cap[0]);
        let t11 = rt.member(&t10, "open")?;
        t7.push_str(&t11.to_js_string());
        let t12 = Value::str(&t7);
        t12
    };
    obj_put(&mut t2, "document", t6);
    let t13 = read(&cap[0]);
    let t14 = rt.member(&t13, "open")?;
    let t15 = if t14.is_nullish() {
        str("")
    } else { t14 };
    obj_put(&mut t2, "caption", t15);
    let t16 = read(&cap[0]);
    let t17 = rt.member(&t16, "dirty")?;
    obj_put(&mut t2, "modified", t17);
    let t18 = Value::object(t2);
    t1.push(t18);
    let t19 = rt.call_builtin(Builtin::CwWindowSet, t1)?;
    let _ = t19;
    Ok(Value::Undefined)
}

/// `<arrow>` (line 111).
fn f41(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<(Str, Value)> = Vec::with_capacity(5);
    let t3 = l0.clone();
    obj_spread(&mut t2, &t3);
    obj_put(&mut t2, "open", Value::Null);
    obj_put(&mut t2, "editing", Value::Bool(false));
    obj_put(&mut t2, "text", str(""));
    obj_put(&mut t2, "dirty", Value::Bool(false));
    let t4 = Value::object(t2);
    return Ok(t4);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 268).
fn f42(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<Value> = Vec::with_capacity(1);
    let t3 = l0.clone();
    let t4 = rt.member(&t3, "currentTarget")?;
    let t5 = rt.member(&t4, "value")?;
    t2.push(t5);
    let t6 = f10(rt, &[], t2, None)?;
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 269).
fn f43(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let t1 = rt.global(20);
    let t2 = rt.member(&t1, "update")?;
    let mut t3: Vec<Value> = Vec::with_capacity(1);
    let t4 = closure(44, vec![]);
    t3.push(t4);
    let t5 = rt.call(&t2, t3)?;
    return Ok(t5);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 269).
fn f44(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = rt.member(&t2, "editing")?;
    let t4 = if t3.truthy() {
        let t5 = l0.clone();
        t5
    } else {
        let mut t6: Vec<(Str, Value)> = Vec::with_capacity(2);
        let t7 = l0.clone();
        obj_spread(&mut t6, &t7);
        obj_put(&mut t6, "editing", Value::Bool(true));
        let t8 = Value::object(t6);
        t8
    };
    return Ok(t4);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 83).
fn f45(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<(Str, Value)> = Vec::with_capacity(6);
    let t3 = l0.clone();
    obj_spread(&mut t2, &t3);
    let t4 = read(&cap[0]);
    obj_put(&mut t2, "open", t4);
    obj_put(&mut t2, "editing", Value::Bool(true));
    obj_put(&mut t2, "text", str(""));
    obj_put(&mut t2, "dirty", Value::Bool(true));
    let t5 = l0.clone();
    let t6 = rt.member(&t5, "entries")?;
    let mut t7: Vec<Value> = Vec::with_capacity(1);
    let t8 = read(&cap[0]);
    t7.push(t8);
    let t9 = rt.call_method(&t6, Method::ArrayIncludes, t7)?;
    let t10 = if t9.truthy() {
        let t11 = l0.clone();
        let t12 = rt.member(&t11, "entries")?;
        t12
    } else {
        let mut t13: Vec<Value> = Vec::with_capacity(2);
        let t14 = l0.clone();
        let t15 = rt.member(&t14, "entries")?;
        rt.spread(&mut t13, &t15)?;
        let t16 = read(&cap[0]);
        t13.push(t16);
        let t17 = Value::array(t13);
        let mut t18: Vec<Value> = Vec::with_capacity(1);
        let t19 = rt.global(3);
        t18.push(t19);
        let t20 = rt.call_method(&t17, Method::ArraySort, t18)?;
        t20
    };
    obj_put(&mut t2, "entries", t10);
    let t21 = Value::object(t2);
    return Ok(t21);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 200).
fn f46(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut occ = [0u32; 1];
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = key_of(&t2);
    let t4 = inst.is_some() && rt.is_pure_render();
    let t5 = if t4 { occ[0] += 1; occ[0] } else { 0 };
    let mut t6 = rt.tpl_begin(t4, 15, t5, 11, 5);
    let t7: Vec<Value> = if t6.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t6, 0, false, &t7) {
        Some(v) => rt.tpl_push(&mut t6, v, t7, false),
        None => {
            let mut t8 = String::new();
            t8.push_str("notes:open:");
            let t9 = l0.clone();
            t8.push_str(&t9.to_js_string());
            let t10 = Value::str(&t8);
            rt.tpl_push(&mut t6, t10, t7, true);
        }
    }
    let t11: Vec<Value> = if t6.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t6, 1, false, &t11) {
        Some(v) => rt.tpl_push(&mut t6, v, t11, false),
        None => {
            let t12 = l0.clone();
            rt.tpl_push(&mut t6, t12, t11, true);
        }
    }
    let t13: Vec<Value> = if t6.caching() { vec![read(&l0), read(&cap[0])] } else { Vec::new() };
    match rt.tpl_reuse(&t6, 2, false, &t13) {
        Some(v) => rt.tpl_push(&mut t6, v, t13, false),
        None => {
            let t14 = read(&cap[0]);
            let t15 = rt.member(&t14, "open")?;
            let t16 = l0.clone();
            let t17 = Value::Bool(strict_equals(&t15, &t16));
            let t18 = if t17.truthy() {
                str("row on")
            } else {
                str("row")
            };
            rt.tpl_push(&mut t6, t18, t13, true);
        }
    }
    let t19: Vec<Value> = if t6.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t6, 3, false, &t19) {
        Some(v) => rt.tpl_push(&mut t6, v, t19, false),
        None => {
            let t20 = closure(47, vec![l0.clone()]);
            rt.tpl_push(&mut t6, t20, t19, true);
        }
    }
    let t21: Vec<Value> = if t6.caching() { vec![read(&l0)] } else { Vec::new() };
    match rt.tpl_reuse(&t6, 4, false, &t21) {
        Some(v) => rt.tpl_push(&mut t6, v, t21, false),
        None => {
            let t22 = l0.clone();
            let mut t23: Vec<Value> = Vec::with_capacity(2);
            let t24 = rt.regex("\\.txt$", "")?;
            t23.push(t24);
            t23.push(str(""));
            let t25 = rt.call_method(&t22, Method::StrReplace, t23)?;
            rt.tpl_push(&mut t6, t25, t21, true);
        }
    }
    let t26 = rt.tpl_finish(t6, t3);
    return Ok(t26);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 206).
fn f47(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut t1: Vec<Value> = Vec::with_capacity(1);
    let t2 = read(&cap[0]);
    t1.push(t2);
    let t3 = f8(rt, &[], t1, None)?;
    return Ok(t3);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 101).
fn f48(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = rt.global(20);
    let t3 = rt.member(&t2, "update")?;
    let mut t4: Vec<Value> = Vec::with_capacity(1);
    let t5 = closure(49, vec![cap[0].clone(), l0.clone()]);
    t4.push(t5);
    let t6 = rt.call(&t3, t4)?;
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 102).
fn f49(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let t2 = l0.clone();
    let t3 = rt.member(&t2, "open")?;
    let t4 = read(&cap[0]);
    let t5 = Value::Bool(strict_equals(&t3, &t4));
    let t6 = if t5.truthy() {
        let mut t7: Vec<(Str, Value)> = Vec::with_capacity(3);
        let t8 = l0.clone();
        obj_spread(&mut t7, &t8);
        let t9 = read(&cap[1]);
        obj_put(&mut t7, "text", t9);
        obj_put(&mut t7, "dirty", Value::Bool(false));
        let t10 = Value::object(t7);
        t10
    } else {
        let t11 = l0.clone();
        t11
    };
    return Ok(t6);
    Ok(Value::Undefined)
}

/// `<arrow>` (line 104).
fn f50(rt: &mut Runtime, cap: &[Value], args: Vec<Value>, inst: Option<u32>) -> R<Value> {
    let mut l0: Value = Value::Undefined; 
    let mut args = args.into_iter();
    let t1 = args.next().unwrap_or(Value::Undefined);
    l0 = t1;
    let mut t2: Vec<Value> = Vec::with_capacity(1);
    let mut t3: Vec<Value> = Vec::with_capacity(1);
    let t4 = l0.clone();
    t3.push(t4);
    let t5 = f4(rt, &[], t3, None)?;
    t2.push(t5);
    let t6 = rt.call_builtin(Builtin::CwRefuse, t2)?;
    return Ok(t6);
    Ok(Value::Undefined)
}

/// The module's globals, in declaration order.
fn init(rt: &mut Runtime) -> R<()> {
    let cap: &[Value] = &[];
    let inst: Option<u32> = None;
    rt.set_global(0, closure(0, Vec::new()));
    rt.set_global(1, closure(1, Vec::new()));
    rt.set_global(2, closure(2, Vec::new()));
    rt.set_global(3, closure(3, Vec::new()));
    rt.set_global(4, closure(4, Vec::new()));
    rt.set_global(5, closure(5, Vec::new()));
    rt.set_global(6, closure(6, Vec::new()));
    rt.set_global(7, closure(7, Vec::new()));
    rt.set_global(8, closure(8, Vec::new()));
    rt.set_global(9, closure(9, Vec::new()));
    rt.set_global(10, closure(10, Vec::new()));
    rt.set_global(11, closure(11, Vec::new()));
    rt.set_global(12, closure(12, Vec::new()));
    rt.set_global(13, closure(13, Vec::new()));
    rt.set_global(14, closure(14, Vec::new()));
    rt.set_global(15, closure(15, Vec::new()));
    rt.set_global(16, closure(16, Vec::new()));
    rt.set_global(17, closure(17, Vec::new()));
    rt.set_global(18, closure(18, Vec::new()));
    let t1 = Value::Num(Value::Num(64.0).to_number() * Value::Num(1024.0).to_number());
    rt.set_global(19, t1);
    let mut t2: Vec<Value> = Vec::with_capacity(1);
    let t3 = closure(24, vec![]);
    t2.push(t3);
    let t4 = f0(rt, &[], t2, None)?;
    rt.set_global(20, t4);
    let mut t5: Vec<Value> = Vec::with_capacity(1);
    let mut t6: Vec<Value> = Vec::with_capacity(11);
    t6.push(str("Backspace"));
    t6.push(str("Delete"));
    t6.push(str("Enter"));
    t6.push(str("ArrowLeft"));
    t6.push(str("ArrowRight"));
    t6.push(str("ArrowUp"));
    t6.push(str("ArrowDown"));
    t6.push(str("Home"));
    t6.push(str("End"));
    t6.push(str("PageUp"));
    t6.push(str("PageDown"));
    let t7 = Value::array(t6);
    t5.push(t7);
    let t8 = rt.call_builtin(Builtin::NewSet, t5)?;
    rt.set_global(21, t8);
    Ok(())
}

}
