// Generator input for crates/web/engine/tests/vendor/tailwind-3.4.17.css. Regenerated by
// crates/web/engine/tools/fetch-vendor.sh with `npx tailwindcss@3.4.17`; see that script for
// the exact command. `content` scans the parity fixture for the classes it uses, and
// `safelist` pads the sheet with whole utility scales (colours, spacing, sizing, ...)
// so the generated stylesheet carries roughly 3,000 rules regardless of which classes
// the fixture happens to use - the point is a broad, representative Tailwind sheet for
// the layout engine to be tested against, not a minimal one.
//
// Deterministic: no plugins beyond the ones Tailwind ships with, no environment-derived
// values, so the same tailwindcss version always produces byte-identical output.
const path = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [path.join(__dirname, '../../tests/script/tailwind.html')],
  safelist: [
    // Full colour scales across backgrounds, text, borders, rings and divide colours,
    // including a few interactive variants, so preflight-adjacent chains (bg-opacity,
    // border-opacity, ring-*, divide-*) all have real generated rules to assert against.
    {pattern: /^bg-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/},
    {pattern: /^text-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/},
    {pattern: /^border-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/},
    {pattern: /^ring-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/},
    {pattern: /^divide-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/},
    {pattern: /^(bg|text|border)-(slate|gray|red|blue|green|indigo|purple|pink)-(100|300|500|700|900)$/, variants: ['hover', 'focus', 'group-hover']},
    // Spacing scale (margin, padding, gap, space-between, inset) across all sides.
    {pattern: /^(m|p)(t|r|b|l|x|y)?-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96)$/},
    {pattern: /^-?(m)(t|r|b|l|x|y)?-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|8|10|12|16|20|24)$/},
    {pattern: /^gap(-x|-y)?-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96)$/},
    {pattern: /^space-(x|y)-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96)$/},
    {pattern: /^(inset(-x|-y)?|top|right|bottom|left)-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|8|10|12|16|20|24|1\/2|1\/3|2\/3|1\/4|full)$/},
    // Sizing (width, height, min/max) including fractions.
    {pattern: /^(w|h)-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96|auto|full|screen|min|max|fit|1\/2|1\/3|2\/3|1\/4|2\/4|3\/4|1\/5|2\/5|3\/5|4\/5|1\/6|5\/6|1\/12)$/},
    {pattern: /^(min|max)-(w|h)-(0|full|screen|min|max|fit|xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|none)$/},
    // Typography, radii, shadows, opacity, borders, transforms and filters, so every
    // --tw-* custom-property chain the fixture uses has neighbouring generated rules.
    {pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl)$/},
    {pattern: /^font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black)$/},
    {pattern: /^leading-(3|4|5|6|7|8|9|10|none|tight|snug|normal|relaxed|loose)$/},
    {pattern: /^tracking-(tighter|tight|normal|wide|wider|widest)$/},
    {pattern: /^rounded(-(none|sm|md|lg|xl|2xl|3xl|full))?$/},
    {pattern: /^rounded-(t|r|b|l|tl|tr|br|bl)(-(none|sm|md|lg|xl|2xl|3xl|full))?$/},
    {pattern: /^shadow(-(sm|md|lg|xl|2xl|inner|none))?$/},
    {pattern: /^opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/},
    {pattern: /^bg-opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/},
    {pattern: /^text-opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/},
    {pattern: /^border-opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/},
    {pattern: /^ring-opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/},
    {pattern: /^divide-opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/},
    {pattern: /^border(-(0|2|4|8))?$/},
    {pattern: /^border-(t|r|b|l)(-(0|2|4|8))?$/},
    {pattern: /^divide-(x|y)(-(0|2|4|8|reverse))?$/},
    {pattern: /^ring(-(0|1|2|4|8|inset))?$/},
    {pattern: /^ring-offset-(0|1|2|4|8)$/},
    {pattern: /^(scale|scale-x|scale-y)-(0|50|75|90|95|100|105|110|125|150)$/},
    {pattern: /^(rotate)-(0|1|2|3|6|12|45|90|180)$/},
    {pattern: /^(translate-x|translate-y)-(0|px|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|8|10|12|16|20|24|1\/2|1\/3|2\/3|1\/4|full)$/},
    {pattern: /^skew-(x|y)-(0|1|2|3|6|12)$/},
    {pattern: /^blur(-(none|sm|md|lg|xl|2xl|3xl))?$/},
    {pattern: /^backdrop-blur(-(none|sm|md|lg|xl|2xl|3xl))?$/},
    {pattern: /^backdrop-(brightness|contrast|saturate)-(0|50|75|90|95|100|105|110|125|150|200)$/},
    // Flex/grid so grid-template-columns, gap and flex-basis are all well represented.
    {pattern: /^grid-cols-(1|2|3|4|5|6|7|8|9|10|11|12|none)$/},
    {pattern: /^col-span-(1|2|3|4|5|6|7|8|9|10|11|12|full)$/},
    {pattern: /^grid-rows-(1|2|3|4|5|6|none)$/},
    {pattern: /^(flex|basis)-(1|auto|initial|none|0|1\/2|1\/3|2\/3|1\/4|full)$/},
    // z-index and outline, rounding out the preflight-adjacent utilities.
    {pattern: /^z-(0|10|20|30|40|50|auto)$/},
    {pattern: /^outline-(none|white|black|dashed|dotted)$/, variants: ['focus', 'focus-visible']},
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
