#!/usr/bin/env python3
"""Regenerates src/locale_data.rs from the host's glibc locales and CLDR.

Run manually (never from a test) when the locale list changes:

    python3 crates/languages/pyvm/tools/generate_locales.py

What CPython answers for a locale — `localeconv()`, `nl_langinfo()` names and
patterns — is recorded here so the simulated interpreter answers the same. A
locale glibc does not have on this machine (Arabic, Hindi) is filled in from the
CLDR data the simulated `node` already carries, which is marked in the table.
"""
import json
import locale
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "locale_data.rs")
CLDR = os.path.join(HERE, "..", "..", "jsvm", "data", "cldr.json")

# The locales the simulated interpreter knows, in the order they are listed.
LOCALES = [
    ("en_US.UTF-8", "en-US"),
    ("en_GB.UTF-8", "en-GB"),
    ("de_DE.UTF-8", "de-DE"),
    ("fr_FR.UTF-8", "fr-FR"),
    ("es_ES.UTF-8", "es-ES"),
    ("it_IT.UTF-8", "it-IT"),
    ("pt_BR.UTF-8", "pt-BR"),
    ("ja_JP.UTF-8", "ja-JP"),
    ("zh_CN.UTF-8", "zh-CN"),
    ("zh_TW.UTF-8", "zh-TW"),
    ("ko_KR.UTF-8", "ko-KR"),
    ("ru_RU.UTF-8", "ru-RU"),
    ("ar_EG.UTF-8", "ar-EG"),
    ("hi_IN.UTF-8", "hi-IN"),
]

CONV_KEYS = [
    "decimal_point", "thousands_sep", "grouping", "int_curr_symbol",
    "currency_symbol", "mon_decimal_point", "mon_thousands_sep", "mon_grouping",
    "positive_sign", "negative_sign", "int_frac_digits", "frac_digits",
    "p_cs_precedes", "p_sep_by_space", "n_cs_precedes", "n_sep_by_space",
    "p_sign_posn", "n_sign_posn",
]


def from_glibc(name):
    locale.setlocale(locale.LC_ALL, name)
    conv = locale.localeconv()
    li = locale.nl_langinfo
    out = {
        "conv": {k: conv[k] for k in CONV_KEYS},
        "days": [li(getattr(locale, f"DAY_{i}")) for i in range(1, 8)],
        "abdays": [li(getattr(locale, f"ABDAY_{i}")) for i in range(1, 8)],
        "months": [li(getattr(locale, f"MON_{i}")) for i in range(1, 13)],
        "abmonths": [li(getattr(locale, f"ABMON_{i}")) for i in range(1, 13)],
        "am_pm": [li(locale.AM_STR), li(locale.PM_STR)],
        "d_t_fmt": li(locale.D_T_FMT),
        "d_fmt": li(locale.D_FMT),
        "t_fmt": li(locale.T_FMT),
        "t_fmt_ampm": li(locale.T_FMT_AMPM),
        "codeset": li(locale.CODESET),
        "source": "glibc",
    }
    locale.setlocale(locale.LC_ALL, "C")
    return out


def from_cldr(tag, cldr):
    """A locale glibc does not have here, built from the CLDR data instead."""
    d = cldr["locales"][tag]
    symbols = d["number"]["symbols"]
    # CLDR's weekday list starts on Sunday; glibc's `DAY_1` is Sunday too.
    return {
        "conv": {
            "decimal_point": symbols["decimal"],
            "thousands_sep": symbols["group"],
            "grouping": [3, 3, 0] if d["number"]["grouping"][1] == 3 else [3, 2, 0],
            "int_curr_symbol": "EGP " if tag == "ar-EG" else "INR ",
            "currency_symbol": d["currencies"]["EGP" if tag == "ar-EG" else "INR"][0],
            "mon_decimal_point": symbols["decimal"],
            "mon_thousands_sep": symbols["group"],
            "mon_grouping": [3, 3, 0] if d["number"]["grouping"][1] == 3 else [3, 2, 0],
            "positive_sign": "",
            "negative_sign": symbols["minus"],
            "int_frac_digits": 2,
            "frac_digits": 2,
            "p_cs_precedes": 1,
            "p_sep_by_space": 1,
            "n_cs_precedes": 1,
            "n_sep_by_space": 1,
            "p_sign_posn": 1,
            "n_sign_posn": 1,
        },
        "days": d["weekdays"]["long"],
        "abdays": d["weekdays"]["short"],
        "months": d["months"]["long"],
        "abmonths": d["months"]["short"],
        "am_pm": d["dayPeriods"],
        "d_t_fmt": "%a %d %b %Y %r" if tag == "ar-EG" else "%A %d %B %Y %I:%M:%S %p",
        "d_fmt": "%d/%m/%Y" if tag == "ar-EG" else "%A %d %b %Y",
        "t_fmt": "%I:%M:%S %p" if tag == "ar-EG" else "%I:%M:%S  %p",
        "t_fmt_ampm": "%I:%M:%S %p",
        "codeset": "UTF-8",
        "source": "cldr",
    }


def rust(value):
    if isinstance(value, str):
        # Rust wants `\u{e4}`, not JSON's `\u00e4`, so the text goes in as it is.
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "&[" + ", ".join(rust(v) for v in value) + "]"
    if isinstance(value, int):
        return str(value)
    raise TypeError(value)


def main():
    cldr = json.load(open(CLDR))
    rows = []
    for name, tag in LOCALES:
        try:
            data = from_glibc(name)
        except locale.Error:
            data = from_cldr(tag, cldr)
            print(f"{name}: not installed here, taken from CLDR", file=sys.stderr)
        rows.append((name, tag, data))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(
            "//! Generated by `tools/generate_locales.py`. Do not edit.\n"
            "//!\n"
            "//! What CPython answers for each locale: `localeconv()`, the names and\n"
            "//! patterns `nl_langinfo()` gives, recorded from the host's glibc (or, for a\n"
            "//! locale glibc does not have there, from CLDR - the `from_cldr` flag).\n\n"
            "pub struct LocaleData {\n"
            "    pub name: &'static str,\n"
            "    pub tag: &'static str,\n"
            "    pub from_cldr: bool,\n"
            "    /// `localeconv()` strings, in the order of `CONV_KEYS`.\n"
            "    pub conv_text: &'static [(&'static str, &'static str)],\n"
            "    /// `localeconv()` numbers.\n"
            "    pub conv_num: &'static [(&'static str, i64)],\n"
            "    pub grouping: &'static [i64],\n"
            "    pub mon_grouping: &'static [i64],\n"
            "    pub days: &'static [&'static str; 7],\n"
            "    pub abdays: &'static [&'static str; 7],\n"
            "    pub months: &'static [&'static str; 12],\n"
            "    pub abmonths: &'static [&'static str; 12],\n"
            "    pub am_pm: &'static [&'static str; 2],\n"
            "    pub d_t_fmt: &'static str,\n"
            "    pub d_fmt: &'static str,\n"
            "    pub t_fmt: &'static str,\n"
            "    pub t_fmt_ampm: &'static str,\n"
            "    pub codeset: &'static str,\n"
            "}\n\n"
            "pub static LOCALES: &[LocaleData] = &[\n"
        )
        for name, tag, d in rows:
            text_keys = [k for k in CONV_KEYS if isinstance(d["conv"][k], str)]
            num_keys = [k for k in CONV_KEYS
                        if isinstance(d["conv"][k], int) and k not in ("grouping", "mon_grouping")]
            f.write("    LocaleData {\n")
            f.write(f"        name: {json.dumps(name, ensure_ascii=False)},\n")
            f.write(f"        tag: {json.dumps(tag, ensure_ascii=False)},\n")
            f.write(f"        from_cldr: {str(d['source'] == 'cldr').lower()},\n")
            f.write("        conv_text: &[")
            f.write(", ".join(f"({json.dumps(k, ensure_ascii=False)}, {json.dumps(d['conv'][k], ensure_ascii=False)})" for k in text_keys))
            f.write("],\n")
            f.write("        conv_num: &[")
            f.write(", ".join(f"({json.dumps(k, ensure_ascii=False)}, {d['conv'][k]})" for k in num_keys))
            f.write("],\n")
            f.write(f"        grouping: {rust([int(x) for x in d['conv']['grouping']])},\n")
            f.write(f"        mon_grouping: {rust([int(x) for x in d['conv']['mon_grouping']])},\n")
            for key in ["days", "abdays", "months", "abmonths", "am_pm"]:
                f.write(f"        {key}: &{rust(d[key])[1:]},\n")
            for key in ["d_t_fmt", "d_fmt", "t_fmt", "t_fmt_ampm", "codeset"]:
                f.write(f"        {key}: {json.dumps(d[key], ensure_ascii=False)},\n")
            f.write("    },\n")
        f.write("];\n")
    print(f"{OUT}: {os.path.getsize(OUT)} bytes for {len(rows)} locales", file=sys.stderr)


if __name__ == "__main__":
    main()
