#!/usr/bin/env node
// Seed the reference desktops' home folders from files in the repository.
//
// Content lives as ordinary files under worlds/company-2026/home, never as JSON string
// literals in world.json:
//
//   worlds/company-2026/home/all/<path>        every desktop computer
//   worlds/company-2026/home/<profile>/<path>  one OS profile (macos, windows, ubuntu);
//                                              overlays `all`, so the same path wins here
//
// `<path>` is relative to the user's home folder. Files that are valid UTF-8 go into
// `initial_files`; anything else travels base64-encoded in `initial_binary_files`. The
// two hand-written top-level files (launch.txt, notes.txt) of each computer are kept;
// everything else under those keys is replaced, so re-running is a no-op and CI can diff.
//
// Engine-authored artifacts (FreeCAD documents from crates/cad, KiCad projects from
// crates/eda) are regenerated by their `samples` tests with CW_UPDATE_SAMPLES=1 and
// checked in here like everything else.
import {readdir, readFile, stat} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {readWorld, write, worldUrl} from './build-world.mjs';

export const homeUrl = new URL('../worlds/company-2026/home/', import.meta.url);
/// The computers that are someone's desk. Servers keep their two files only.
const DESKTOPS = ['alice-mac', 'bob-windows', 'carol-ubuntu'];
/// The hand-written files every computer starts with, kept as they are.
const KEEP = new Set(['launch.txt', 'notes.txt']);
/// A generous ceiling: world.json is embedded in the Wasm bundle and every native build.
const MAX_BYTES_PER_COMPUTER = 3 * 1024 * 1024;

async function walk(dir, prefix, out) {
  let names;
  try {
    names = (await readdir(dir)).sort();
  } catch (e) {
    if (e.code === 'ENOENT') return out;
    throw e;
  }
  for (const name of names) {
    if (name === '.DS_Store') continue;
    const url = new URL(name, dir);
    const info = await stat(url);
    const path = prefix ? `${prefix}/${name}` : name;
    if (info.isDirectory()) await walk(new URL(`${name}/`, dir), path, out);
    else out.set(path, await readFile(url));
  }
  return out;
}

function isUtf8(bytes) {
  try {
    new TextDecoder('utf-8', {fatal: true}).decode(bytes);
    return true;
  } catch {
    return false;
  }
}

/// The seeded files of one profile: `all` first, the profile's own on top.
export async function seededFiles(profile) {
  const files = await walk(new URL('all/', homeUrl), '', new Map());
  await walk(new URL(`${profile}/`, homeUrl), '', files);
  return files;
}

async function main() {
  const world = await readWorld();
  const summary = [];
  for (const id of DESKTOPS) {
    const computer = world.computers.find((c) => c.id === id);
    if (!computer) throw new Error(`build-home: no computer "${id}" in world.json`);
    const files = await seededFiles(computer.profile);
    const text = {};
    const binary = {};
    for (const path of Object.keys(computer.initial_files ?? {})) if (KEEP.has(path)) text[path] = computer.initial_files[path];
    let bytes = 0;
    let binaries = 0;
    for (const [path, data] of files) {
      bytes += data.length;
      if (isUtf8(data)) text[path] = data.toString('utf8');
      else {
        binary[path] = data.toString('base64');
        binaries += 1;
      }
    }
    if (bytes > MAX_BYTES_PER_COMPUTER) {
      throw new Error(`build-home: ${id} would seed ${bytes} bytes; the limit is ${MAX_BYTES_PER_COMPUTER}`);
    }
    computer.initial_files = Object.fromEntries(Object.entries(text).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
    if (binaries > 0) {
      computer.initial_binary_files = Object.fromEntries(Object.entries(binary).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
    } else {
      delete computer.initial_binary_files;
    }
    summary.push(`${id} (${computer.profile}): ${files.size} files, ${bytes} bytes${binaries ? `, ${binaries} binary` : ''}`);
  }
  await write(worldUrl, world);
  const size = (await stat(worldUrl)).size;
  console.log(`Seeded home folders from worlds/company-2026/home:\n  ${summary.join('\n  ')}\nworld.json is ${size} bytes.`);
}
if (import.meta.url === pathToFileURL(process.argv[1]).href) await main();
