/* Real wasm execution; no browser, subprocess simulator, or network needed. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { World, SceneRenderer } = require('../pkg/node/computerworld.js');
const definition = JSON.parse(fs.readFileSync(path.join(__dirname,'../worlds/company-2026/world.json'),'utf8'));
const config = {actor:'alice',machines:['alice-mac'],actions:['terminal.v1','browser.v1'],observations:['terminal.v1','semantic.v1']};
const actions = [{family:'terminal.v1',op:'execute',machine:'alice-mac',payload:{command:'echo binding-parity'}}];
const world = new World(definition, 42);
const env = world.environment(config);
const before = world.snapshot();
const initialHash = world.stateHash();
const result = env.step(actions);
assert(result.outcomes[0].success, JSON.stringify(result));
assert(JSON.stringify(result).includes('binding-parity'));
const afterHash = world.stateHash();
const portable = world.exportSnapshot();
world.restore(before);
assert.deepEqual(env.step(actions), result);
assert.equal(world.stateHash(), afterHash);
const fork = world.fork(world.snapshot());
assert.equal(fork.stateHash(), afterHash);
assert.deepEqual(fork.session(env.id).observe(), env.observe());
const gui = fork.environment({actor:'alice',machines:['alice-mac'],actions:['browser.v1','pointer.v1'],observations:['semantic.v1']});
assert(gui.step([{family:'browser.v1',op:'navigate',machine:'alice-mac',payload:{url:'http://intranet.internal/'}}]).outcomes[0].success);
const link = gui.scene(960,560).nodes.find(n => n.semantic?.role === 'link' && n.interaction);
assert(link, 'expected an interactive intranet link');
const click = gui.step([{family:'pointer.v1',op:'click',machine:'alice-mac',payload:{x:link.bounds.x+2,y:link.bounds.y+2,width:960,height:560}}]);
assert(click.outcomes[0].success, JSON.stringify(click));
const imported = new World(definition, 0);
imported.importSnapshot(portable);
assert.equal(imported.stateHash(), afterHash);
assert.equal(env.inspect, undefined);
assert.equal(env.snapshot, undefined);
assert.equal(env.step([{family:'private.v1',op:'inspect',machine:'alice-mac'}]).outcomes[0].success, false);
const frame = env.render(320,240);
assert.equal(frame.rgba.length,320*240*4);
assert(frame.rgba instanceof Uint8Array);
assert(world.trajectory().length > 0);
assert.throws(()=>env.step('invalid'));
const renderer = new SceneRenderer();
const scene = {width:32,height:32,revision:0,nodes:[{id:1,bounds:{x:2,y:2,width:10,height:10},primitive:{kind:'box',fill:[20,30,40,255],border:null,border_width:0}}]};
const firstFrame = renderer.render(scene);
const changed = {...scene.nodes[0],primitive:{...scene.nodes[0].primitive,fill:[100,120,140,255]}};
const patched = renderer.patch({base_revision:0,revision:1,operations:[{op:'upsert',value:changed}]});
const fresh = new SceneRenderer().render({...scene,revision:1,nodes:[changed]});
assert.deepEqual(patched.rgba,fresh.rgba);
assert.notDeepEqual(firstFrame.rgba,patched.rgba);
assert.throws(()=>renderer.patch({base_revision:0,revision:1,operations:[]}));
const fixture = {width:160,height:90,revision:0,background:[10,20,30,255],nodes:[
  {id:1,bounds:{x:3,y:4,width:100,height:70},primitive:{kind:'box',fill:[100,200,30,128],border:null,border_width:0}},
  {id:2,bounds:{x:8,y:8,width:130,height:65},primitive:{kind:'text',text:'Hello world\nDeterministic λ',size:16,color:[255,255,255,255]}}
]};
const fixtureHash = require('node:crypto').createHash('sha256').update(renderer.render(fixture).rgba).digest('hex');
assert.equal(fixtureHash,'01455c4eaa6c1eca6900b545f69bba35ad9428fb66275a41df86268ae3595ec6');
const metadata = JSON.parse('{"__proto__":{"polluted":true}}');
const dataWorld = new World({...definition,metadata},0);
assert.equal(dataWorld.definition().metadata.__proto__.polluted,true);
assert.equal({}.polluted,undefined);
assert.throws(()=>new World(definition,-1));
assert.throws(()=>new World(definition,1.5));
const maxSeed = new World(definition, '18446744073709551615');
assert.equal(maxSeed.stateHash(),new World(definition,18446744073709551615n).stateHash());
world.reset(42);
assert.equal(world.stateHash(),initialHash);
assert.deepEqual(env.observe(),world.session(env.id).observe());
if (process.argv[2]) fs.writeFileSync(process.argv[2],JSON.stringify({hash:afterHash,snapshot:portable}));
console.log(JSON.stringify({runtime:'wasm',hash:afterHash,rgba_bytes:frame.rgba.length}));
