// console.log / util.inspect formatting
const util = require('util');
const log = console.log;
log({ a: 1, b: { c: { d: { e: { f: 1 } } } }, arr: [[1, [2, [3, [4]]]]] });
log([1, 'two', { three: 3 }, [4], null, undefined, true, 5n, Symbol('six'), () => 7, function named() {}, class K {}]);
log(new Map([['key', { nested: [1, 2] }], [{ obj: 1 }, 'val']]), new Set(['a', { b: 1 }, [2]]));
log(Array.from({ length: 26 }, (_, i) => String.fromCharCode(97 + i)));
log(Array.from({ length: 12 }, (_, i) => ({ id: i })));
log(Array.from({ length: 7 }, (_, i) => i * 1000000));
log(['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape', 'honeydew', 'kiwi']);
log({ longKeyNumberOne: 'value one is here', longKeyNumberTwo: 'value two is here', k3: 'v3' });
log({ 'key-with-dash': 1, 'valid_id': 2, '3d': 3, '': 4, 'with space': 5, [Symbol('sym')]: 6, 7: 'seven' });
const circ = { name: 'root', child: { name: 'child' } };
circ.child.parent = circ;
circ.self = circ;
log(circ);
const arr = [1, 2];
arr.push(arr);
log(arr);
log(util.inspect({ a: { b: { c: { d: {} } } } }, { depth: 0 }), util.inspect({ a: { b: { c: { d: 1 } } } }, { depth: null }));
log(util.inspect('str'), util.inspect([1, 2, 3], { compact: false }), util.inspect({ a: 1, b: 2 }, { breakLength: 3 }));
log(util.format('%s:%i:%f:%j %o', 'x', 3.9, '2.5', { j: 1 }, [1]), util.format('no args %s'), util.format(1, 2, '3'));
log(new Error('plain message').message, [new Error('in array').name]);
log(Object.create(null), Object.create({ inherited: 1 }), new (class Foo { constructor() { this.x = 1; } })());
class Point { constructor(x, y) { this.x = x; this.y = y; } [util.inspect.custom]() { return `Point<${this.x},${this.y}>`; } }
log(new Point(1, 2), [new Point(3, 4)], { p: new Point(5, 6) });
log([undefined, , null, , , 3], new Array(3), [1, 2, 3].keys(), new Map([[1, 2]]).entries(), 'abc'[Symbol.iterator]());
log(new Date(Date.UTC(2020, 0, 15, 10, 30)), /re+/gi, new Boolean(true), new Number(-0), new String('boxed'), Object(Symbol('bx')), Object(10n));
log(Promise.resolve({ v: 1 }), Promise.reject(new Error('r')).catch(() => {}) && 'ok', new Promise(() => {}));
log(new WeakMap(), new WeakSet(), Symbol.iterator, Symbol(), Symbol('with space'));
log([1.5, -0, 0, NaN, Infinity, -Infinity, 1e100, 2 ** -1074, 0x10], [1n, -2n]);
log({ f: function () {}, g: () => {}, h: async () => {}, i: function* () {}, j: Math.max, k: class {}, l: class Bar extends Array {} });
log(Buffer.from('hi there'), new Uint8Array([1, 2, 3]), new Float64Array(2), new ArrayBuffer(4), new Int16Array([-1, 300]));
log('%c styled', 'color: red', 'next');
log('%%', '%d%%', 50, '%s', { toString() { return 'custom toString'; } });
log(process.argv.length >= 2, typeof process.env, process.platform, typeof process.version, process.exitCode);
const big = {};
for (let i = 0; i < 30; i++) big['key' + i] = i;
log(big);
log([['nested', 'array'], ['of', 'arrays']], { matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] });
log('a'.repeat(100));
log({ s: 'b'.repeat(90) });
log([{ a: 1, b: 2 }, { a: 3, b: 4 }]);
console.error('to stderr', { e: 1 });
console.info('info'); console.warn('warn'); console.debug('debug');
console.group('Group A'); log('inside'); console.group(); log('nested'); console.groupEnd(); console.groupEnd(); log('outside');
console.table([{ a: 1, b: 'x' }, { a: 2, c: true }]);
console.table({ r1: { c1: 1 }, r2: { c2: 2 } });
console.count(); console.count('x'); console.count(); console.countReset(); console.count();
console.assert(1 === 1, 'not shown'); console.assert(false, 'shown %s', 'formatted'); console.assert(false);
console.dir({ deep: { deeper: { deepest: { bottom: 1 } } } }, { depth: 0 });
