// Strings & regular expressions
const log = console.log;
const text = 'The quick brown fox jumps over the lazy dog. The dog sleeps.';
log(text.match(/the/gi), text.match(/(\w+) (\w+)/).slice(0, 3), text.search(/fox/), /dog/.test(text));
const re = /(?<word>\w+)s\b/g;
let m;
while ((m = re.exec(text)) !== null) log(m.index, m[0], m.groups.word, re.lastIndex);
log([...text.matchAll(/o(\w)/g)].map((x) => x[1] + '@' + x.index));
log(text.replace(/(\w+) (\w+)/, '$2 $1'), text.replace(/dog/g, (s, i) => s.toUpperCase() + i));
log('2024-01-15'.replace(/(?<y>\d+)-(?<m>\d+)-(?<d>\d+)/, '$<d>/$<m>/$<y>'));
log('a1b2c3'.split(/\d/), 'a1b2c3'.split(/(\d)/), 'one  two   three'.split(/\s+/), ''.split(','), 'abc'.split(''));
log('x'.padEnd(5, 'ab') + '|', 'Hello World'.split(' ').map((w) => w[0]).join(''), 'abc'.charCodeAt(1), String.fromCharCode(72, 105));
log(/^[\w.+-]+@\w+\.\w{2,}$/.test('user.name+tag@example.com'), /^\d{3}-\d{4}$/.test('555-1234'));
log('CamelCaseString'.replace(/([A-Z])/g, ' $1').trim(), 'snake_case_here'.replace(/_(\w)/g, (_, c) => c.toUpperCase()));
log(new RegExp('a+b', 'g').toString(), /x/gimsuy.flags, /[/]/.source, RegExp('\\d').source, /a/.global);
log('aaa'.replace(/a*?/g, '-'), 'abc'.replace(/(?:)/g, '.'), 'test'.replace(/t$/, 'T'));
log('%', 'multi\nline'.match(/^line$/m)[0], /a.b/s.test('a\nb'), /\bfoo\b/i.exec('a FOO b').index);
const csv = 'name,age\nalice,30\nbob,25';
const rows = csv.split('\n').slice(1).map((l) => { const [name, age] = l.split(','); return { name, age: Number(age) }; });
log(rows, rows.reduce((s, r) => s + r.age, 0) / rows.length);
log('Straße'.normalize('NFC').length, 'résumé'.toUpperCase(), 'İ'.toLowerCase().length, 'ß'.localeCompare('ss'));
log(['b', 'a', 'C', 'á'].sort((a, b) => a.localeCompare(b)), ['10', '9', '1'].sort((a, b) => a.localeCompare(b, undefined, { numeric: true })));
log(encodeURIComponent('a b&c=d/é'), decodeURIComponent('%E2%9C%93'), encodeURI('http://x.com/a b?q=1&r=é'), escape('a b'), unescape('%41'));
log(btoa('hello'), atob('aGVsbG8='), Buffer.from('héllo').toString('base64'), Buffer.from('aGk=', 'base64').toString());
log('abc'.at(-4), 'abc'.substring(2, 0), 'abc'.substr(-2, 1), 'abcdef'.slice(-3, -1), 'a-b-c'.lastIndexOf('-'), 'aXbX'.indexOf('X', 2));
log(`${1 + 1} ${[1, 2]} ${{}} ${null} ${undefined} ${() => 1}`);
log(String(Symbol('d')), `${String(123n)}`, [1, [2, [3]]] + '', String([null, undefined, 1]));
log('trimStart'.padStart(12, '*').trimStart(), '\t x \n'.trim().length, ' a '.trimEnd() + '|');
log('abc'.codePointAt(0), '😀'.codePointAt(0), '😀'.charCodeAt(0), String.fromCodePoint(0x1f600), [...'a😀b'].length, 'a😀b'.length);
log('x'.repeat(0) === '', 'ab'.concat('cd', 1, null), 'Hello'.startsWith('ell', 1), 'Hello'.endsWith('ell', 4), 'a,b'.split(',', 1));
log(JSON.stringify('he said "hi"\n\t'), JSON.stringify({ k: 'v' }, null, '\t'), JSON.stringify([undefined, () => 1, Symbol('s')]));
log(parseInt('ff', 16), parseInt('z', 36), (255).toString(2), Number('1e3'), Number('0b101'), Number('12abc'), Number.parseFloat('.5e1'));
log('Is it true?'.replaceAll('t', 'T'), 'a.b.c'.replaceAll('.', '/'), 'aaa'.replaceAll('aa', 'b'), 'xyz'.replace('y', '$&$&'));
const tpl = (strings, ...keys) => strings.reduce((acc, s, i) => acc + s + (keys[i] !== undefined ? `[${keys[i]}]` : ''), '');
log(tpl`Hello ${'world'} and ${42}!`, String.raw`a\nb${1}`);
