[package]
name = "cw-environment"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
cw-protocol = { path = "../protocol" }
cw-kernel = { path = "../kernel" }
cw-browser = { path = "../browser" }
cw-applications = { path = "../applications" }
cw-scene = { path = "../scene" }
cw-trajectory = { path = "../trajectory" }
serde.workspace = true
serde_json.workspace = true
cw-sdk = { path = "../sdk" }
